// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni


export enum AnimationType {
    LINEAR = 0,
    EASEIN = 1,
    EASEOUT = 2,
    EASEINOUT = 3,
}

export enum AttributeType {
    STRING = 0,
    DOUBLE = 1,
    INT = 2,
    BOOLEAN = 3,
    COLOR = 4,
    UNTYPED = 5,
}

export enum Platform {
    IOS = 0,
    ANDROID = 1,
    SKIA = 2,
}

export enum AssetOutputType {
    BYTES = 0,
    IMAGEIOS = 1,
    IMAGEANDROID = 2,
    IMAGESNAPDRAWING = 3,
    VIDEOIOS = 4,
    VIDEOANDROID = 5,
    LOTTIE = 6,
    DUMMY = 7,
}

export interface Animator {
    /** The Value is a wrapped completion callback */
    flushAnimations(completion: any): void;
    /** Cancel an animation */
    cancel(): void;
}

export interface AssetLoadObserver {
    onLoad(asset: Asset, loadedAsset: any, error: any | undefined): void;
}

/** Represents a loadable asset like an Image */
export interface Asset {
    /** Return a string that uniquely identifies this asset */
    getIdentifier(): any;
    /**
     * Measure the width that should be used for this asset
     * given a max width and height.
     */
    measureWidth(maxWidth: number, maxHeight: number): number;
    /**
     * Measure the height that should be used for this asset
     * given a max width and height.
     */
    measureHeight(maxWidth: number, maxHeight: number): number;
    /**
     * Append a load observer, which will be notified
     * when the asset is loaded.
     */
    addLoadObserver(observer: AssetLoadObserver, outputType: AssetOutputType, preferredWidth: number, preferredHeight: number, filter: any): void;
    /** Remove a previously registered load observer */
    removeLoadObserver(observer: AssetLoadObserver): void;
    /** Update the preferred width and height of a previously registered load observer */
    updateLoadObserverPreferredSize(observer: AssetLoadObserver, preferredWidth: number, preferredHeight: number): void;
}

export interface Cancelable {
    cancel(): void;
}

export interface /*record*/ CompositeAttributePart {
    attribute: any;
    type: AttributeType;
    optional: boolean;
    invalidateLayoutOnChange: boolean;
}

export interface ModuleFactory {
    /**
     * Return the path of the module, which represents its path
     * when imported from TypeScript.
     */
    getModulePath(): any;
    /**
     * Returns the module exports object that should be returned to
     * TypeScript when the module is imported.
     */
    loadModule(): any;
}

/**
 * The ModuleFactoriesProvider will be invoked when the RuntimeManager is initialized
 * to provide additional built-in Modules that will be exposed to the JS runtime environment.
 */
export interface ModuleFactoriesProvider {
    /** Create and return the module factories that will be exposed to the JS runtime environment. */
    createModuleFactories(runtimeManager: any): Array<ModuleFactory>;
}

export interface /*record*/ HTTPRequest {
    url: any;
    method: any;
    headers: any;
    body?: any;
    /** Between 0 being lowest, to 10 being maximum */
    priority: number;
}

export interface /*record*/ HTTPResponse {
    statusCode: number;
    headers: any;
    body?: any;
}

export interface HTTPRequestManagerCompletion {
    onComplete(response: HTTPResponse): void;
    onFail(error: string): void;
}

export interface HTTPRequestManager {
    performRequest(request: HTTPRequest, completion: HTTPRequestManagerCompletion): Cancelable;
}

export enum JavaScriptEngineType {
    AUTO = 0,
    QUICKJS = 1,
    JSCORE = 2,
    V8 = 3,
    HERMES = 4,
}

export interface ValdiCore_statics {
}
