// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

#pragma once

#include "valdi_core/cpp/Utils/StringBox.hpp"
#include "valdi_core/cpp/Utils/Value.hpp"
#include <cstdint>
#include <memory>

namespace snap::valdi {

class JSRuntimeNativeObjectsManager;

class JSRuntime {
public:
    virtual ~JSRuntime() = default;

    /**
     * Push the module unmarshalled using the schema in the given marshaller handle
     * into the marshaller.
     */
    virtual int32_t pushModuleToMarshaller(const /*not-null*/ std::shared_ptr<JSRuntimeNativeObjectsManager> & nativeObjectsManager, const Valdi::StringBox & path, int64_t marshallerHandle) = 0;

    virtual void addModuleUnloadObserver(const Valdi::StringBox & path, const Valdi::Value & observer) = 0;

    virtual void preloadModule(const Valdi::StringBox & path, int32_t maxDepth) = 0;

    virtual /*not-null*/ std::shared_ptr<JSRuntimeNativeObjectsManager> createNativeObjectsManager() = 0;

    virtual void destroyNativeObjectsManager(const /*not-null*/ std::shared_ptr<JSRuntimeNativeObjectsManager> & nativeObjectsManager) = 0;

    virtual /*not-null*/ std::shared_ptr<JSRuntime> createWorker() = 0;

    virtual void runOnJsThread(const Valdi::Value & runnable) = 0;
};

} // namespace snap::valdi
