// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

#pragma once

#include "valdi_core/cpp/Utils/Bytes.hpp"
#include "valdi_core/cpp/Utils/PlatformResult.hpp"
#include "valdi_core/cpp/Utils/StringBox.hpp"

namespace snap::valdi {

class Keychain {
public:
    virtual ~Keychain() = default;

    /** Store the given string blob into the keychain */
    virtual Valdi::PlatformResult store(const Valdi::StringBox & key, const Valdi::BytesView & value) = 0;

    /**
     * Retrieve the stored blob for the given key.
     * Returns empty data if the value was not found.
     */
    virtual Valdi::BytesView get(const Valdi::StringBox & key) = 0;

    /** Erase the stored blob for the given key. */
    virtual bool erase(const Valdi::StringBox & key) = 0;
};

} // namespace snap::valdi
