// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

#pragma once

#include "valdi_core/cpp/Utils/StringBox.hpp"
#include <cstdint>
#include <string>

namespace snap::valdi {

class RuntimeMessageHandler {
public:
    virtual ~RuntimeMessageHandler() = default;

    virtual void onUncaughtJsError(int32_t errorCode, const Valdi::StringBox & moduleName, const std::string & errorMessage, const std::string & stackTrace) = 0;

    virtual void onJsCrash(const Valdi::StringBox & moduleName, const std::string & errorMessage, const std::string & stackTrace, bool isANR) = 0;

    virtual void onDebugMessage(int32_t level, const std::string & message) = 0;
};

} // namespace snap::valdi
