// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

#include "valdi/NativeRuntimeMessageHandler.hpp"  // my header
#include "djinni/jni/Marshal.hpp"
#include "utils/debugging/DjinniPrologue.hpp"
#include "valdi_core/bindings/InternedStringTranslator_jni.hpp"

namespace djinni_generated_client::valdi {

NativeRuntimeMessageHandler::NativeRuntimeMessageHandler() : ::djinni::JniInterface<::snap::valdi::RuntimeMessageHandler, NativeRuntimeMessageHandler>("com/snapchat/client/valdi/RuntimeMessageHandler$CppProxy") {}

NativeRuntimeMessageHandler::~NativeRuntimeMessageHandler() = default;

NativeRuntimeMessageHandler::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeRuntimeMessageHandler::JavaProxy::~JavaProxy() = default;

void NativeRuntimeMessageHandler::JavaProxy::onUncaughtJsError(int32_t c_errorCode, const Valdi::StringBox & c_moduleName, const std::string & c_errorMessage, const std::string & c_stackTrace) {
    DJINNI_FUNCTION_PROLOGUE("RuntimeMessageHandler.onUncaughtJsError");
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated_client::valdi::NativeRuntimeMessageHandler>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onUncaughtJsError,
                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c_errorCode)),
                           ::djinni::get(ValdiAndroid::InternedStringTranslator::fromCpp(jniEnv, c_moduleName)),
                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c_errorMessage)),
                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c_stackTrace)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeRuntimeMessageHandler::JavaProxy::onJsCrash(const Valdi::StringBox & c_moduleName, const std::string & c_errorMessage, const std::string & c_stackTrace, bool c_isANR) {
    DJINNI_FUNCTION_PROLOGUE("RuntimeMessageHandler.onJsCrash");
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated_client::valdi::NativeRuntimeMessageHandler>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onJsCrash,
                           ::djinni::get(ValdiAndroid::InternedStringTranslator::fromCpp(jniEnv, c_moduleName)),
                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c_errorMessage)),
                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c_stackTrace)),
                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c_isANR)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeRuntimeMessageHandler::JavaProxy::onDebugMessage(int32_t c_level, const std::string & c_message) {
    DJINNI_FUNCTION_PROLOGUE("RuntimeMessageHandler.onDebugMessage");
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated_client::valdi::NativeRuntimeMessageHandler>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onDebugMessage,
                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c_level)),
                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c_message)));
    ::djinni::jniExceptionCheck(jniEnv);
}

CJNIEXPORT void JNICALL Java_com_snapchat_client_valdi_RuntimeMessageHandler_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("RuntimeMessageHandler.nativeDestroy");
        delete reinterpret_cast<::djinni::CppProxyHandle<::snap::valdi::RuntimeMessageHandler>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_snapchat_client_valdi_RuntimeMessageHandler_00024CppProxy_native_1onUncaughtJsError(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_errorCode, ValdiAndroid::InternedStringTranslator::JniType j_moduleName, jstring j_errorMessage, jstring j_stackTrace)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("RuntimeMessageHandler.native_onUncaughtJsError");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi::RuntimeMessageHandler>(nativeRef);
        ref->onUncaughtJsError(::djinni::I32::toCpp(jniEnv, j_errorCode),
                               ValdiAndroid::InternedStringTranslator::toCpp(jniEnv, j_moduleName),
                               ::djinni::String::toCpp(jniEnv, j_errorMessage),
                               ::djinni::String::toCpp(jniEnv, j_stackTrace));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_snapchat_client_valdi_RuntimeMessageHandler_00024CppProxy_native_1onJsCrash(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, ValdiAndroid::InternedStringTranslator::JniType j_moduleName, jstring j_errorMessage, jstring j_stackTrace, jboolean j_isANR)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("RuntimeMessageHandler.native_onJsCrash");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi::RuntimeMessageHandler>(nativeRef);
        ref->onJsCrash(ValdiAndroid::InternedStringTranslator::toCpp(jniEnv, j_moduleName),
                       ::djinni::String::toCpp(jniEnv, j_errorMessage),
                       ::djinni::String::toCpp(jniEnv, j_stackTrace),
                       ::djinni::Bool::toCpp(jniEnv, j_isANR));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_snapchat_client_valdi_RuntimeMessageHandler_00024CppProxy_native_1onDebugMessage(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_level, jstring j_message)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("RuntimeMessageHandler.native_onDebugMessage");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi::RuntimeMessageHandler>(nativeRef);
        ref->onDebugMessage(::djinni::I32::toCpp(jniEnv, j_level),
                            ::djinni::String::toCpp(jniEnv, j_message));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

} // namespace djinni_generated_client::valdi
