// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "valdi/JSRuntime.hpp"

namespace djinni_generated_client::valdi {

class NativeJSRuntime final : ::djinni::JniInterface<::snap::valdi::JSRuntime, NativeJSRuntime> {
public:
    using CppType = std::shared_ptr<::snap::valdi::JSRuntime>;
    using CppOptType = std::shared_ptr<::snap::valdi::JSRuntime>;
    using JniType = jobject;

    using Boxed = NativeJSRuntime;

    ~NativeJSRuntime();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeJSRuntime>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeJSRuntime>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeJSRuntime();
    friend ::djinni::JniClass<NativeJSRuntime>;
    friend ::djinni::JniInterface<::snap::valdi::JSRuntime, NativeJSRuntime>;

};

} // namespace djinni_generated_client::valdi
