// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "valdi/RuntimeMessageHandler.hpp"

namespace djinni_generated_client::valdi {

class NativeRuntimeMessageHandler final : ::djinni::JniInterface<::snap::valdi::RuntimeMessageHandler, NativeRuntimeMessageHandler> {
public:
    using CppType = std::shared_ptr<::snap::valdi::RuntimeMessageHandler>;
    using CppOptType = std::shared_ptr<::snap::valdi::RuntimeMessageHandler>;
    using JniType = jobject;

    using Boxed = NativeRuntimeMessageHandler;

    ~NativeRuntimeMessageHandler();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeRuntimeMessageHandler>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeRuntimeMessageHandler>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeRuntimeMessageHandler();
    friend ::djinni::JniClass<NativeRuntimeMessageHandler>;
    friend ::djinni::JniInterface<::snap::valdi::RuntimeMessageHandler, NativeRuntimeMessageHandler>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::snap::valdi::RuntimeMessageHandler
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void onUncaughtJsError(int32_t errorCode, const Valdi::StringBox & moduleName, const std::string & errorMessage, const std::string & stackTrace) override;
        void onJsCrash(const Valdi::StringBox & moduleName, const std::string & errorMessage, const std::string & stackTrace, bool isANR) override;
        void onDebugMessage(int32_t level, const std::string & message) override;

    private:
        friend ::djinni::JniInterface<::snap::valdi::RuntimeMessageHandler, ::djinni_generated_client::valdi::NativeRuntimeMessageHandler>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/snapchat/client/valdi/RuntimeMessageHandler") };
    const jmethodID method_onUncaughtJsError { ::djinni::jniGetMethodID(clazz.get(), "onUncaughtJsError", "(ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V") };
    const jmethodID method_onJsCrash { ::djinni::jniGetMethodID(clazz.get(), "onJsCrash", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V") };
    const jmethodID method_onDebugMessage { ::djinni::jniGetMethodID(clazz.get(), "onDebugMessage", "(ILjava/lang/String;)V") };
};

} // namespace djinni_generated_client::valdi
