// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "valdi/Keychain.hpp"

namespace djinni_generated_client::valdi {

class NativeKeychain final : ::djinni::JniInterface<::snap::valdi::Keychain, NativeKeychain> {
public:
    using CppType = std::shared_ptr<::snap::valdi::Keychain>;
    using CppOptType = std::shared_ptr<::snap::valdi::Keychain>;
    using JniType = jobject;

    using Boxed = NativeKeychain;

    ~NativeKeychain();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeKeychain>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeKeychain>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeKeychain();
    friend ::djinni::JniClass<NativeKeychain>;
    friend ::djinni::JniInterface<::snap::valdi::Keychain, NativeKeychain>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::snap::valdi::Keychain
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        Valdi::PlatformResult store(const Valdi::StringBox & key, const Valdi::BytesView & value) override;
        Valdi::BytesView get(const Valdi::StringBox & key) override;
        bool erase(const Valdi::StringBox & key) override;

    private:
        friend ::djinni::JniInterface<::snap::valdi::Keychain, ::djinni_generated_client::valdi::NativeKeychain>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/snapchat/client/valdi/Keychain") };
    const jmethodID method_store { ::djinni::jniGetMethodID(clazz.get(), "store", "(Ljava/lang/String;[B)Lcom/snap/valdi/utils/ValdiResult;") };
    const jmethodID method_get { ::djinni::jniGetMethodID(clazz.get(), "get", "(Ljava/lang/String;)[B") };
    const jmethodID method_erase { ::djinni::jniGetMethodID(clazz.get(), "erase", "(Ljava/lang/String;)Z") };
};

} // namespace djinni_generated_client::valdi
