// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

#include "valdi/NativeKeychain.hpp"  // my header
#include "djinni/jni/Marshal.hpp"
#include "utils/debugging/DjinniPrologue.hpp"
#include "valdi_core/bindings/BytesTranslator_jni.hpp"
#include "valdi_core/bindings/InternedStringTranslator_jni.hpp"
#include "valdi_core/bindings/ResultTranslator_jni.hpp"

namespace djinni_generated_client::valdi {

NativeKeychain::NativeKeychain() : ::djinni::JniInterface<::snap::valdi::Keychain, NativeKeychain>() {}

NativeKeychain::~NativeKeychain() = default;

NativeKeychain::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeKeychain::JavaProxy::~JavaProxy() = default;

Valdi::PlatformResult NativeKeychain::JavaProxy::store(const Valdi::StringBox & c_key, const Valdi::BytesView & c_value) {
    DJINNI_FUNCTION_PROLOGUE("Keychain.store");
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated_client::valdi::NativeKeychain>::get();
    auto jret = jniEnv->CallObjectMethod(Handle::get().get(), data.method_store,
                                         ::djinni::get(ValdiAndroid::InternedStringTranslator::fromCpp(jniEnv, c_key)),
                                         ::djinni::get(ValdiAndroid::BytesTranslator::fromCpp(jniEnv, c_value)));
    ::djinni::jniExceptionCheck(jniEnv);
    return ValdiAndroid::ResultTranslator::toCpp(jniEnv, jret);
}
Valdi::BytesView NativeKeychain::JavaProxy::get(const Valdi::StringBox & c_key) {
    DJINNI_FUNCTION_PROLOGUE("Keychain.get");
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated_client::valdi::NativeKeychain>::get();
    auto jret = jniEnv->CallObjectMethod(Handle::get().get(), data.method_get,
                                         ::djinni::get(ValdiAndroid::InternedStringTranslator::fromCpp(jniEnv, c_key)));
    ::djinni::jniExceptionCheck(jniEnv);
    return ValdiAndroid::BytesTranslator::toCpp(jniEnv, jret);
}
bool NativeKeychain::JavaProxy::erase(const Valdi::StringBox & c_key) {
    DJINNI_FUNCTION_PROLOGUE("Keychain.erase");
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated_client::valdi::NativeKeychain>::get();
    auto jret = jniEnv->CallBooleanMethod(Handle::get().get(), data.method_erase,
                                          ::djinni::get(ValdiAndroid::InternedStringTranslator::fromCpp(jniEnv, c_key)));
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni::Bool::toCpp(jniEnv, jret);
}

} // namespace djinni_generated_client::valdi
