// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

#include "valdi/NativeJSRuntimeNativeObjectsManager.hpp"  // my header
#include "utils/debugging/DjinniPrologue.hpp"
#include "valdi_core/bindings/ValueTranslator_jni.hpp"

namespace djinni_generated_client::valdi {

NativeJSRuntimeNativeObjectsManager::NativeJSRuntimeNativeObjectsManager() : ::djinni::JniInterface<::snap::valdi::JSRuntimeNativeObjectsManager, NativeJSRuntimeNativeObjectsManager>("com/snapchat/client/valdi/JSRuntimeNativeObjectsManager$CppProxy") {}

NativeJSRuntimeNativeObjectsManager::~NativeJSRuntimeNativeObjectsManager() = default;


CJNIEXPORT void JNICALL Java_com_snapchat_client_valdi_JSRuntimeNativeObjectsManager_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("JSRuntimeNativeObjectsManager.nativeDestroy");
        delete reinterpret_cast<::djinni::CppProxyHandle<::snap::valdi::JSRuntimeNativeObjectsManager>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT ValdiAndroid::ValueTranslator::JniType JNICALL Java_com_snapchat_client_valdi_JSRuntimeNativeObjectsManager_00024CppProxy_native_1getReachableObjectsDescription(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("JSRuntimeNativeObjectsManager.native_getReachableObjectsDescription");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi::JSRuntimeNativeObjectsManager>(nativeRef);
        auto r = ref->getReachableObjectsDescription();
        return ::djinni::release(ValdiAndroid::ValueTranslator::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated_client::valdi
