// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

#include "valdi/NativeJSRuntime.hpp"  // my header
#include "djinni/jni/Marshal.hpp"
#include "utils/debugging/DjinniPrologue.hpp"
#include "valdi/NativeJSRuntimeNativeObjectsManager.hpp"
#include "valdi_core/bindings/InternedStringTranslator_jni.hpp"
#include "valdi_core/bindings/ValueTranslator_jni.hpp"

namespace djinni_generated_client::valdi {

NativeJSRuntime::NativeJSRuntime() : ::djinni::JniInterface<::snap::valdi::JSRuntime, NativeJSRuntime>("com/snapchat/client/valdi/JSRuntime$CppProxy") {}

NativeJSRuntime::~NativeJSRuntime() = default;


CJNIEXPORT void JNICALL Java_com_snapchat_client_valdi_JSRuntime_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("JSRuntime.nativeDestroy");
        delete reinterpret_cast<::djinni::CppProxyHandle<::snap::valdi::JSRuntime>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jint JNICALL Java_com_snapchat_client_valdi_JSRuntime_00024CppProxy_native_1pushModuleToMarshaller(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_nativeObjectsManager, ValdiAndroid::InternedStringTranslator::JniType j_path, jlong j_marshallerHandle)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("JSRuntime.native_pushModuleToMarshaller");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi::JSRuntime>(nativeRef);
        auto r = ref->pushModuleToMarshaller(::djinni_generated_client::valdi::NativeJSRuntimeNativeObjectsManager::toCpp(jniEnv, j_nativeObjectsManager),
                                             ValdiAndroid::InternedStringTranslator::toCpp(jniEnv, j_path),
                                             ::djinni::I64::toCpp(jniEnv, j_marshallerHandle));
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_snapchat_client_valdi_JSRuntime_00024CppProxy_native_1addModuleUnloadObserver(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, ValdiAndroid::InternedStringTranslator::JniType j_path, ValdiAndroid::ValueTranslator::JniType j_observer)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("JSRuntime.native_addModuleUnloadObserver");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi::JSRuntime>(nativeRef);
        ref->addModuleUnloadObserver(ValdiAndroid::InternedStringTranslator::toCpp(jniEnv, j_path),
                                     ValdiAndroid::ValueTranslator::toCpp(jniEnv, j_observer));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_snapchat_client_valdi_JSRuntime_00024CppProxy_native_1preloadModule(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, ValdiAndroid::InternedStringTranslator::JniType j_path, jint j_maxDepth)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("JSRuntime.native_preloadModule");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi::JSRuntime>(nativeRef);
        ref->preloadModule(ValdiAndroid::InternedStringTranslator::toCpp(jniEnv, j_path),
                           ::djinni::I32::toCpp(jniEnv, j_maxDepth));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_snapchat_client_valdi_JSRuntime_00024CppProxy_native_1createNativeObjectsManager(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("JSRuntime.native_createNativeObjectsManager");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi::JSRuntime>(nativeRef);
        auto r = ref->createNativeObjectsManager();
        return ::djinni::release(::djinni_generated_client::valdi::NativeJSRuntimeNativeObjectsManager::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_snapchat_client_valdi_JSRuntime_00024CppProxy_native_1destroyNativeObjectsManager(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_nativeObjectsManager)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("JSRuntime.native_destroyNativeObjectsManager");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi::JSRuntime>(nativeRef);
        ref->destroyNativeObjectsManager(::djinni_generated_client::valdi::NativeJSRuntimeNativeObjectsManager::toCpp(jniEnv, j_nativeObjectsManager));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_snapchat_client_valdi_JSRuntime_00024CppProxy_native_1createWorker(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("JSRuntime.native_createWorker");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi::JSRuntime>(nativeRef);
        auto r = ref->createWorker();
        return ::djinni::release(::djinni_generated_client::valdi::NativeJSRuntime::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_snapchat_client_valdi_JSRuntime_00024CppProxy_native_1runOnJsThread(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, ValdiAndroid::ValueTranslator::JniType j_runnable)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("JSRuntime.native_runOnJsThread");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi::JSRuntime>(nativeRef);
        ref->runOnJsThread(ValdiAndroid::ValueTranslator::toCpp(jniEnv, j_runnable));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

} // namespace djinni_generated_client::valdi
