// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "valdi/JSRuntimeNativeObjectsManager.hpp"

namespace djinni_generated_client::valdi {

class NativeJSRuntimeNativeObjectsManager final : ::djinni::JniInterface<::snap::valdi::JSRuntimeNativeObjectsManager, NativeJSRuntimeNativeObjectsManager> {
public:
    using CppType = std::shared_ptr<::snap::valdi::JSRuntimeNativeObjectsManager>;
    using CppOptType = std::shared_ptr<::snap::valdi::JSRuntimeNativeObjectsManager>;
    using JniType = jobject;

    using Boxed = NativeJSRuntimeNativeObjectsManager;

    ~NativeJSRuntimeNativeObjectsManager();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeJSRuntimeNativeObjectsManager>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeJSRuntimeNativeObjectsManager>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeJSRuntimeNativeObjectsManager();
    friend ::djinni::JniClass<NativeJSRuntimeNativeObjectsManager>;
    friend ::djinni::JniInterface<::snap::valdi::JSRuntimeNativeObjectsManager, NativeJSRuntimeNativeObjectsManager>;

};

} // namespace djinni_generated_client::valdi
