import 'ts-jest';
import { generateIds } from './GenerateIds';

const TEST_ID_FILES = `
ids:
  my_first_id:
    description: This is my first id
  my_second_id:
`;

describe('Ids Files Geneerator', () => {
  it('can generate Android resource file', () => {
    const android = generateIds('hello_world', '"SCHelloWorld/Ids.h"', TEST_ID_FILES).android;

    expect(android).toBe(
      `
<resources>
  <item type="id" name="hello_world__my_first_id"/>
  <item type="id" name="hello_world__my_second_id"/>
</resources>
    `.trim(),
    );
  });

  it('can generate Objective-C header file', () => {
    const iosHeader = generateIds('hello_world', '"SCHelloWorld/Ids.h"', TEST_ID_FILES).ios.header;

    expect(iosHeader).toBe(
      `/**
 * Generated from ids.yaml by the Valdi compiler.
 * Please do not edit this file directly.
 */

#import <Foundation/Foundation.h>

/**
 * This is my first id
 */
extern NSString *SCValdiIdHelloWorldMyFirstId();

extern NSString *SCValdiIdHelloWorldMySecondId();
`,
    );
  });

  it('can generate Objective-C impl file', () => {
    const iosImpl = generateIds('hello_world', '"SCHelloWorld/Ids.h"', TEST_ID_FILES).ios.impl;

    expect(iosImpl).toBe(
      `/**
 * Generated from ids.yaml by the Valdi compiler.
 * Please do not edit this file directly.
 */

#import <Foundation/Foundation.h>
#import "SCHelloWorld/Ids.h"

NSString *SCValdiIdHelloWorldMyFirstId() {
    return @"hello_world/my_first_id";
}

NSString *SCValdiIdHelloWorldMySecondId() {
    return @"hello_world/my_second_id";
}
`,
    );
  });

  it('can generate TypeScript definition file', () => {
    const tsDefinition = generateIds('hello_world', '"SCHelloWorld/Ids.h"', TEST_ID_FILES).typescript.definition;

    expect(tsDefinition).toBe(
      `export class Ids {
  /**
   * This is my first id
   */
  static myFirstId(): string;

  static mySecondId(): string;
}
`,
    );
  });

  it('can generate JavaScript implementation file', () => {
    const jsImplementation = generateIds('hello_world', '"SCHelloWorld/Ids.h"', TEST_ID_FILES).typescript
      .implementation;

    expect(jsImplementation).toBe(
      `module.exports.Ids = {
  myFirstId: () => 'hello_world/my_first_id',
  mySecondId: () => 'hello_world/my_second_id',
}
`,
    );
  });
});
