import * as fs from 'fs';
import { promisify } from 'util';
import * as yaml from 'js-yaml';
import * as xml from 'xml-js';
import { OutputWriter } from './OutputWriter';
import { Identifier } from './Identifier';
import { GeneratedFileHeader } from './GeneratedFileHeader';
import { ObjectiveCWriter } from './ObjectiveCWriter';

interface ObjectiveCFile {
  header: string;
  impl: string;
}

interface TypeScriptFile {
  definition: string;
  implementation: string;
}

interface GenerateIds {
  android: string;
  ios: ObjectiveCFile;
  typescript: TypeScriptFile;
}

interface IdYaml {
  description?: string;
}

interface IdsYaml {
  ids?: { [id: string]: IdYaml };
}

interface Id {
  name: string;
  identifier: string;
  androidCompatibleIdentifier: string;
  description?: string;
}

function parseIds(moduleName: string, fileContent: string): Id[] {
  const idsYaml = yaml.load(fileContent.toString()) as IdsYaml;

  if (!idsYaml || !idsYaml.ids) {
    throw new Error(`Ids Yaml file does not have an 'ids' section`);
  }
  const unprocessedIds = idsYaml.ids;

  const ids = Object.keys(unprocessedIds).map((id) => {
    return { name: id, description: unprocessedIds[id]?.description };
  });

  ids.sort((l, r) => l.name.localeCompare(r.name));

  return ids.map((id) => {
    const identifier = new Identifier(id.name);
    return {
      name: identifier.toCamelCase(),
      identifier: `${moduleName}/${identifier.toSnakeCase()}`,
      androidCompatibleIdentifier: `${moduleName}__${identifier.toSnakeCase()}`,
      description: id.description,
    };
  });
}

function generateHeaderComment(): string {
  return GeneratedFileHeader.generateMultilineComment(
    `Generated from ids.yaml by the Valdi compiler.
Please do not edit this file directly.`,
  );
}

function generateAndroidResourceFile(ids: Id[]): string {
  const androidItems: object[] = ids.map((id) => {
    return { _attributes: { type: 'id', name: id.androidCompatibleIdentifier } };
  });

  return xml.js2xml(
    {
      resources: {
        item: androidItems,
      },
    },
    { compact: true, spaces: 2 },
  );
}

function generateIOSIds(ids: Id[], iosHeaderImportPath: string): ObjectiveCFile {
  const header = new ObjectiveCWriter();
  const impl = new ObjectiveCWriter();

  header.append(generateHeaderComment());
  impl.append(generateHeaderComment());

  header.appendImport('<Foundation/Foundation.h>');
  impl.appendImport('<Foundation/Foundation.h>');
  impl.appendImport(iosHeaderImportPath);

  let first = true;

  for (const id of ids) {
    if (!first) {
      impl.append('\n');
      header.append('\n');
    }
    first = false;

    const functionNameSuffix = new Identifier(id.identifier).toPascalCase();
    const functionName = `SCValdiId${functionNameSuffix}`;

    const functionSignature = `NSString *${functionName}()`;

    if (id.description) {
      header.append(GeneratedFileHeader.generateMultilineComment(id.description));
    }

    header.append(`extern ${functionSignature};\n`);
    impl.append(`${functionSignature} {\n`);
    impl.withIndentation('    ', () => {
      impl.append(`return @"${id.identifier}";\n`);
    });
    impl.append('}\n');
  }

  return {
    header: header.content(),
    impl: impl.content(),
  };
}

function generateTypeScriptIds(ids: Id[]): TypeScriptFile {
  const definition = new OutputWriter();
  const implementation = new OutputWriter();

  definition.append('export class Ids {\n');
  implementation.append('module.exports.Ids = {\n');

  definition.beginIndent('  ');
  implementation.beginIndent('  ');

  let first = true;
  for (const id of ids) {
    if (!first) {
      definition.append('\n');
    }
    first = false;

    if (id.description) {
      definition.append(GeneratedFileHeader.generateMultilineComment(id.description));
    }
    definition.append(`static ${id.name}(): string;\n`);

    implementation.append(`${id.name}: () => '${id.identifier}',\n`);
  }

  definition.endIndent();
  implementation.endIndent();

  implementation.append('}\n');
  definition.append('}\n');

  return {
    definition: definition.content(),
    implementation: implementation.content(),
  };
}

export function generateIds(moduleName: string, iosHeaderImportPath: string, fileContent: string): GenerateIds {
  const ids = parseIds(moduleName, fileContent);

  const androidIds = generateAndroidResourceFile(ids);
  const iosFiles = generateIOSIds(ids, iosHeaderImportPath);
  const tsFile = generateTypeScriptIds(ids);

  return {
    android: androidIds,
    ios: iosFiles,
    typescript: tsFile,
  };
}

export async function generateIdsFromPath(
  moduleName: string,
  iosHeaderImportPath: string,
  filePath: string,
): Promise<GenerateIds> {
  const fileContent = await promisify(fs.readFile)(filePath);
  return generateIds(moduleName, iosHeaderImportPath, fileContent.toString());
}
