#import "valdi_core/SCValdiMarshallable.h"
#import "valdi_core/SCValdiMarshallableObject.h"
#import "valdi_core/SCValdiMarshaller.h"
#import <Foundation/Foundation.h>

@class SCValdiINavigatorPageConfig;

/**
 * Generated from 'INavigator.ts' by the Valdi compiler.
 * Please do not edit this file directly.
 */
@interface SCValdiINavigatorPageConfig : SCValdiMarshallableObject

@property (copy, nonatomic) NSString* _Nonnull componentPath;

@property (copy, nonatomic) NSDictionary<NSString*, id>* _Nullable componentViewModel;

@property (copy, nonatomic) NSDictionary<NSString*, id>* _Nullable componentContext;

@property (copy, nonatomic) NSNumber* _Nullable showPlatformNavigationBar;

@property (copy, nonatomic) NSNumber* _Nullable wrapInPlatformNavigationController;

@property (copy, nonatomic) NSString* _Nullable platformNavigationTitle;

@property (copy, nonatomic) NSNumber* _Nullable isPartiallyHiding;

@property (copy, nonatomic) NSNumber* _Nullable disableSwipeToDismissModal;

@end
