#import "valdi_core/SCValdiINavigatorPageConfig.h"
#import "valdi_core/SCValdiINavigatorPageVisibility.h"
#import "valdi_core/SCValdiMarshallable.h"
#import "valdi_core/SCValdiMarshallableObject.h"
#import "valdi_core/SCValdiMarshaller.h"
#import <Foundation/Foundation.h>

@protocol SCValdiINavigator;

typedef void (^SCValdiINavigatorSetBackButtonObserverObserverBlock)();
typedef void (^SCValdiINavigatorSetPageVisibilityObserverObserverBlock)(double);

/**
 * Generated from 'INavigator.ts' by the Valdi compiler.
 * Please do not edit this file directly.
 */
@protocol SCValdiINavigator <NSObject, SCValdiMarshallable>

/**
 * NOTE: This method can be called from any thread.
 */
@required
- (void)pushComponentWithPage:(SCValdiINavigatorPageConfig* _Nonnull)page animated:(BOOL)animated;

/**
 * NOTE: This method can be called from any thread.
 */
@required
- (void)popWithAnimated:(BOOL)animated;

/**
 * NOTE: This method can be called from any thread.
 */
@required
- (void)popToSelfWithAnimated:(BOOL)animated;

/**
 * NOTE: This method can be called from any thread.
 */
@required
- (void)presentComponentWithPage:(SCValdiINavigatorPageConfig* _Nonnull)page animated:(BOOL)animated;

/**
 * NOTE: This method can be called from any thread.
 */
@required
- (void)dismissWithAnimated:(BOOL)animated;

/**
 * NOTE: This method can be called from any thread.
 */
@required
- (void)forceDisableDismissalGestureWithForceDisable:(BOOL)forceDisable;

/**
 * returns the unregister function
 * NOTE: This method can be called from any thread.
 */
@optional
- (void)setBackButtonObserverWithObserver:(SCValdiINavigatorSetBackButtonObserverObserverBlock _Nonnull)observer;

/**
 * NOTE: This method can be called from any thread.
 */
@optional
- (void)setPageVisibilityObserver:(SCValdiINavigatorSetPageVisibilityObserverObserverBlock _Nullable)observer;

@end

/**
 * Marshall the instance into the given SCValdiMarshaller.
 */
FOUNDATION_EXPORT NSInteger SCValdiINavigatorMarshall(SCValdiMarshallerRef _Nonnull marshaller,
                                                      id<SCValdiINavigator> _Nonnull instance);
