// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

package com.snapchat.client.valdi_core;

public abstract class Animator {
    /** The Value is a wrapped completion callback */
    public abstract void flushAnimations(java.lang.Object completion);

    /** Cancel an animation */
    public abstract void cancel();
}
