// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

package com.snapchat.client.valdi_core;

public abstract class AssetLoadObserver {
    public abstract void onLoad(Asset asset, java.lang.Object loadedAsset, java.lang.String error);
}
