// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

package com.snapchat.client.valdi_core;

import com.snapchat.djinni.NativeObjectManager;
import java.util.concurrent.atomic.AtomicBoolean;

/** Represents a loadable asset like an Image */
public abstract class Asset {
    /** Return a string that uniquely identifies this asset */
    public abstract java.lang.String getIdentifier();

    /**
     * Measure the width that should be used for this asset
     * given a max width and height.
     */
    public abstract double measureWidth(double maxWidth, double maxHeight);

    /**
     * Measure the height that should be used for this asset
     * given a max width and height.
     */
    public abstract double measureHeight(double maxWidth, double maxHeight);

    /**
     * Append a load observer, which will be notified
     * when the asset is loaded.
     */
    public abstract void addLoadObserver(AssetLoadObserver observer, AssetOutputType outputType, int preferredWidth, int preferredHeight, java.lang.Object filter);

    /** Remove a previously registered load observer */
    public abstract void removeLoadObserver(AssetLoadObserver observer);

    /** Update the preferred width and height of a previously registered load observer */
    public abstract void updateLoadObserverPreferredSize(AssetLoadObserver observer, int preferredWidth, int preferredHeight);

    public static final class CppProxy extends Asset
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);

        @Override
        public java.lang.String getIdentifier()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getIdentifier(this.nativeRef);
        }
        private native java.lang.String native_getIdentifier(long _nativeRef);

        @Override
        public double measureWidth(double maxWidth, double maxHeight)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_measureWidth(this.nativeRef, maxWidth, maxHeight);
        }
        private native double native_measureWidth(long _nativeRef, double maxWidth, double maxHeight);

        @Override
        public double measureHeight(double maxWidth, double maxHeight)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_measureHeight(this.nativeRef, maxWidth, maxHeight);
        }
        private native double native_measureHeight(long _nativeRef, double maxWidth, double maxHeight);

        @Override
        public void addLoadObserver(AssetLoadObserver observer, AssetOutputType outputType, int preferredWidth, int preferredHeight, java.lang.Object filter)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_addLoadObserver(this.nativeRef, observer, outputType, preferredWidth, preferredHeight, filter);
        }
        private native void native_addLoadObserver(long _nativeRef, AssetLoadObserver observer, AssetOutputType outputType, int preferredWidth, int preferredHeight, java.lang.Object filter);

        @Override
        public void removeLoadObserver(AssetLoadObserver observer)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_removeLoadObserver(this.nativeRef, observer);
        }
        private native void native_removeLoadObserver(long _nativeRef, AssetLoadObserver observer);

        @Override
        public void updateLoadObserverPreferredSize(AssetLoadObserver observer, int preferredWidth, int preferredHeight)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_updateLoadObserverPreferredSize(this.nativeRef, observer, preferredWidth, preferredHeight);
        }
        private native void native_updateLoadObserverPreferredSize(long _nativeRef, AssetLoadObserver observer, int preferredWidth, int preferredHeight);
    }
}
