// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

package com.snapchat.client.valdi_core;

public enum AssetOutputType {
    BYTES,
    IMAGEIOS,
    IMAGEANDROID,
    IMAGESNAPDRAWING,
    VIDEOIOS,
    VIDEOANDROID,
    LOTTIE,
    DUMMY,
    ;
}
