// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

package com.snapchat.client.valdi_core;

public final class CompositeAttributePart {


    /*package*/ final java.lang.String mAttribute;

    /*package*/ final AttributeType mType;

    /*package*/ final boolean mOptional;

    /*package*/ final boolean mInvalidateLayoutOnChange;

    public CompositeAttributePart(
            java.lang.String attribute,
            AttributeType type,
            boolean optional,
            boolean invalidateLayoutOnChange) {
        this.mAttribute = attribute;
        this.mType = type;
        this.mOptional = optional;
        this.mInvalidateLayoutOnChange = invalidateLayoutOnChange;
    }

    public java.lang.String getAttribute() {
        return mAttribute;
    }

    public AttributeType getType() {
        return mType;
    }

    public boolean getOptional() {
        return mOptional;
    }

    public boolean getInvalidateLayoutOnChange() {
        return mInvalidateLayoutOnChange;
    }

    @Override
    public String toString() {
        return "CompositeAttributePart{" +
                "mAttribute=" + mAttribute +
                "," + "mType=" + mType +
                "," + "mOptional=" + mOptional +
                "," + "mInvalidateLayoutOnChange=" + mInvalidateLayoutOnChange +
        "}";
    }

}
