// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

package com.snapchat.client.valdi_core;

public abstract class HTTPRequestManager {
    public abstract Cancelable performRequest(HTTPRequest request, HTTPRequestManagerCompletion completion);
}
