// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

package com.snapchat.client.valdi_core;

public final class HTTPRequest {


    /*package*/ final java.lang.String mUrl;

    /*package*/ final java.lang.String mMethod;

    /*package*/ final java.lang.Object mHeaders;

    /*package*/ final byte[] mBody;

    /*package*/ final int mPriority;

    public HTTPRequest(
            java.lang.String url,
            java.lang.String method,
            java.lang.Object headers,
            byte[] body,
            int priority) {
        this.mUrl = url;
        this.mMethod = method;
        this.mHeaders = headers;
        this.mBody = body;
        this.mPriority = priority;
    }

    public java.lang.String getUrl() {
        return mUrl;
    }

    public java.lang.String getMethod() {
        return mMethod;
    }

    public java.lang.Object getHeaders() {
        return mHeaders;
    }

    public byte[] getBody() {
        return mBody;
    }

    /** Between 0 being lowest, to 10 being maximum */
    public int getPriority() {
        return mPriority;
    }

    @Override
    public String toString() {
        return "HTTPRequest{" +
                "mUrl=" + mUrl +
                "," + "mMethod=" + mMethod +
                "," + "mHeaders=" + mHeaders +
                "," + "mBody=" + mBody +
                "," + "mPriority=" + mPriority +
        "}";
    }

}
