// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

package com.snapchat.client.valdi_core;

import com.snapchat.djinni.NativeObjectManager;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class HTTPRequestManagerCompletion {
    public abstract void onComplete(HTTPResponse response);

    public abstract void onFail(String error);

    public static final class CppProxy extends HTTPRequestManagerCompletion
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);

        @Override
        public void onComplete(HTTPResponse response)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onComplete(this.nativeRef, response);
        }
        private native void native_onComplete(long _nativeRef, HTTPResponse response);

        @Override
        public void onFail(String error)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onFail(this.nativeRef, error);
        }
        private native void native_onFail(long _nativeRef, String error);
    }
}
