// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

package com.snapchat.client.valdi_core;

public final class HTTPResponse {


    /*package*/ final int mStatusCode;

    /*package*/ final java.lang.Object mHeaders;

    /*package*/ final byte[] mBody;

    public HTTPResponse(
            int statusCode,
            java.lang.Object headers,
            byte[] body) {
        this.mStatusCode = statusCode;
        this.mHeaders = headers;
        this.mBody = body;
    }

    public int getStatusCode() {
        return mStatusCode;
    }

    public java.lang.Object getHeaders() {
        return mHeaders;
    }

    public byte[] getBody() {
        return mBody;
    }

    @Override
    public String toString() {
        return "HTTPResponse{" +
                "mStatusCode=" + mStatusCode +
                "," + "mHeaders=" + mHeaders +
                "," + "mBody=" + mBody +
        "}";
    }

}
