// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

package com.snapchat.client.valdi_core;

import com.snapchat.djinni.NativeObjectManager;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class ModuleFactory {
    /**
     * Return the path of the module, which represents its path
     * when imported from TypeScript.
     */
    public abstract java.lang.String getModulePath();

    /**
     * Returns the module exports object that should be returned to
     * TypeScript when the module is imported.
     */
    public abstract java.lang.Object loadModule();

    public static final class CppProxy extends ModuleFactory
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);

        @Override
        public java.lang.String getModulePath()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getModulePath(this.nativeRef);
        }
        private native java.lang.String native_getModulePath(long _nativeRef);

        @Override
        public java.lang.Object loadModule()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_loadModule(this.nativeRef);
        }
        private native java.lang.Object native_loadModule(long _nativeRef);
    }
}
