// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

package com.snapchat.client.valdi_core;

import com.snapchat.djinni.NativeObjectManager;
import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * The ModuleFactoriesProvider will be invoked when the RuntimeManager is initialized
 * to provide additional built-in Modules that will be exposed to the JS runtime environment.
 */
public abstract class ModuleFactoriesProvider {
    /** Create and return the module factories that will be exposed to the JS runtime environment. */
    public abstract ArrayList<ModuleFactory> createModuleFactories(java.lang.Object runtimeManager);

    public static final class CppProxy extends ModuleFactoriesProvider
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);

        @Override
        public ArrayList<ModuleFactory> createModuleFactories(java.lang.Object runtimeManager)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_createModuleFactories(this.nativeRef, runtimeManager);
        }
        private native ArrayList<ModuleFactory> native_createModuleFactories(long _nativeRef, java.lang.Object runtimeManager);
    }
}
