import 'ts-jest';
import {
  generateAndroidStringsXMLFromStringsJSON,
  generateIOSLocalizableStringsFromStringsJSON,
  LocalizationServiceDirectiveParsingMode,
  parseStringsJSON,
} from './GenerateStringsFiles';

describe('Strings JSON File Generator', () => {
  describe('translation with different placeholder order', () => {
    const moduleName = 'empty_module';
    const baseEnglishJSONString = `
{
  "some_key": {
    "defaultMessage": "Sent {sentCount} out of {totalCount} total items"
  }
}
`;

    const inputJSONString = `
{
  "some_key": {
    "defaultMessage": "Из {totalCount} штук уже отправлено {sentCount}"
  }
}
`;
    const baseEnglishJSON = parseStringsJSON(
      moduleName,
      baseEnglishJSONString,
      LocalizationServiceDirectiveParsingMode.Ignore,
    );
    const inputJSON = parseStringsJSON(moduleName, inputJSONString, LocalizationServiceDirectiveParsingMode.Ignore);
    it('should work for iOS', () => {
      const english = generateIOSLocalizableStringsFromStringsJSON(moduleName, undefined, baseEnglishJSON, 'en');
      const russian = generateIOSLocalizableStringsFromStringsJSON(moduleName, baseEnglishJSON, inputJSON, 'ru');
      expect(english).toMatchInlineSnapshot(`
        "
        // BEGIN VALDI AUTOGENERATED see https://github.com/Snapchat/Valdi/blob/main/docs/docs/advanced-localization.md
        \"some_key\" = \"Sent $0 out of $1 total items\";
        "
      `);
      expect(russian).toMatchInlineSnapshot(`
        "
        // BEGIN VALDI AUTOGENERATED see https://github.com/Snapchat/Valdi/blob/main/docs/docs/advanced-localization.md
        \"some_key\" = \"Из $1 штук уже отправлено $0\";
        "
      `);
    });

    it('should work for Android', async () => {
      const english = await generateAndroidStringsXMLFromStringsJSON(moduleName, undefined, baseEnglishJSON, 'en');
      const russian = await generateAndroidStringsXMLFromStringsJSON(moduleName, baseEnglishJSON, inputJSON, 'ru');
      expect(english).toMatchInlineSnapshot(`
        "<?xml version="1.0" encoding="UTF-8"?><resources>
            <!-- VALDI GENERATED STRINGS, see https://github.com/Snapchat/Valdi/blob/main/docs/docs/advanced-localization.md -->
            <string name="empty_module_some_key">Sent $0 out of $1 total items</string>
        </resources>
        "
      `);
      expect(russian).toMatchInlineSnapshot(`
        "<?xml version="1.0" encoding="UTF-8"?><resources>
            <!-- VALDI GENERATED STRINGS, see https://github.com/Snapchat/Valdi/blob/main/docs/docs/advanced-localization.md -->
            <string name="empty_module_some_key">Из $1 штук уже отправлено $0</string>
        </resources>
        "
      `);
    });
  });

  describe('silly private_profile strings.json with xml entities', () => {
    const moduleName = 'private_profile';
    const baseEnglishJSONString = `
{
    "friendBirthdayPillDialogSubBodyTimeDiffFuture": {
      "defaultMessage": "That's only <b>{numberOfDays} days</b> away!"
    },
    "friendmojiPillDialogBFF": {
      "defaultMessage": "You and {friendFirstName} have been each other’s #1 Best Friend\\nfor <b>2 weeks in a row</b>!"
    },
    "friendmojiPillDialogSuperBFF": {
      "defaultMessage": "You and {friendFirstName} have been each other’s #1 Best Friend\\nfor <b>2 months in a row</b>!"
    }
}
`;

    const inputJSONString = `
{
  "friendBirthdayPillDialogSubBodyTimeDiffFuture": {
    "defaultMessage": "¡Solo faltan \u003cb\u003e{numberOfDays}\u0026nbsp;días\u003c/b\u003e!"
  },
  "friendmojiPillDialogBFF": {
    "defaultMessage": "Tu e {friendFirstName} são o Melhor Amigo N.\u0026ordm; 1 um do outro\\nhá \u003cb\u003e2 semanas seguidas\u003c/b\u003e!"
  },
  "friendmojiPillDialogSuperBFF": {
    "defaultMessage": "Vos y {friendFirstName} fueron mejores amigos n.\u0026deg;\u0026nbsp;1\\ndurante \u003cb\u003edos meses seguidos\u003c/b\u003e."
  }
}
`;
    const baseEnglishJSON = parseStringsJSON(
      moduleName,
      baseEnglishJSONString,
      LocalizationServiceDirectiveParsingMode.Ignore,
    );
    const inputJSON = parseStringsJSON(moduleName, inputJSONString, LocalizationServiceDirectiveParsingMode.Ignore);
    it('should work for iOS', () => {
      const esAR = generateIOSLocalizableStringsFromStringsJSON(moduleName, baseEnglishJSON, inputJSON, 'es-AR');
      expect(esAR).toMatchInlineSnapshot(`
        "
        // BEGIN VALDI AUTOGENERATED see https://github.com/Snapchat/Valdi/blob/main/docs/docs/advanced-localization.md
        \"friendBirthdayPillDialogSubBodyTimeDiffFuture\" = \"¡Solo faltan <b>$0 días</b>!\";
        \"friendmojiPillDialogBFF\" = \"Tu e $0 são o Melhor Amigo N.º 1 um do outro
        há <b>2 semanas seguidas</b>!\";
        \"friendmojiPillDialogSuperBFF\" = \"Vos y $0 fueron mejores amigos n.° 1
        durante <b>dos meses seguidos</b>.\";
        "
      `);
    });

    it('should work for Android', async () => {
      const esAR = await generateAndroidStringsXMLFromStringsJSON(moduleName, baseEnglishJSON, inputJSON, 'es-AR');
      expect(esAR).toMatchInlineSnapshot(`
        "<?xml version="1.0" encoding="UTF-8"?><resources>
            <!-- VALDI GENERATED STRINGS, see https://github.com/Snapchat/Valdi/blob/main/docs/docs/advanced-localization.md -->
            <string name="private_profile_friendBirthdayPillDialogSubBodyTimeDiffFuture">¡Solo faltan &lt;b&gt;$0 días&lt;/b&gt;!</string>
            <string name="private_profile_friendmojiPillDialogBFF">Tu e $0 são o Melhor Amigo N.º 1 um do outro
        há &lt;b&gt;2 semanas seguidas&lt;/b&gt;!</string>
            <string name="private_profile_friendmojiPillDialogSuperBFF">Vos y $0 fueron mejores amigos n.° 1
        durante &lt;b&gt;dos meses seguidos&lt;/b&gt;.</string>
        </resources>
        "
      `);
    });
  });

  describe('empty strings.json', () => {
    const moduleName = 'empty_module';
    const emptyStringsJSON = parseStringsJSON(moduleName, '{}', LocalizationServiceDirectiveParsingMode.Ignore);
    it('should not output any iOS strings', () => {
      const ios = generateIOSLocalizableStringsFromStringsJSON(moduleName, undefined, emptyStringsJSON, 'en');
      expect(ios).toBe(
        '\n// BEGIN VALDI AUTOGENERATED see https://github.com/Snapchat/Valdi/blob/main/docs/docs/advanced-localization.md\n\n',
      );
    });

    it('should not output any Android strings', async () => {
      const android = await generateAndroidStringsXMLFromStringsJSON(moduleName, undefined, emptyStringsJSON, 'en');
      expect(android).toBe(
        `<?xml version="1.0" encoding="UTF-8"?><resources>
    <!-- VALDI GENERATED STRINGS, see https://github.com/Snapchat/Valdi/blob/main/docs/docs/advanced-localization.md -->

</resources>
`,
      );
    });
  });

  describe('strings.json with duplicate ios_key values', () => {
    // We want to kill the ability to specify custom ios_key values,
    // but since we currently support it we should guard against misuse
    const moduleName = 'test_module';
    const stringsJSONWithDupeIOSKeys = `{
      "first": {
        "defaultMessage": "Good morning",
        "iosKey": "some_ios_key"
      },
      "second": {
        "defaultMessage": "Another good morning",
        "iosKey": "some_ios_key"
      }
    }`;

    it('should be ignored on iOS', () => {
      const parsedStringsJSON = parseStringsJSON(
        moduleName,
        stringsJSONWithDupeIOSKeys,
        LocalizationServiceDirectiveParsingMode.Ignore,
      );

      const result = generateIOSLocalizableStringsFromStringsJSON(moduleName, undefined, parsedStringsJSON, 'en');
      expect(result).toMatchInlineSnapshot(`
        "
        // BEGIN VALDI AUTOGENERATED see https://github.com/Snapchat/Valdi/blob/main/docs/docs/advanced-localization.md
        \"first\" = \"Good morning\";
        \"second\" = \"Another good morning\";
        "
      `);
    });

    it('should not fail for Android', async () => {
      const parsedStringsJSON = parseStringsJSON(
        moduleName,
        stringsJSONWithDupeIOSKeys,
        LocalizationServiceDirectiveParsingMode.Ignore,
      );

      const result = await generateAndroidStringsXMLFromStringsJSON(
        moduleName,
        undefined,
        parsedStringsJSON,

        'en',
      );
      expect(result).toMatchInlineSnapshot(`
        "<?xml version="1.0" encoding="UTF-8"?><resources>
            <!-- VALDI GENERATED STRINGS, see https://github.com/Snapchat/Valdi/blob/main/docs/docs/advanced-localization.md -->
            <string name="test_module_first">Good morning</string>
            <string name="test_module_second">Another good morning</string>
        </resources>
        "
      `);
    });
  });

  describe('strings.json with whitespace', () => {
    const moduleName = 'test_module';
    const stringsJSONWithWhiteSpace = `{
      "first_key": {
        "defaultMessage": "   FIRST!!!!"
      },
      "second_key": {
        "defaultMessage": "SECOND!!!!   "
      },
      "third_key": {
        "defaultMessage": "third\\n"
      },
      "fourth": {
        "defaultMessage": "fourth \\t"
      }
    }`;

    it('should succeed for iOS', () => {
      const parsedStringsJSON = parseStringsJSON(
        moduleName,
        stringsJSONWithWhiteSpace,
        LocalizationServiceDirectiveParsingMode.Ignore,
      );

      const result = generateIOSLocalizableStringsFromStringsJSON(moduleName, undefined, parsedStringsJSON, 'en');
      expect(result).toMatchInlineSnapshot(`
        "
        // BEGIN VALDI AUTOGENERATED see https://github.com/Snapchat/Valdi/blob/main/docs/docs/advanced-localization.md
        \"first_key\" = \"   FIRST!!!!\";
        \"fourth\" = \"fourth 	\";
        \"second_key\" = \"SECOND!!!!   \";
        \"third_key\" = \"third
        \";
        "
      `);
    });

    it('should work for Android', async () => {
      const parsedStringsJSON = parseStringsJSON(
        moduleName,
        stringsJSONWithWhiteSpace,
        LocalizationServiceDirectiveParsingMode.Ignore,
      );

      const result = await generateAndroidStringsXMLFromStringsJSON(moduleName, undefined, parsedStringsJSON, 'en');
      expect(result).toMatchInlineSnapshot(`
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?><resources>
            <!-- VALDI GENERATED STRINGS, see https://github.com/Snapchat/Valdi/blob/main/docs/docs/advanced-localization.md -->
            <string name=\"test_module_first_key\">   FIRST!!!!</string>
            <string name=\"test_module_fourth\">fourth 	</string>
            <string name=\"test_module_second_key\">SECOND!!!!   </string>
            <string name=\"test_module_third_key\">third
        </string>
        </resources>
        "
      `);
    });
  });

  describe('strings.json with duplicate keys', () => {
    // We use JSON.parse, which doesn't let us validate against duplicate keys.
    // What ends up happening is the later instance wins.
    //
    // Ideally, we'd introdue a JSON string validation stage, but I don't want
    // to pay the cost of yet another npm dependency just yet... But adding a test to capture
    // the current behaviour and detect any changes in it in the future.
    const moduleName = 'test_module';
    const stringsJSONWithDupeKeys = `{
      "first_key": {
        "defaultMessage": "FIRST!!!!"
      },
      "second_key": {
        "defaultMessage": "SECOND!!!!"
      },
      "first_key": {
        "defaultMessage": "another first"
      }
    }`;

    it('should succeed for iOS', () => {
      const parsedStringsJSON = parseStringsJSON(
        moduleName,
        stringsJSONWithDupeKeys,
        LocalizationServiceDirectiveParsingMode.Ignore,
      );

      const result = generateIOSLocalizableStringsFromStringsJSON(moduleName, undefined, parsedStringsJSON, 'en');
      expect(result).toMatchInlineSnapshot(`
        "
        // BEGIN VALDI AUTOGENERATED see https://github.com/Snapchat/Valdi/blob/main/docs/docs/advanced-localization.md
        \"first_key\" = \"another first\";
        \"second_key\" = \"SECOND!!!!\";
        "
      `);
    });

    it('should fail for Android', async () => {
      const parsedStringsJSON = parseStringsJSON(
        moduleName,
        stringsJSONWithDupeKeys,
        LocalizationServiceDirectiveParsingMode.Ignore,
      );

      const result = await generateAndroidStringsXMLFromStringsJSON(moduleName, undefined, parsedStringsJSON, 'en');
      expect(result).toMatchInlineSnapshot(`
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?><resources>
            <!-- VALDI GENERATED STRINGS, see https://github.com/Snapchat/Valdi/blob/main/docs/docs/advanced-localization.md -->
            <string name=\"test_module_first_key\">another first</string>
            <string name=\"test_module_second_key\">SECOND!!!!</string>
        </resources>
        "
      `);
    });
  });
});
