package com.snap.valdi.modules.drawing

import com.snap.valdi.schema.ValdiClassConstructor
import com.snap.valdi.schema.ValdiField
import com.snap.valdi.schema.ValdiInterface
import com.snap.valdi.utils.ValdiMarshallable
import com.snap.valdi.utils.ValdiMarshallableObject
import com.snap.valdi.utils.ValdiMarshaller

/**
 * Generated from type 'DrawingModule' at 'valdi_example/Drawing.d.ts' by the Valdi compiler.
 * Please do not edit this file directly.
 */
@ValdiInterface(
    schema = "'getFont':f|m|(r:'[0]'): r:'[1]','isFontRegistered':f|m|(s): b,'registerFont':f|m|(s, r:'[2]', r:'[3]', s)",
    typeReferences = [FontSpecs::class, Font::class, FontWeight::class, FontStyle::class],
    propertyReplacements = "",
    proxyClass = DrawingModule_Proxy::class
)
interface DrawingModule: ValdiMarshallable {

    fun getFont(specs: FontSpecs): Font

    fun isFontRegistered(fontName: String): Boolean

    fun registerFont(fontName: String, weight: FontWeight, style: FontStyle, filename: String): Unit

    override fun pushToMarshaller(marshaller: ValdiMarshaller) = ValdiMarshallableObject.marshall(DrawingModule::class.java, marshaller, this)

}

class DrawingModule_Proxy: DrawingModule {

    private var _getFont: (specs: FontSpecs) -> Font

    private var _isFontRegistered: (fontName: String) -> Boolean

    private var _registerFont: (fontName: String, weight: FontWeight, style: FontStyle, filename: String) -> Unit

    @ValdiField
    override fun getFont(specs: FontSpecs): Font {
        return _getFont(specs)
    }

    @ValdiField
    override fun isFontRegistered(fontName: String): Boolean {
        return _isFontRegistered(fontName)
    }

    @ValdiField
    override fun registerFont(fontName: String, weight: FontWeight, style: FontStyle, filename: String): Unit {
        return _registerFont(fontName, weight, style, filename)
    }

    @ValdiClassConstructor
    constructor(getFont: (specs: FontSpecs) -> Font, isFontRegistered: (fontName: String) -> Boolean, registerFont: (fontName: String, weight: FontWeight, style: FontStyle, filename: String) -> Unit) {
        _getFont = getFont
        _isFontRegistered = isFontRegistered
        _registerFont = registerFont
    }

}
