package com.snap.valdi.modules.drawing

import com.snap.valdi.schema.ValdiClass
import com.snap.valdi.schema.ValdiClassConstructor
import com.snap.valdi.schema.ValdiField
import com.snap.valdi.utils.ValdiMarshallableObject

/**
 * Generated from type 'FontSpecs' at 'Drawing.d.ts' by the Valdi compiler.
 * Please do not edit this file directly.
 */
@ValdiClass(
        schema = "'font':s,'lineHeight':d@?",
)
class FontSpecs: ValdiMarshallableObject {

    var font: String
        get() = _font
        set(value) { _font = value }

    var lineHeight: Double?
        get() = _lineHeight
        set(value) { _lineHeight = value }

    @ValdiField
    private var _font: String

    @ValdiField
    private var _lineHeight: Double?

    @ValdiClassConstructor
    constructor(font: String, lineHeight: Double?) {
        _font = font
        _lineHeight = lineHeight
    }

    constructor(font: String) {
        _font = font
        _lineHeight = null
    }
}
