package com.snap.valdi.modules.drawing

import com.snap.valdi.schema.ValdiEnum
import com.snap.valdi.schema.ValdiEnumType
import com.snap.valdi.schema.ValdiField
import com.snap.valdi.utils.ValdiEnumUtils

/**
* Generated from type 'FontWeight' at 'valdi_example/Drawing.d.ts' by the Valdi compiler.
* Please do not edit this file directly.
*/
@ValdiEnum(
schema = "'LIGHT':'light','NORMAL':'normal','MEDIUM':'medium','DEMI_BOLD':'demi-bold','BOLD':'bold','BLACK':'black'",
propertyReplacements = "",
type = ValdiEnumType.STRING
)
enum class FontWeight {
    @ValdiField
    LIGHT,
    @ValdiField
    NORMAL,
    @ValdiField
    MEDIUM,
    @ValdiField
    DEMI_BOLD,
    @ValdiField
    BOLD,
    @ValdiField
    BLACK;

    val value: String
    get() = ValdiEnumUtils.getEnumStringValue(this)

}

