package com.snap.valdi.modules.drawing

import com.snap.valdi.schema.ValdiClassConstructor
import com.snap.valdi.schema.ValdiField
import com.snap.valdi.schema.ValdiInterface
import com.snap.valdi.schema.ValdiMethod
import com.snap.valdi.utils.ValdiMarshallable
import com.snap.valdi.utils.ValdiMarshallableObject
import com.snap.valdi.utils.ValdiMarshaller

/**
 * Generated from type 'Font' at 'Drawing.d.ts' by the Valdi compiler.
 * Please do not edit this file directly.
 */
@ValdiInterface(
        schema = "'measureText':f*(s, d@?, d@?, d@?): r:'[0]'",
        proxyClass = Font_Proxy::class,
        typeReferences = [Size::class],
)
interface Font: ValdiMarshallable {

    fun measureText(text: String, maxWidth: Double?, maxHeight: Double?, maxLines: Double?): Size

    override fun pushToMarshaller(marshaller: ValdiMarshaller) = ValdiMarshallableObject.marshall(Font::class.java, marshaller, this)

}

class Font_Proxy: Font {

    private var _measureText: (text: String, maxWidth: Double?, maxHeight: Double?, maxLines: Double?) -> Size

    @ValdiField
    override fun measureText(text: String, maxWidth: Double?, maxHeight: Double?, maxLines: Double?): Size {
        return _measureText(text, maxWidth, maxHeight, maxLines)
    }

    @ValdiClassConstructor
    constructor(measureText: (text: String, maxWidth: Double?, maxHeight: Double?, maxLines: Double?) -> Size) {
        _measureText = measureText
    }
}
