package com.snap.valdi.modules.drawing

import com.snap.valdi.schema.ValdiEnum
import com.snap.valdi.schema.ValdiEnumType
import com.snap.valdi.schema.ValdiField
import com.snap.valdi.utils.ValdiEnumUtils

/**
* Generated from type 'FontStyle' at 'valdi_example/Drawing.d.ts' by the Valdi compiler.
* Please do not edit this file directly.
*/
@ValdiEnum(
schema = "'NORMAL':'normal','ITALIC':'italic'",
propertyReplacements = "",
type = ValdiEnumType.STRING
)
enum class FontStyle {
    @ValdiField
    NORMAL,
    @ValdiField
    ITALIC;

    val value: String
    get() = ValdiEnumUtils.getEnumStringValue(this)

}

