package com.snap.valdi.modules.drawing

import com.snap.valdi.schema.ValdiClass
import com.snap.valdi.schema.ValdiClassConstructor
import com.snap.valdi.schema.ValdiField
import com.snap.valdi.utils.ValdiMarshallableObject

/**
 * Generated from type 'Size' at 'Drawing.d.ts' by the Valdi compiler.
 * Please do not edit this file directly.
 */
@ValdiClass(
        schema = "'width':d,'height':d"
)
class Size: ValdiMarshallableObject {

    var width: Double
        get() = _width
        set(value) { _width = value }

    var height: Double
        get() = _height
        set(value) { _height = value }

    @ValdiField
    private var _width: Double

    @ValdiField
    private var _height: Double

    @ValdiClassConstructor
    constructor(width: Double, height: Double) {
        _width = width
        _height = height
    }
}
