load(":valdi_compiled.bzl", "ValdiModuleInfo")
load(":valdi_extract_output_rule_helper.bzl", "extract_valdi_output_rule")

def _extract_swift_srcs_impl(ctx):
    module = ctx.attr.compiled_module[ValdiModuleInfo]
    module_name = module.name
    selected_source_set = ctx.attr.selected_source_set
    swift_srcs = []

    if selected_source_set == "debug":
        swift_srcs.extend([
            module.ios_debug_generated_srcs,
            module.ios_debug_api_generated_srcs,
        ])
    else:
        swift_srcs.extend([
            module.ios_release_generated_srcs,
            module.ios_release_api_generated_srcs,
        ])

    if not swift_srcs:
        return [DefaultInfo(files = depset([]))]

    merged_swift_src = _merge_swift_srcs(
        ctx,
        module_name,
        selected_source_set,
        swift_srcs,
    )

    return [
        DefaultInfo(files = depset([
            merged_swift_src,
        ])),
    ]

def _swift_concat_command(output):
    """ Generate a shell script to concatenate all .swift files in a directory.
    """
    command = """
text="//THIS IS AN AUTOGENERATED FILE. DO NOT EDIT\n\n"
destination_filename=$(basename "{output_file}")

for source_dir in "$@"; do
    for swift in `find $source_dir ! -name "$destination_filename" -name "*.swift"`; do
        text="$text\n// ----------------------------";
        text="$text\n//";
        text="$text\n// $(basename "$swift")";
        text="$text\n//";
        text="$text\n// ----------------------------\n\n";
        text="$text$(cat "${{swift}}";)\n\n";
    done;
done;
echo -e "$text" > "{output_file}"
""".format(
        output_file = output.path,
    )

    return command

def _merge_swift_srcs(ctx, module_name, selected_source_set, swift_srcs):
    output = ctx.actions.declare_file("{}_{}_concat.swift".format(module_name, selected_source_set))

    # Pass them as arguments to the generated shell command
    args = ctx.actions.args()
    for swift_src in swift_srcs:
        args.add(swift_src.path)  # Add each directory as an argument
    ctx.actions.run_shell(
        command = _swift_concat_command(output),
        arguments = [args],
        inputs = swift_srcs,
        outputs = [output],
        mnemonic = "SwiftConcatGen",
        progress_message = "Concatenating Swift files for module {}".format(module_name),
    )
    return output

extract_swift_srcs = extract_valdi_output_rule(
    implementation = _extract_swift_srcs_impl,
    attrs = {
        "selected_source_set": attr.string(
            mandatory = True,
        ),
    },
)
