import { StringMap } from 'coreutils/src/StringMap';
import { ElementFrame } from 'valdi_tsx/src/Geometry';
import { IRenderedVirtualNode } from './IRenderedVirtualNode';
import { getNodeTag } from './utils/RenderedVirtualNodeUtils';
import { debugStringify } from './utils/StringUtils';

export interface IRenderedElementData {
  readonly id: number;
  readonly frame: ElementFrame;
  readonly attributes?: StringMap<string>;
}

export interface IRenderedComponentData {}

export interface IRenderedVirtualNodeData {
  /**
   * The key, which was either automatically generated by
   * the renderer or manually provided.
   */
  readonly key: string;

  readonly tag: string;

  readonly element: IRenderedElementData | undefined;
  readonly component: IRenderedComponentData | undefined;
  readonly children: IRenderedVirtualNodeData[] | undefined;
}

export function getPathToNode(parent: IRenderedVirtualNodeData, child: IRenderedVirtualNodeData): number[] | undefined {
  if (parent === child) {
    return [];
  }

  if (parent.children) {
    let index = 0;
    for (const childOfParent of parent.children) {
      if (childOfParent === child) {
        return [index];
      }

      const path = getPathToNode(childOfParent, child);
      if (path) {
        path.unshift(index);
        return path;
      }

      index++;
    }
  }

  return undefined;
}

export function fromRenderedVirtualNode(
  node: IRenderedVirtualNode,
  includeAttributes: boolean,
  onCreate?: (node: IRenderedVirtualNode, data: IRenderedVirtualNodeData) => void,
): IRenderedVirtualNodeData {
  let children: IRenderedVirtualNodeData[] | undefined;

  if (node.children.length) {
    children = [];
    for (const child of node.children) {
      children.push(fromRenderedVirtualNode(child, includeAttributes, onCreate));
    }
  }

  let element: IRenderedElementData | undefined;
  let component: IRenderedComponentData | undefined;

  if (node.element) {
    const renderedElement = node.element;
    let attributes: StringMap<string> | undefined;

    if (includeAttributes) {
      attributes = {};
      for (const attributeName of renderedElement.getAttributeNames()) {
        const attributeValue = renderedElement.getAttribute(attributeName);
        attributes[attributeName] = debugStringify(attributeValue, 3, true);
      }
    }

    element = {
      id: renderedElement.id,
      frame: renderedElement.frame,
      attributes,
    };
  }

  if (node.component) {
    component = {};
  }

  const tag = getNodeTag(node);

  const data = {
    key: node.key,
    tag,
    element,
    component,
    children,
  };

  if (onCreate) {
    onCreate(node, data);
  }

  return data;
}

export interface RenderedVirtualNodeDataFromRoot {
  root: IRenderedVirtualNodeData;
  child: IRenderedVirtualNodeData;
}

export function getVirtualNodeDataFromRootToChild(child: IRenderedVirtualNode): RenderedVirtualNodeDataFromRoot {
  let childData: IRenderedVirtualNodeData | undefined;

  let root = child;
  while (root.parent) {
    root = root.parent;
  }

  const rootData = fromRenderedVirtualNode(root, false, (node, data) => {
    if (node === child) {
      childData = data;
    }
  });

  return {
    root: rootData,
    child: childData!,
  };
}
