import { IComponent } from './IComponent';
import { IRenderedElement } from './IRenderedElement';
import { IRenderer } from './IRenderer';

/**
 * IRenderedVirtualNode represents a node with the rendered virtual tree.
 * Every TSX tag will emit a virtual node, which will be either a Component or an Element.
 */
export interface IRenderedVirtualNode {
  /**
   * The key, which was either automatically generated by
   * the renderer or manually provided.
   */
  readonly key: string;

  /**
   * A unique string representation of the node within the render tree
   */
  readonly uniqueId: string;

  readonly parent: IRenderedVirtualNode | undefined;
  readonly element: IRenderedElement | undefined;
  readonly component: IComponent | undefined;
  readonly children: IRenderedVirtualNode[];
  readonly parentIndex: number;

  readonly renderer: IRenderer;
}
