import { ElementFrame } from 'valdi_tsx/src/Geometry';
import { IRenderedElementBase } from 'valdi_tsx/src/IRenderedElementBase';
import { NativeNode } from 'valdi_tsx/src/NativeNode';
import { NativeView } from 'valdi_tsx/src/NativeView';
import { IComponent } from './IComponent';
import { IRenderedVirtualNode } from './IRenderedVirtualNode';
import { IRenderer } from './IRenderer';
import { PropertyList } from './utils/PropertyList';

export type ElementId = number;

export type StringKeyOf<T> = Extract<keyof T, string>;

export type AttributesFrom<T> = { [K in StringKeyOf<T>]?: T[K] };

/**
 * IRenderedElement represents an element (a view, label, layout) that has been rendered.
 * Elements are used to layout and display the user interface. The IRenderedElement API
 * allows to inspect and modify the elements tree at runtime. Elements are NOT Components,
 * Components are building blocks that manages and create elements.
 */
export interface IRenderedElement<T = any> extends IRenderedElementBase<T> {
  /**
   * The generated id for this element.
   * The id is unique within a renderer context.
   */
  readonly id: ElementId;

  /**
   * The key, which was either automatically generated by
   * the renderer or manually provided.
   */
  readonly key: string;

  /**
   * The XML node tag, like 'view', 'layout' etc...
   */
  readonly tag: string;

  /**
   * The native view class name
   */
  readonly viewClass: string;

  /**
   * All the children elements emitted from this node.
   */
  readonly children: IRenderedElement[];

  /**
   * The parent node containing the current node
   */
  readonly parent: IRenderedElement | undefined;

  /**
   * The current node position within its siblings
   */
  readonly parentIndex: number;

  /**
   * The renderer responsible for rendering the element
   */
  readonly renderer: IRenderer;

  /**
   * The component which was responsible for rendering this element.
   */
  readonly emittingComponent: IComponent | undefined;

  /**
   * Get the calculated frame for this element.
   */
  readonly frame: ElementFrame;

  getAttribute<K extends keyof AttributesFrom<T>>(name: K): AttributesFrom<T>[K];
  setAttribute<K extends keyof AttributesFrom<T>>(name: K, value: AttributesFrom<T>[K]): boolean;
  setAttributes(attributes: PropertyList): boolean;
  setAttributes(attributes: AttributesFrom<T>): boolean;

  /**
   * Returns a VirtualNode representation of this node.
   */
  getVirtualNode(): IRenderedVirtualNode;

  /**
   * Return a copy of the attribute names held by this element.
   */
  getAttributeNames(): (keyof AttributesFrom<T>)[];

  /**
   * Return the backing native view instance for this element.
   * If the element has no backing view, the returned
   * instance will be undefined.
   * @deprecated use {@link getNativeNode} instead
   */
  getNativeView(): Promise<NativeView | undefined>;

  /**
   * Return the backing native node for this element.
   * If the element has no backing node, the returned
   * instance will be undefined.
   */
  getNativeNode(): NativeNode | undefined;

  /**
   * Take a bitmap snapshot of the element
   */
  takeSnapshot(): Promise<string | undefined>;
}
