// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

package com.snapchat.client.valdi;

import com.snapchat.djinni.NativeObjectManager;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class JSRuntime {
    /**
     * Push the module unmarshalled using the schema in the given marshaller handle
     * into the marshaller.
     */
    public abstract int pushModuleToMarshaller(JSRuntimeNativeObjectsManager nativeObjectsManager, java.lang.String path, long marshallerHandle);

    public abstract void addModuleUnloadObserver(java.lang.String path, java.lang.Object observer);

    public abstract void preloadModule(java.lang.String path, int maxDepth);

    public abstract JSRuntimeNativeObjectsManager createNativeObjectsManager();

    public abstract void destroyNativeObjectsManager(JSRuntimeNativeObjectsManager nativeObjectsManager);

    public abstract JSRuntime createWorker();

    public abstract void runOnJsThread(java.lang.Object runnable);

    public static final class CppProxy extends JSRuntime
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);

        @Override
        public int pushModuleToMarshaller(JSRuntimeNativeObjectsManager nativeObjectsManager, java.lang.String path, long marshallerHandle)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_pushModuleToMarshaller(this.nativeRef, nativeObjectsManager, path, marshallerHandle);
        }
        private native int native_pushModuleToMarshaller(long _nativeRef, JSRuntimeNativeObjectsManager nativeObjectsManager, java.lang.String path, long marshallerHandle);

        @Override
        public void addModuleUnloadObserver(java.lang.String path, java.lang.Object observer)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_addModuleUnloadObserver(this.nativeRef, path, observer);
        }
        private native void native_addModuleUnloadObserver(long _nativeRef, java.lang.String path, java.lang.Object observer);

        @Override
        public void preloadModule(java.lang.String path, int maxDepth)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_preloadModule(this.nativeRef, path, maxDepth);
        }
        private native void native_preloadModule(long _nativeRef, java.lang.String path, int maxDepth);

        @Override
        public JSRuntimeNativeObjectsManager createNativeObjectsManager()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_createNativeObjectsManager(this.nativeRef);
        }
        private native JSRuntimeNativeObjectsManager native_createNativeObjectsManager(long _nativeRef);

        @Override
        public void destroyNativeObjectsManager(JSRuntimeNativeObjectsManager nativeObjectsManager)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_destroyNativeObjectsManager(this.nativeRef, nativeObjectsManager);
        }
        private native void native_destroyNativeObjectsManager(long _nativeRef, JSRuntimeNativeObjectsManager nativeObjectsManager);

        @Override
        public JSRuntime createWorker()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_createWorker(this.nativeRef);
        }
        private native JSRuntime native_createWorker(long _nativeRef);

        @Override
        public void runOnJsThread(java.lang.Object runnable)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_runOnJsThread(this.nativeRef, runnable);
        }
        private native void native_runOnJsThread(long _nativeRef, java.lang.Object runnable);
    }
}
