// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

package com.snapchat.client.valdi;

public abstract class Keychain {
    /** Store the given string blob into the keychain */
    public abstract com.snap.valdi.utils.ValdiResult store(java.lang.String key, byte[] value);

    /**
     * Retrieve the stored blob for the given key.
     * Returns empty data if the value was not found.
     */
    public abstract byte[] get(java.lang.String key);

    /** Erase the stored blob for the given key. */
    public abstract boolean erase(java.lang.String key);
}
