// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

package com.snapchat.client.valdi;

import com.snapchat.djinni.NativeObjectManager;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class RuntimeMessageHandler {
    public abstract void onUncaughtJsError(int errorCode, java.lang.String moduleName, String errorMessage, String stackTrace);

    public abstract void onJsCrash(java.lang.String moduleName, String errorMessage, String stackTrace, boolean isANR);

    public abstract void onDebugMessage(int level, String message);

    public static final class CppProxy extends RuntimeMessageHandler
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);

        @Override
        public void onUncaughtJsError(int errorCode, java.lang.String moduleName, String errorMessage, String stackTrace)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onUncaughtJsError(this.nativeRef, errorCode, moduleName, errorMessage, stackTrace);
        }
        private native void native_onUncaughtJsError(long _nativeRef, int errorCode, java.lang.String moduleName, String errorMessage, String stackTrace);

        @Override
        public void onJsCrash(java.lang.String moduleName, String errorMessage, String stackTrace, boolean isANR)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onJsCrash(this.nativeRef, moduleName, errorMessage, stackTrace, isANR);
        }
        private native void native_onJsCrash(long _nativeRef, java.lang.String moduleName, String errorMessage, String stackTrace, boolean isANR);

        @Override
        public void onDebugMessage(int level, String message)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onDebugMessage(this.nativeRef, level, message);
        }
        private native void native_onDebugMessage(long _nativeRef, int level, String message);
    }
}
