// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#import "valdi_core/SCNValdiCoreHTTPResponse.h"
#import <Foundation/Foundation.h>


@interface SCNValdiCoreHTTPRequestManagerCompletion : NSObject

- (void)onComplete:(nonnull SCNValdiCoreHTTPResponse *)response;

- (void)onFail:(nonnull NSString *)error;

@end
