// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#ifdef __cplusplus
#import "valdi_core/SCNValdiCoreAnimator+Private.h"
#import "valdi_core/SCNValdiCoreAnimator.h"
#import "djinni/objc/DJIObjcWrapperCache+Private.h"
#import "valdi_core/bindings/ValueTranslator_objc.hpp"
#include "utils/debugging/DjinniPrologue.hpp"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated_client::valdi_core {

class Animator::ObjcProxy final
: public ::snap::valdi_core::Animator
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated_client::valdi_core::Animator;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void flushAnimations(const Valdi::Value & c_completion) override
    {
        DJINNI_FUNCTION_PROLOGUE("Animator.flushAnimations");
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() flushAnimations:(ValdiIOS::ValueTranslator::fromCpp(c_completion))];
        }
    }
    void cancel() override
    {
        DJINNI_FUNCTION_PROLOGUE("Animator.cancel");
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() cancel];
        }
    }
};

} // namespace djinni_generated_client::valdi_core

namespace djinni_generated_client::valdi_core {

auto Animator::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto Animator::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

} // namespace djinni_generated_client::valdi_core
#endif // __cplusplus
