// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, SCNValdiCorePlatform)
{
    SCNValdiCorePlatformIos = 0,
    SCNValdiCorePlatformAndroid = 1,
    SCNValdiCorePlatformSkia = 2,
};
