// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#ifdef __cplusplus
#import "valdi_core/SCNValdiCoreHTTPRequest.h"
#include "valdi_core/HTTPRequest.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SCNValdiCoreHTTPRequest;

namespace djinni_generated_client::valdi_core {

struct HTTPRequest
{
    using CppType = ::snap::valdi_core::HTTPRequest;
    using ObjcType = SCNValdiCoreHTTPRequest*;

    using Boxed = HTTPRequest;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated_client::valdi_core
#endif // __cplusplus
