// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, SCNValdiCoreAssetOutputType)
{
    SCNValdiCoreAssetOutputTypeBytes = 0,
    SCNValdiCoreAssetOutputTypeImageIOS = 1,
    SCNValdiCoreAssetOutputTypeImageAndroid = 2,
    SCNValdiCoreAssetOutputTypeImageSnapDrawing = 3,
    SCNValdiCoreAssetOutputTypeVideoIOS = 4,
    SCNValdiCoreAssetOutputTypeVideoAndroid = 5,
    SCNValdiCoreAssetOutputTypeLottie = 6,
    SCNValdiCoreAssetOutputTypeDummy = 7,
};
