// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, SCNValdiCoreJavaScriptEngineType)
{
    SCNValdiCoreJavaScriptEngineTypeAuto = 0,
    SCNValdiCoreJavaScriptEngineTypeQuickJS = 1,
    SCNValdiCoreJavaScriptEngineTypeJSCore = 2,
    SCNValdiCoreJavaScriptEngineTypeV8 = 3,
    SCNValdiCoreJavaScriptEngineTypeHermes = 4,
};
