// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#import <Foundation/Foundation.h>

@interface SCNValdiCoreHTTPResponse : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithStatusCode:(int32_t)statusCode
                                   headers:(nonnull NSObject *)headers
                                      body:(nullable NSData *)body NS_DESIGNATED_INITIALIZER;

@property (nonatomic, readonly) int32_t statusCode;

@property (nonatomic, readonly, nonnull) NSObject * headers;

@property (nonatomic, readonly, nullable) NSData * body;

@end
