// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#import <Foundation/Foundation.h>

@interface SCNValdiCoreHTTPRequest : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithUrl:(nonnull NSString *)url
                             method:(nonnull NSString *)method
                            headers:(nonnull NSObject *)headers
                               body:(nullable NSData *)body
                           priority:(int32_t)priority NS_DESIGNATED_INITIALIZER;

@property (nonatomic, readonly, nonnull) NSString * url;

@property (nonatomic, readonly, nonnull) NSString * method;

@property (nonatomic, readonly, nonnull) NSObject * headers;

@property (nonatomic, readonly, nullable) NSData * body;

/** Between 0 being lowest, to 10 being maximum */
@property (nonatomic, readonly) int32_t priority;

@end
