// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, SCNValdiCoreAnimationType)
{
    SCNValdiCoreAnimationTypeLinear = 0,
    SCNValdiCoreAnimationTypeEaseIn = 1,
    SCNValdiCoreAnimationTypeEaseOut = 2,
    SCNValdiCoreAnimationTypeEaseInOut = 3,
};
