// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#ifdef __cplusplus
#import "valdi_core/SCNValdiCoreHTTPRequest+Private.h"
#import "djinni/objc/DJIMarshal+Private.h"
#import "valdi_core/bindings/BytesTranslator_objc.hpp"
#import "valdi_core/bindings/InternedStringTranslator_objc.hpp"
#import "valdi_core/bindings/ValueTranslator_objc.hpp"
#include <cassert>

namespace djinni_generated_client::valdi_core {

auto HTTPRequest::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {ValdiIOS::InternedStringTranslator::toCpp(obj.url),
            ValdiIOS::InternedStringTranslator::toCpp(obj.method),
            ValdiIOS::ValueTranslator::toCpp(obj.headers),
            ::djinni::Optional<std::optional, ValdiIOS::BytesTranslator>::toCpp(obj.body),
            ::djinni::I32::toCpp(obj.priority)};
}

auto HTTPRequest::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[SCNValdiCoreHTTPRequest alloc] initWithUrl:(ValdiIOS::InternedStringTranslator::fromCpp(cpp.url))
                                                 method:(ValdiIOS::InternedStringTranslator::fromCpp(cpp.method))
                                                headers:(ValdiIOS::ValueTranslator::fromCpp(cpp.headers))
                                                   body:(::djinni::Optional<std::optional, ValdiIOS::BytesTranslator>::fromCpp(cpp.body))
                                               priority:(::djinni::I32::fromCpp(cpp.priority))];
}

} // namespace djinni_generated_client::valdi_core
#endif // __cplusplus
