// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#import <Foundation/Foundation.h>
@protocol SCNValdiCoreModuleFactory;


/**
 * The ModuleFactoriesProvider will be invoked when the RuntimeManager is initialized
 * to provide additional built-in Modules that will be exposed to the JS runtime environment.
 */
@protocol SCNValdiCoreModuleFactoriesProvider <NSObject>

/** Create and return the module factories that will be exposed to the JS runtime environment. */
- (nonnull NSArray<id<SCNValdiCoreModuleFactory>> *)createModuleFactories:(nonnull NSObject *)runtimeManager;

@end
