// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#ifdef __cplusplus
#include "valdi_core/AttributeType.hpp"
#import "djinni/objc/DJIMarshal+Private.h"

#endif // __cplusplus
