// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#import "valdi_core/SCNValdiCoreAssetOutputType.h"
#import <Foundation/Foundation.h>
@protocol SCNValdiCoreAssetLoadObserver;


/** Represents a loadable asset like an Image */
@interface SCNValdiCoreAsset : NSObject

/** Return a string that uniquely identifies this asset */
- (nonnull NSString *)getIdentifier;

/**
 * Measure the width that should be used for this asset
 * given a max width and height.
 */
- (double)measureWidth:(double)maxWidth
             maxHeight:(double)maxHeight;

/**
 * Measure the height that should be used for this asset
 * given a max width and height.
 */
- (double)measureHeight:(double)maxWidth
              maxHeight:(double)maxHeight;

/**
 * Append a load observer, which will be notified
 * when the asset is loaded.
 */
- (void)addLoadObserver:(nullable id<SCNValdiCoreAssetLoadObserver>)observer
             outputType:(SCNValdiCoreAssetOutputType)outputType
         preferredWidth:(int32_t)preferredWidth
        preferredHeight:(int32_t)preferredHeight
                 filter:(nonnull NSObject *)filter;

/** Remove a previously registered load observer */
- (void)removeLoadObserver:(nullable id<SCNValdiCoreAssetLoadObserver>)observer;

/** Update the preferred width and height of a previously registered load observer */
- (void)updateLoadObserverPreferredSize:(nullable id<SCNValdiCoreAssetLoadObserver>)observer
                         preferredWidth:(int32_t)preferredWidth
                        preferredHeight:(int32_t)preferredHeight;

@end
