// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#ifdef __cplusplus
#include "valdi_core/bindings/UndefExceptions_objc.hpp"
#import "valdi_core/SCNValdiCoreHTTPRequestManagerCompletion+Private.h"
#import "valdi_core/SCNValdiCoreHTTPRequestManagerCompletion.h"
#import "djinni/objc/DJICppWrapperCache+Private.h"
#import "djinni/objc/DJIError.h"
#import "djinni/objc/DJIMarshal+Private.h"
#import "valdi_core/SCNValdiCoreHTTPResponse+Private.h"
#include "utils/debugging/DjinniPrologue.hpp"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SCNValdiCoreHTTPRequestManagerCompletion ()

- (id)initWithCpp:(const std::shared_ptr<::snap::valdi_core::HTTPRequestManagerCompletion>&)cppRef;

@end

@implementation SCNValdiCoreHTTPRequestManagerCompletion {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::snap::valdi_core::HTTPRequestManagerCompletion>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::snap::valdi_core::HTTPRequestManagerCompletion>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)onComplete:(nonnull SCNValdiCoreHTTPResponse *)response {
    try {
        DJINNI_FUNCTION_PROLOGUE("HTTPRequestManagerCompletion.onComplete");
        _cppRefHandle.get()->onComplete(::djinni_generated_client::valdi_core::HTTPResponse::toCpp(response));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)onFail:(nonnull NSString *)error {
    try {
        DJINNI_FUNCTION_PROLOGUE("HTTPRequestManagerCompletion.onFail");
        _cppRefHandle.get()->onFail(::djinni::String::toCpp(error));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated_client::valdi_core {

auto HTTPRequestManagerCompletion::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto HTTPRequestManagerCompletion::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SCNValdiCoreHTTPRequestManagerCompletion>(cpp);
}

} // namespace djinni_generated_client::valdi_core

@end
#endif // __cplusplus
