// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#import <Foundation/Foundation.h>


@protocol SCNValdiCoreAnimator <NSObject>

/** The Value is a wrapped completion callback */
- (void)flushAnimations:(nonnull NSObject *)completion;

/** Cancel an animation */
- (void)cancel;

@end
