// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#import "valdi_core/SCNValdiCoreHTTPResponse.h"


@implementation SCNValdiCoreHTTPResponse

- (nonnull instancetype)initWithStatusCode:(int32_t)statusCode
                                   headers:(nonnull NSObject *)headers
                                      body:(nullable NSData *)body
{
    if (self = [super init]) {
        _statusCode = statusCode;
        _headers = headers;
        _body = body;
    }
    return self;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p statusCode:%@ headers:%@ body:%@>", self.class, (void *)self, @(self.statusCode), self.headers, self.body];
}

#endif
@end
