// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#import "valdi_core/SCNValdiCoreCompositeAttributePart.h"


@implementation SCNValdiCoreCompositeAttributePart

- (nonnull instancetype)initWithAttribute:(nonnull NSString *)attribute
                                     type:(SCNValdiCoreAttributeType)type
                                 optional:(BOOL)optional
                 invalidateLayoutOnChange:(BOOL)invalidateLayoutOnChange
{
    if (self = [super init]) {
        _attribute = attribute;
        _type = type;
        _optional = optional;
        _invalidateLayoutOnChange = invalidateLayoutOnChange;
    }
    return self;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p attribute:%@ type:%@ optional:%@ invalidateLayoutOnChange:%@>", self.class, (void *)self, self.attribute, @(self.type), @(self.optional), @(self.invalidateLayoutOnChange)];
}

#endif
@end
