// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#import "valdi_core/SCNValdiCoreHTTPRequest.h"
#import <Foundation/Foundation.h>
@class SCNValdiCoreHTTPRequestManagerCompletion;
@protocol SCNValdiCoreCancelable;


@protocol SCNValdiCoreHTTPRequestManager <NSObject>

- (nullable id<SCNValdiCoreCancelable>)performRequest:(nonnull SCNValdiCoreHTTPRequest *)request
                                           completion:(nullable SCNValdiCoreHTTPRequestManagerCompletion *)completion;

@end
