// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#ifdef __cplusplus
#include "valdi_core/ModuleFactoriesProvider.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol SCNValdiCoreModuleFactoriesProvider;

namespace djinni_generated_client::valdi_core {

class ModuleFactoriesProvider
{
public:
    using CppType = std::shared_ptr<::snap::valdi_core::ModuleFactoriesProvider>;
    using CppOptType = std::shared_ptr<::snap::valdi_core::ModuleFactoriesProvider>;
    using ObjcType = id<SCNValdiCoreModuleFactoriesProvider>;

    using Boxed = ModuleFactoriesProvider;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated_client::valdi_core

#endif // __cplusplus
