// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#import "valdi_core/SCNValdiCoreAttributeType.h"
#import <Foundation/Foundation.h>

@interface SCNValdiCoreCompositeAttributePart : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithAttribute:(nonnull NSString *)attribute
                                     type:(SCNValdiCoreAttributeType)type
                                 optional:(BOOL)optional
                 invalidateLayoutOnChange:(BOOL)invalidateLayoutOnChange NS_DESIGNATED_INITIALIZER;

@property (nonatomic, readonly, nonnull) NSString * attribute;

@property (nonatomic, readonly) SCNValdiCoreAttributeType type;

@property (nonatomic, readonly) BOOL optional;

@property (nonatomic, readonly) BOOL invalidateLayoutOnChange;

@end
