// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#ifdef __cplusplus
#import "valdi_core/SCNValdiCoreAssetLoadObserver+Private.h"
#import "valdi_core/SCNValdiCoreAssetLoadObserver.h"
#import "djinni/objc/DJIMarshal+Private.h"
#import "djinni/objc/DJIObjcWrapperCache+Private.h"
#import "valdi_core/SCNValdiCoreAsset+Private.h"
#import "valdi_core/bindings/InternedStringTranslator_objc.hpp"
#import "valdi_core/bindings/ValueTranslator_objc.hpp"
#include "utils/debugging/DjinniPrologue.hpp"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated_client::valdi_core {

class AssetLoadObserver::ObjcProxy final
: public ::snap::valdi_core::AssetLoadObserver
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated_client::valdi_core::AssetLoadObserver;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void onLoad(const /*not-null*/ std::shared_ptr<::snap::valdi_core::Asset> & c_asset, const Valdi::Value & c_loadedAsset, const std::optional<Valdi::StringBox> & c_error) override
    {
        DJINNI_FUNCTION_PROLOGUE("AssetLoadObserver.onLoad");
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onLoad:(::djinni_generated_client::valdi_core::Asset::fromCpp(c_asset))
                                                 loadedAsset:(ValdiIOS::ValueTranslator::fromCpp(c_loadedAsset))
                                                       error:(::djinni::Optional<std::optional, ValdiIOS::InternedStringTranslator>::fromCpp(c_error))];
        }
    }
};

} // namespace djinni_generated_client::valdi_core

namespace djinni_generated_client::valdi_core {

auto AssetLoadObserver::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto AssetLoadObserver::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

} // namespace djinni_generated_client::valdi_core
#endif // __cplusplus
