// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#ifdef __cplusplus
#import "valdi_core/SCNValdiCoreHTTPResponse+Private.h"
#import "djinni/objc/DJIMarshal+Private.h"
#import "valdi_core/bindings/BytesTranslator_objc.hpp"
#import "valdi_core/bindings/ValueTranslator_objc.hpp"
#include <cassert>

namespace djinni_generated_client::valdi_core {

auto HTTPResponse::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.statusCode),
            ValdiIOS::ValueTranslator::toCpp(obj.headers),
            ::djinni::Optional<std::optional, ValdiIOS::BytesTranslator>::toCpp(obj.body)};
}

auto HTTPResponse::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[SCNValdiCoreHTTPResponse alloc] initWithStatusCode:(::djinni::I32::fromCpp(cpp.statusCode))
                                                        headers:(ValdiIOS::ValueTranslator::fromCpp(cpp.headers))
                                                           body:(::djinni::Optional<std::optional, ValdiIOS::BytesTranslator>::fromCpp(cpp.body))];
}

} // namespace djinni_generated_client::valdi_core
#endif // __cplusplus
