// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#ifdef __cplusplus
#import "valdi_core/SCNValdiCoreModuleFactoriesProvider+Private.h"
#import "valdi_core/SCNValdiCoreModuleFactoriesProvider.h"
#import "djinni/objc/DJICppWrapperCache+Private.h"
#import "djinni/objc/DJIError.h"
#import "djinni/objc/DJIMarshal+Private.h"
#import "djinni/objc/DJIObjcWrapperCache+Private.h"
#import "valdi_core/SCNValdiCoreModuleFactory+Private.h"
#import "valdi_core/bindings/ValueTranslator_objc.hpp"
#include "utils/debugging/DjinniPrologue.hpp"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SCNValdiCoreModuleFactoriesProviderCppProxy : NSObject<SCNValdiCoreModuleFactoriesProvider>

- (id)initWithCpp:(const std::shared_ptr<::snap::valdi_core::ModuleFactoriesProvider>&)cppRef;

@end

@implementation SCNValdiCoreModuleFactoriesProviderCppProxy {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::snap::valdi_core::ModuleFactoriesProvider>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::snap::valdi_core::ModuleFactoriesProvider>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nonnull NSArray<id<SCNValdiCoreModuleFactory>> *)createModuleFactories:(nonnull NSObject *)runtimeManager {
    try {
        DJINNI_FUNCTION_PROLOGUE("ModuleFactoriesProvider.createModuleFactories");
        auto objcpp_result_ = _cppRefHandle.get()->createModuleFactories(ValdiIOS::ValueTranslator::toCpp(runtimeManager));
        return ::djinni::List<::djinni_generated_client::valdi_core::ModuleFactory>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated_client::valdi_core {

class ModuleFactoriesProvider::ObjcProxy final
: public ::snap::valdi_core::ModuleFactoriesProvider
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated_client::valdi_core::ModuleFactoriesProvider;
public:
    using ObjcProxyBase::ObjcProxyBase;
    std::vector</*not-null*/ std::shared_ptr<::snap::valdi_core::ModuleFactory>> createModuleFactories(const Valdi::Value & c_runtimeManager) override
    {
        DJINNI_FUNCTION_PROLOGUE("ModuleFactoriesProvider.createModuleFactories");
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() createModuleFactories:(ValdiIOS::ValueTranslator::fromCpp(c_runtimeManager))];
            return ::djinni::List<::djinni_generated_client::valdi_core::ModuleFactory>::toCpp(objcpp_result_);
        }
    }
};

} // namespace djinni_generated_client::valdi_core

namespace djinni_generated_client::valdi_core {

auto ModuleFactoriesProvider::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    if ([(id)objc isKindOfClass:[SCNValdiCoreModuleFactoriesProviderCppProxy class]]) {
        return ((SCNValdiCoreModuleFactoriesProviderCppProxy*)objc)->_cppRefHandle.get();
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto ModuleFactoriesProvider::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    if (auto cppPtr = dynamic_cast<ObjcProxy*>(cpp.get())) {
        return cppPtr->djinni_private_get_proxied_objc_object();
    }
    return ::djinni::get_cpp_proxy<SCNValdiCoreModuleFactoriesProviderCppProxy>(cpp);
}

} // namespace djinni_generated_client::valdi_core

@end
#endif // __cplusplus
