// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#ifdef __cplusplus
#import "valdi_core/SCNValdiCoreHTTPResponse.h"
#include "valdi_core/HTTPResponse.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SCNValdiCoreHTTPResponse;

namespace djinni_generated_client::valdi_core {

struct HTTPResponse
{
    using CppType = ::snap::valdi_core::HTTPResponse;
    using ObjcType = SCNValdiCoreHTTPResponse*;

    using Boxed = HTTPResponse;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated_client::valdi_core
#endif // __cplusplus
