// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, SCNValdiCoreAttributeType)
{
    SCNValdiCoreAttributeTypeString = 0,
    SCNValdiCoreAttributeTypeDouble = 1,
    SCNValdiCoreAttributeTypeInt = 2,
    SCNValdiCoreAttributeTypeBoolean = 3,
    SCNValdiCoreAttributeTypeColor = 4,
    SCNValdiCoreAttributeTypeUntyped = 5,
};
