// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#import <Foundation/Foundation.h>


@protocol SCNValdiCoreCancelable <NSObject>

- (void)cancel;

@end
