// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#import <Foundation/Foundation.h>


@protocol SCNValdiCoreModuleFactory <NSObject>

/**
 * Return the path of the module, which represents its path
 * when imported from TypeScript.
 */
- (nonnull NSString *)getModulePath;

/**
 * Returns the module exports object that should be returned to
 * TypeScript when the module is imported.
 */
- (nonnull NSObject *)loadModule;

@end
