// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#ifdef __cplusplus
#import "valdi_core/SCNValdiCoreModuleFactory+Private.h"
#import "valdi_core/SCNValdiCoreModuleFactory.h"
#import "djinni/objc/DJICppWrapperCache+Private.h"
#import "djinni/objc/DJIError.h"
#import "djinni/objc/DJIObjcWrapperCache+Private.h"
#import "valdi_core/bindings/InternedStringTranslator_objc.hpp"
#import "valdi_core/bindings/ValueTranslator_objc.hpp"
#include "utils/debugging/DjinniPrologue.hpp"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SCNValdiCoreModuleFactoryCppProxy : NSObject<SCNValdiCoreModuleFactory>

- (id)initWithCpp:(const std::shared_ptr<::snap::valdi_core::ModuleFactory>&)cppRef;

@end

@implementation SCNValdiCoreModuleFactoryCppProxy {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::snap::valdi_core::ModuleFactory>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::snap::valdi_core::ModuleFactory>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nonnull NSString *)getModulePath {
    try {
        DJINNI_FUNCTION_PROLOGUE("ModuleFactory.getModulePath");
        auto objcpp_result_ = _cppRefHandle.get()->getModulePath();
        return ValdiIOS::InternedStringTranslator::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSObject *)loadModule {
    try {
        DJINNI_FUNCTION_PROLOGUE("ModuleFactory.loadModule");
        auto objcpp_result_ = _cppRefHandle.get()->loadModule();
        return ValdiIOS::ValueTranslator::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated_client::valdi_core {

class ModuleFactory::ObjcProxy final
: public ::snap::valdi_core::ModuleFactory
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated_client::valdi_core::ModuleFactory;
public:
    using ObjcProxyBase::ObjcProxyBase;
    Valdi::StringBox getModulePath() override
    {
        DJINNI_FUNCTION_PROLOGUE("ModuleFactory.getModulePath");
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() getModulePath];
            return ValdiIOS::InternedStringTranslator::toCpp(objcpp_result_);
        }
    }
    Valdi::Value loadModule() override
    {
        DJINNI_FUNCTION_PROLOGUE("ModuleFactory.loadModule");
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() loadModule];
            return ValdiIOS::ValueTranslator::toCpp(objcpp_result_);
        }
    }
};

} // namespace djinni_generated_client::valdi_core

namespace djinni_generated_client::valdi_core {

auto ModuleFactory::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    if ([(id)objc isKindOfClass:[SCNValdiCoreModuleFactoryCppProxy class]]) {
        return ((SCNValdiCoreModuleFactoryCppProxy*)objc)->_cppRefHandle.get();
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto ModuleFactory::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    if (auto cppPtr = dynamic_cast<ObjcProxy*>(cpp.get())) {
        return cppPtr->djinni_private_get_proxied_objc_object();
    }
    return ::djinni::get_cpp_proxy<SCNValdiCoreModuleFactoryCppProxy>(cpp);
}

} // namespace djinni_generated_client::valdi_core

@end
#endif // __cplusplus
