// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#ifdef __cplusplus
#import "valdi_core/SCNValdiCoreCompositeAttributePart.h"
#include "valdi_core/CompositeAttributePart.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SCNValdiCoreCompositeAttributePart;

namespace djinni_generated_client::valdi_core {

struct CompositeAttributePart
{
    using CppType = ::snap::valdi_core::CompositeAttributePart;
    using ObjcType = SCNValdiCoreCompositeAttributePart*;

    using Boxed = CompositeAttributePart;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated_client::valdi_core
#endif // __cplusplus
