// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#ifdef __cplusplus
#import "valdi_core/SCNValdiCoreAsset+Private.h"
#import "valdi_core/SCNValdiCoreAsset.h"
#import "djinni/objc/DJICppWrapperCache+Private.h"
#import "djinni/objc/DJIError.h"
#import "djinni/objc/DJIMarshal+Private.h"
#import "valdi_core/SCNValdiCoreAssetLoadObserver+Private.h"
#import "valdi_core/SCNValdiCoreAssetOutputType+Private.h"
#import "valdi_core/bindings/InternedStringTranslator_objc.hpp"
#import "valdi_core/bindings/ValueTranslator_objc.hpp"
#include "utils/debugging/DjinniPrologue.hpp"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SCNValdiCoreAsset ()

- (id)initWithCpp:(const std::shared_ptr<::snap::valdi_core::Asset>&)cppRef;

@end

@implementation SCNValdiCoreAsset {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::snap::valdi_core::Asset>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::snap::valdi_core::Asset>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nonnull NSString *)getIdentifier {
    try {
        DJINNI_FUNCTION_PROLOGUE("Asset.getIdentifier");
        auto objcpp_result_ = _cppRefHandle.get()->getIdentifier();
        return ValdiIOS::InternedStringTranslator::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (double)measureWidth:(double)maxWidth
             maxHeight:(double)maxHeight {
    try {
        DJINNI_FUNCTION_PROLOGUE("Asset.measureWidth");
        auto objcpp_result_ = _cppRefHandle.get()->measureWidth(::djinni::F64::toCpp(maxWidth),
                                                                ::djinni::F64::toCpp(maxHeight));
        return ::djinni::F64::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (double)measureHeight:(double)maxWidth
              maxHeight:(double)maxHeight {
    try {
        DJINNI_FUNCTION_PROLOGUE("Asset.measureHeight");
        auto objcpp_result_ = _cppRefHandle.get()->measureHeight(::djinni::F64::toCpp(maxWidth),
                                                                 ::djinni::F64::toCpp(maxHeight));
        return ::djinni::F64::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)addLoadObserver:(nullable id<SCNValdiCoreAssetLoadObserver>)observer
             outputType:(SCNValdiCoreAssetOutputType)outputType
         preferredWidth:(int32_t)preferredWidth
        preferredHeight:(int32_t)preferredHeight
                 filter:(nonnull NSObject *)filter {
    try {
        DJINNI_FUNCTION_PROLOGUE("Asset.addLoadObserver");
        _cppRefHandle.get()->addLoadObserver(::djinni_generated_client::valdi_core::AssetLoadObserver::toCpp(observer),
                                             ::djinni::Enum<::snap::valdi_core::AssetOutputType, SCNValdiCoreAssetOutputType>::toCpp(outputType),
                                             ::djinni::I32::toCpp(preferredWidth),
                                             ::djinni::I32::toCpp(preferredHeight),
                                             ValdiIOS::ValueTranslator::toCpp(filter));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)removeLoadObserver:(nullable id<SCNValdiCoreAssetLoadObserver>)observer {
    try {
        DJINNI_FUNCTION_PROLOGUE("Asset.removeLoadObserver");
        _cppRefHandle.get()->removeLoadObserver(::djinni_generated_client::valdi_core::AssetLoadObserver::toCpp(observer));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)updateLoadObserverPreferredSize:(nullable id<SCNValdiCoreAssetLoadObserver>)observer
                         preferredWidth:(int32_t)preferredWidth
                        preferredHeight:(int32_t)preferredHeight {
    try {
        DJINNI_FUNCTION_PROLOGUE("Asset.updateLoadObserverPreferredSize");
        _cppRefHandle.get()->updateLoadObserverPreferredSize(::djinni_generated_client::valdi_core::AssetLoadObserver::toCpp(observer),
                                                             ::djinni::I32::toCpp(preferredWidth),
                                                             ::djinni::I32::toCpp(preferredHeight));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated_client::valdi_core {

auto Asset::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Asset::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SCNValdiCoreAsset>(cpp);
}

} // namespace djinni_generated_client::valdi_core

@end
#endif // __cplusplus
