// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#ifdef __cplusplus
#import "valdi_core/SCNValdiCoreHTTPRequestManager+Private.h"
#import "valdi_core/SCNValdiCoreHTTPRequestManager.h"
#import "djinni/objc/DJIObjcWrapperCache+Private.h"
#import "valdi_core/SCNValdiCoreCancelable+Private.h"
#import "valdi_core/SCNValdiCoreHTTPRequest+Private.h"
#import "valdi_core/SCNValdiCoreHTTPRequestManagerCompletion+Private.h"
#include "utils/debugging/DjinniPrologue.hpp"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated_client::valdi_core {

class HTTPRequestManager::ObjcProxy final
: public ::snap::valdi_core::HTTPRequestManager
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated_client::valdi_core::HTTPRequestManager;
public:
    using ObjcProxyBase::ObjcProxyBase;
    /*not-null*/ std::shared_ptr<::snap::valdi_core::Cancelable> performRequest(const ::snap::valdi_core::HTTPRequest & c_request, const /*not-null*/ std::shared_ptr<::snap::valdi_core::HTTPRequestManagerCompletion> & c_completion) override
    {
        DJINNI_FUNCTION_PROLOGUE("HTTPRequestManager.performRequest");
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() performRequest:(::djinni_generated_client::valdi_core::HTTPRequest::fromCpp(c_request))
                                                                                completion:(::djinni_generated_client::valdi_core::HTTPRequestManagerCompletion::fromCpp(c_completion))];
            return ::djinni_generated_client::valdi_core::Cancelable::toCpp(objcpp_result_);
        }
    }
};

} // namespace djinni_generated_client::valdi_core

namespace djinni_generated_client::valdi_core {

auto HTTPRequestManager::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto HTTPRequestManager::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

} // namespace djinni_generated_client::valdi_core
#endif // __cplusplus
