// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#import "valdi_core/SCNValdiCoreHTTPRequest.h"


@implementation SCNValdiCoreHTTPRequest

- (nonnull instancetype)initWithUrl:(nonnull NSString *)url
                             method:(nonnull NSString *)method
                            headers:(nonnull NSObject *)headers
                               body:(nullable NSData *)body
                           priority:(int32_t)priority
{
    if (self = [super init]) {
        _url = url;
        _method = method;
        _headers = headers;
        _body = body;
        _priority = priority;
    }
    return self;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p url:%@ method:%@ headers:%@ body:%@ priority:%@>", self.class, (void *)self, self.url, self.method, self.headers, self.body, @(self.priority)];
}

#endif
@end
