// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#import <Foundation/Foundation.h>
@class SCNValdiCoreAsset;


@protocol SCNValdiCoreAssetLoadObserver <NSObject>

- (void)onLoad:(nullable SCNValdiCoreAsset *)asset
   loadedAsset:(nonnull NSObject *)loadedAsset
         error:(nullable NSString *)error;

@end
