// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#ifdef __cplusplus
#import "valdi_core/SCNValdiCoreCompositeAttributePart+Private.h"
#import "djinni/objc/DJIMarshal+Private.h"
#import "valdi_core/SCNValdiCoreAttributeType+Private.h"
#import "valdi_core/bindings/InternedStringTranslator_objc.hpp"
#include <cassert>

namespace djinni_generated_client::valdi_core {

auto CompositeAttributePart::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {ValdiIOS::InternedStringTranslator::toCpp(obj.attribute),
            ::djinni::Enum<::snap::valdi_core::AttributeType, SCNValdiCoreAttributeType>::toCpp(obj.type),
            ::djinni::Bool::toCpp(obj.optional),
            ::djinni::Bool::toCpp(obj.invalidateLayoutOnChange)};
}

auto CompositeAttributePart::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[SCNValdiCoreCompositeAttributePart alloc] initWithAttribute:(ValdiIOS::InternedStringTranslator::fromCpp(cpp.attribute))
                                                                    type:(::djinni::Enum<::snap::valdi_core::AttributeType, SCNValdiCoreAttributeType>::fromCpp(cpp.type))
                                                                optional:(::djinni::Bool::fromCpp(cpp.optional))
                                                invalidateLayoutOnChange:(::djinni::Bool::fromCpp(cpp.invalidateLayoutOnChange))];
}

} // namespace djinni_generated_client::valdi_core
#endif // __cplusplus
