package com.snap.valdi.navigation

import com.snap.valdi.schema.ValdiClass
import com.snap.valdi.schema.ValdiClassConstructor
import com.snap.valdi.schema.ValdiField
import com.snap.valdi.utils.ValdiMarshallableObject

/**
 * Generated from type 'INavigatorPageConfig' at 'navigation/src/INavigator.ts' by the Valdi compiler.
 * Please do not edit this file directly.
 */
@ValdiClass(
        schema = "'componentPath':s,'componentViewModel': m<s,u>,'componentContext':m<s,u>,'showPlatformNavigationBar':b@?,'wrapInPlatformNavigationController':b@?,'platformNavigationTitle':s?,'isPartiallyHiding':b@?, 'presentFromBottom':b@?",
)
class INavigatorPageConfig: ValdiMarshallableObject {

    var componentPath: String
        get() = _componentPath
        set(value) { _componentPath = value }

    var componentViewModel: Map<String, Any?>
        get() = _componentViewModel
        set(value) { _componentViewModel = value }

    var componentContext: Map<String, Any?>
        get() = _componentContext
        set(value) { _componentContext = value }

    var showPlatformNavigationBar: Boolean?
        get() = _showPlatformNavigationBar
        set(value) { _showPlatformNavigationBar = value }

    var wrapInPlatformNavigationController: Boolean?
        get() = _wrapInPlatformNavigationController
        set(value) { _wrapInPlatformNavigationController = value }

    var platformNavigationTitle: String?
        get() = _platformNavigationTitle
        set(value) { _platformNavigationTitle = value }

    /**
     * Keeps the source page partially visible.
     */
    var isPartiallyHiding: Boolean?
        get() = _isPartiallyHiding
        set(value) { _isPartiallyHiding = value }

    var presentFromBottom: Boolean?
        get() = _presentFromBottom
        set(value) { _presentFromBottom = value }

    @ValdiField
    private var _componentPath: String

    @ValdiField
    private var _componentViewModel: Map<String, Any?>

    @ValdiField
    private var _componentContext: Map<String, Any?>

    @ValdiField
    private var _showPlatformNavigationBar: Boolean?

    @ValdiField
    private var _wrapInPlatformNavigationController: Boolean?

    @ValdiField
    private var _platformNavigationTitle: String?

    @ValdiField
    private var _isPartiallyHiding: Boolean?

    @ValdiField
    private var _presentFromBottom: Boolean?

    @ValdiClassConstructor
    constructor(componentPath: String, componentViewModel: Map<String, Any?>, componentContext: Map<String, Any?>, showPlatformNavigationBar: Boolean?, wrapInPlatformNavigationController: Boolean?, platformNavigationTitle: String?, isPartiallyHiding: Boolean?, presentFromBottom: Boolean?) {
        _componentPath = componentPath
        _componentViewModel = componentViewModel
        _componentContext = componentContext
        _showPlatformNavigationBar = showPlatformNavigationBar
        _wrapInPlatformNavigationController = wrapInPlatformNavigationController
        _platformNavigationTitle = platformNavigationTitle
        _isPartiallyHiding = isPartiallyHiding
        _presentFromBottom = presentFromBottom
    }

    constructor(componentPath: String, componentViewModel: Map<String, Any?>, componentContext: Map<String, Any?>) {
        _componentPath = componentPath
        _componentViewModel = componentViewModel
        _componentContext = componentContext
        _showPlatformNavigationBar = null
        _wrapInPlatformNavigationController = null
        _platformNavigationTitle = null
        _isPartiallyHiding = null
        _presentFromBottom = null
    }
}
