package com.snap.valdi.navigation

import com.snap.valdi.schema.ValdiClassConstructor
import com.snap.valdi.schema.ValdiField
import com.snap.valdi.schema.ValdiInterface
import com.snap.valdi.schema.ValdiOptionalMethod
import com.snap.valdi.utils.ValdiMarshallable
import com.snap.valdi.utils.ValdiMarshallableObject
import com.snap.valdi.utils.ValdiMarshaller

/**
 * The bridge interface that provides the implementation underlying all the operations exposed via NavigationController.
 *
 * Generated from type 'INavigator' at 'navigation/src/INavigator.ts' by the Valdi compiler.
 * Please do not edit this file directly.
 */
@ValdiInterface(
        schema = "'pushComponent':f*(r:'[0]', b),'pop':f*(b),'popToRoot':f*(b),'popToSelf':f*(b),'presentComponent':f*(r:'[0]', b),'dismiss':f*(b),'forceDisableDismissalGesture':f*(b),'setBackButtonObserver':f?*(f?()),'setOnPausePopAfterDelay':f?*(d@?),'setPageVisibilityObserver':f?*(f?(d@))",
        typeReferences = [INavigatorPageConfig::class],
        proxyClass = INavigator_Proxy::class
)
interface INavigator: ValdiMarshallable {

    fun pushComponent(page: INavigatorPageConfig, animated: Boolean): Unit

    fun pop(animated: Boolean): Unit

    fun popToRoot(animated: Boolean): Unit

    fun popToSelf(animated: Boolean): Unit

    fun presentComponent(page: INavigatorPageConfig, animated: Boolean): Unit

    fun dismiss(animated: Boolean): Unit

    fun forceDisableDismissalGesture(forceDisable: Boolean): Unit

    @ValdiOptionalMethod
    fun setBackButtonObserver(observer: (() -> Unit)?): Unit {
        ValdiMarshallableObject.unimplementedMethod()
    }

    @ValdiOptionalMethod
    fun setOnPausePopAfterDelay(delayMs: Double?): Unit {
        ValdiMarshallableObject.unimplementedMethod()
    }

    @ValdiOptionalMethod
    fun setPageVisibilityObserver(observer: ((Double) -> Unit)?): Unit {
        ValdiMarshallableObject.unimplementedMethod()
    }

    override fun pushToMarshaller(marshaller: ValdiMarshaller) = ValdiMarshallableObject.marshall(INavigator::class.java, marshaller, this)

}

class INavigator_Proxy: INavigator {

    private var _pushComponent: (page: INavigatorPageConfig, animated: Boolean) -> Unit

    private var _pop: (animated: Boolean) -> Unit

    private var _popToRoot: (animated: Boolean) -> Unit

    private var _popToSelf: (animated: Boolean) -> Unit

    private var _presentComponent: (page: INavigatorPageConfig, animated: Boolean) -> Unit

    private var _dismiss: (animated: Boolean) -> Unit

    private var _forceDisableDismissalGesture: (forceDisable: Boolean) -> Unit

    private var _setBackButtonObserver: ((observer: (() -> Unit)?) -> Unit)?

    private var _setOnPausePopAfterDelay: ((delayMs: Double?) -> Unit)?

    private var _setPageVisibilityObserver: ((observer: ((visibility: Double) -> Unit)?) -> Unit)?

    @ValdiField
    override fun pushComponent(page: INavigatorPageConfig, animated: Boolean): Unit {
        return _pushComponent(page, animated)
    }

    @ValdiField
    override fun pop(animated: Boolean): Unit {
        return _pop(animated)
    }

    @ValdiField
    override fun popToRoot(animated: Boolean): Unit {
        return _popToRoot(animated)
    }

    @ValdiField
    override fun popToSelf(animated: Boolean): Unit {
        return _popToSelf(animated)
    }

    @ValdiField
    override fun presentComponent(page: INavigatorPageConfig, animated: Boolean): Unit {
        return _presentComponent(page, animated)
    }

    @ValdiField
    override fun dismiss(animated: Boolean): Unit {
        return _dismiss(animated)
    }

    @ValdiField
    override fun forceDisableDismissalGesture(forceDisable: Boolean): Unit {
        return _forceDisableDismissalGesture(forceDisable)
    }

    @ValdiField
    override fun setBackButtonObserver(observer: (() -> Unit)?): Unit {
        return _setBackButtonObserver?.invoke(observer) ?: Unit
    }

    @ValdiField
    override fun setOnPausePopAfterDelay(delayMs: Double?): Unit {
        return _setOnPausePopAfterDelay?.invoke(delayMs) ?: Unit
    }

    @ValdiField
    override fun setPageVisibilityObserver(observer: ((Double) -> Unit)?): Unit {
        return _setPageVisibilityObserver?.invoke(observer) ?: Unit
    }

    @ValdiClassConstructor
    constructor(pushComponent: (page: INavigatorPageConfig, animated: Boolean) -> Unit, pop: (animated: Boolean) -> Unit, popToRoot: (animated: Boolean) -> Unit, popToSelf: (animated: Boolean) -> Unit, presentComponent: (page: INavigatorPageConfig, animated: Boolean) -> Unit, dismiss: (animated: Boolean) -> Unit, forceDisableDismissalGesture: (forceDisable: Boolean) -> Unit, setBackButtonObserver: ((observer: (() -> Unit)?) -> Unit)?, setOnPausePopAfterDelay: ((delayMs: Double?) -> Unit)?,setPageVisibilityObserver: ((observer: ((visibility: Double) -> Unit)?) -> Unit)?) {
        _pushComponent = pushComponent
        _pop = pop
        _popToRoot = popToRoot
        _popToSelf = popToSelf
        _presentComponent = presentComponent
        _dismiss = dismiss
        _forceDisableDismissalGesture = forceDisableDismissalGesture
        _setBackButtonObserver = setBackButtonObserver
        _setOnPausePopAfterDelay = setOnPausePopAfterDelay
        _setPageVisibilityObserver = setPageVisibilityObserver
    }

    constructor(pushComponent: (page: INavigatorPageConfig, animated: Boolean) -> Unit, pop: (animated: Boolean) -> Unit, popToRoot: (animated: Boolean) -> Unit, popToSelf: (animated: Boolean) -> Unit, presentComponent: (page: INavigatorPageConfig, animated: Boolean) -> Unit, dismiss: (animated: Boolean) -> Unit, forceDisableDismissalGesture: (forceDisable: Boolean) -> Unit) {
        _pushComponent = pushComponent
        _pop = pop
        _popToRoot = popToRoot
        _popToSelf = popToSelf
        _presentComponent = presentComponent
        _dismiss = dismiss
        _forceDisableDismissalGesture = forceDisableDismissalGesture
        _setBackButtonObserver = null
        _setOnPausePopAfterDelay = null
        _setPageVisibilityObserver = null
    }
}
