// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: valdi.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Defines a static attribute name
/// and its value.
struct Valdi_NodeAttribute {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var type: Valdi_NodeAttribute.TypeEnum = .nodeAttributeTypeString

  var name: String = String()

  /// Set if the type is STRING
  var strValue: String = String()

  /// Set if type is INT
  var intValue: Int64 = 0

  /// Set if double is INT
  var doubleValue: Double = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum TypeEnum: SwiftProtobuf.Enum {
    typealias RawValue = Int
    case nodeAttributeTypeString // = 0
    case nodeAttributeTypeInt // = 1
    case nodeAttributeTypeDouble // = 2
    case UNRECOGNIZED(Int)

    init() {
      self = .nodeAttributeTypeString
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .nodeAttributeTypeString
      case 1: self = .nodeAttributeTypeInt
      case 2: self = .nodeAttributeTypeDouble
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .nodeAttributeTypeString: return 0
      case .nodeAttributeTypeInt: return 1
      case .nodeAttributeTypeDouble: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

  }
}

#if swift(>=4.2)

extension Valdi_NodeAttribute.TypeEnum: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [Valdi_NodeAttribute.TypeEnum] = [
    .nodeAttributeTypeString,
    .nodeAttributeTypeInt,
    .nodeAttributeTypeDouble
  ]
}

#endif  // swift(>=4.2)

struct Valdi_DownloadableModuleArtifact {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The url on which the artifact can be downloaded.
  var url: String = String()

  /// The sha256 digest of the artifact data that can be used for verification.
  var sha256Digest: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct Valdi_DownloadableModuleArtifactSignatures {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  // An array of artifacts sorted by url, generated by BundleResourcesProcessor.swift
  var artifacts: [Valdi_DownloadableModuleArtifact] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}


struct Valdi_DownloadableModuleAssets {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var artifact: Valdi_DownloadableModuleArtifact {
    get {return _artifact ?? Valdi_DownloadableModuleArtifact()}
    set {_artifact = newValue}
  }
  /// Returns true if `artifact` has been explicitly set.
  var hasArtifact: Bool {return self._artifact != nil}
  /// Clears the value of `artifact`. Subsequent reads from it will return its default value.
  mutating func clearArtifact() {self._artifact = nil}

  /// The device density for which the assets contained
  /// in this artifact are optimized for.
  /// List of known density:
  /// iPhone @2x: 2
  /// iPhone @3x: 3
  /// Android mdpi: 1
  /// Android hdpi: 1.5
  /// Android xhdpi: 2
  /// Android xxhdpi: 3
  /// Android xxxhdpi: 4
  var deviceDensity: Double = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _artifact: Valdi_DownloadableModuleArtifact?
}

/// Manifest stored in a .valdimodule when the module
/// is downloadable. Contains all the dependencies and all
/// the urls in which the artifact can be downloaded from.
struct Valdi_DownloadableModuleManifest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The name which uniquely identifies the module
  var name: String = String()

  /// Where to download the .valdimodule containing the compiled sources
  /// Can be unset if this module only contains assets
  var artifact: Valdi_DownloadableModuleArtifact {
    get {return _artifact ?? Valdi_DownloadableModuleArtifact()}
    set {_artifact = newValue}
  }
  /// Returns true if `artifact` has been explicitly set.
  var hasArtifact: Bool {return self._artifact != nil}
  /// Clears the value of `artifact`. Subsequent reads from it will return its default value.
  mutating func clearArtifact() {self._artifact = nil}

  /// The list of available artifacts containing the assets.
  var assets: [Valdi_DownloadableModuleAssets] = []

  /// The list of module dependencies on this module.
  /// This can be used to ensure that they are available before
  /// attempting to use the module.
  var dependencies: [String] = []

  /// Whether the downloadable assets are also available locally
  var hasLocalAssets_p: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _artifact: Valdi_DownloadableModuleArtifact?
}

struct Valdi_DaemonAwakeMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The list of device ids that should connect to the announced service
  var deviceIds: [String] = []

  /// The list of usernames that should connect to the announced service
  var usernames: [String] = []

  /// addresses at which the daemon service is listening
  var serviceAddresses: [String] = []

  /// port at which the daemon service is listening
  var servicePort: Int32 = 0

  /// The id of the daemon process
  var processID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct Valdi_ClientAwakeMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var deviceID: String = String()

  var username: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct Valdi_DaemonServiceDiscoveryPayload {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var message: Valdi_DaemonServiceDiscoveryPayload.OneOf_Message?

  var daemonAwakeMessage: Valdi_DaemonAwakeMessage {
    get {
      if case .daemonAwakeMessage(let v)? = message {return v}
      return Valdi_DaemonAwakeMessage()
    }
    set {message = .daemonAwakeMessage(newValue)}
  }

  var clientAwakeMessage: Valdi_ClientAwakeMessage {
    get {
      if case .clientAwakeMessage(let v)? = message {return v}
      return Valdi_ClientAwakeMessage()
    }
    set {message = .clientAwakeMessage(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Message: Equatable {
    case daemonAwakeMessage(Valdi_DaemonAwakeMessage)
    case clientAwakeMessage(Valdi_ClientAwakeMessage)

  #if !swift(>=4.1)
    static func ==(lhs: Valdi_DaemonServiceDiscoveryPayload.OneOf_Message, rhs: Valdi_DaemonServiceDiscoveryPayload.OneOf_Message) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.daemonAwakeMessage, .daemonAwakeMessage): return {
        guard case .daemonAwakeMessage(let l) = lhs, case .daemonAwakeMessage(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.clientAwakeMessage, .clientAwakeMessage): return {
        guard case .clientAwakeMessage(let l) = lhs, case .clientAwakeMessage(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      default: return false
      }
    }
  #endif
  }

  init() {}
}

struct Valdi_StyleNode {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var styles: [Valdi_StyleDeclaration] {
    get {return _storage._styles}
    set {_uniqueStorage()._styles = newValue}
  }

  var ruleIndex: Valdi_CSSRuleIndex {
    get {return _storage._ruleIndex ?? Valdi_CSSRuleIndex()}
    set {_uniqueStorage()._ruleIndex = newValue}
  }
  /// Returns true if `ruleIndex` has been explicitly set.
  var hasRuleIndex: Bool {return _storage._ruleIndex != nil}
  /// Clears the value of `ruleIndex`. Subsequent reads from it will return its default value.
  mutating func clearRuleIndex() {_uniqueStorage()._ruleIndex = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct Valdi_StyleDeclaration {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var attribute: Valdi_NodeAttribute {
    get {return _attribute ?? Valdi_NodeAttribute()}
    set {_attribute = newValue}
  }
  /// Returns true if `attribute` has been explicitly set.
  var hasAttribute: Bool {return self._attribute != nil}
  /// Clears the value of `attribute`. Subsequent reads from it will return its default value.
  mutating func clearAttribute() {self._attribute = nil}

  /// value corresponding to CSS specificity
  var priority: Int32 = 0

  var order: Int32 = 0

  var id: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _attribute: Valdi_NodeAttribute?
}

struct Valdi_NamedStyleNode {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var node: Valdi_StyleNode {
    get {return _node ?? Valdi_StyleNode()}
    set {_node = newValue}
  }
  /// Returns true if `node` has been explicitly set.
  var hasNode: Bool {return self._node != nil}
  /// Clears the value of `node`. Subsequent reads from it will return its default value.
  mutating func clearNode() {self._node = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _node: Valdi_StyleNode?
}

struct Valdi_CSSRuleIndex {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// To determine the rules that match an element, elements should start with
  /// the current element and the document's root CSSRuleIndex, and recur up
  /// through matching ruleIndexes and the element's ancestry. For a particular
  /// element and ruleIndex, the ruleIndex's properties should be checked in the
  /// order they appear in this proto, and the current ruleIndex should be
  /// reassigned if a match is found.
  var idRules: [Valdi_NamedStyleNode] {
    get {return _storage._idRules}
    set {_uniqueStorage()._idRules = newValue}
  }

  var classRules: [Valdi_NamedStyleNode] {
    get {return _storage._classRules}
    set {_uniqueStorage()._classRules = newValue}
  }

  /// the universal selector is implemented as a tagRule with tag '*'
  var tagRules: [Valdi_NamedStyleNode] {
    get {return _storage._tagRules}
    set {_uniqueStorage()._tagRules = newValue}
  }

  var attributeRules: [Valdi_CSSRuleIndex.AttributeRule] {
    get {return _storage._attributeRules}
    set {_uniqueStorage()._attributeRules = newValue}
  }

  var firstChildRule: Valdi_StyleNode {
    get {return _storage._firstChildRule ?? Valdi_StyleNode()}
    set {_uniqueStorage()._firstChildRule = newValue}
  }
  /// Returns true if `firstChildRule` has been explicitly set.
  var hasFirstChildRule: Bool {return _storage._firstChildRule != nil}
  /// Clears the value of `firstChildRule`. Subsequent reads from it will return its default value.
  mutating func clearFirstChildRule() {_uniqueStorage()._firstChildRule = nil}

  var lastChildRule: Valdi_StyleNode {
    get {return _storage._lastChildRule ?? Valdi_StyleNode()}
    set {_uniqueStorage()._lastChildRule = newValue}
  }
  /// Returns true if `lastChildRule` has been explicitly set.
  var hasLastChildRule: Bool {return _storage._lastChildRule != nil}
  /// Clears the value of `lastChildRule`. Subsequent reads from it will return its default value.
  mutating func clearLastChildRule() {_uniqueStorage()._lastChildRule = nil}

  var nthChildRules: [Valdi_CSSRuleIndex.NthChildRule] {
    get {return _storage._nthChildRules}
    set {_uniqueStorage()._nthChildRules = newValue}
  }

  var ancestorRules: Valdi_CSSRuleIndex {
    get {return _storage._ancestorRules ?? Valdi_CSSRuleIndex()}
    set {_uniqueStorage()._ancestorRules = newValue}
  }
  /// Returns true if `ancestorRules` has been explicitly set.
  var hasAncestorRules: Bool {return _storage._ancestorRules != nil}
  /// Clears the value of `ancestorRules`. Subsequent reads from it will return its default value.
  mutating func clearAncestorRules() {_uniqueStorage()._ancestorRules = nil}

  var directParentRules: Valdi_CSSRuleIndex {
    get {return _storage._directParentRules ?? Valdi_CSSRuleIndex()}
    set {_uniqueStorage()._directParentRules = newValue}
  }
  /// Returns true if `directParentRules` has been explicitly set.
  var hasDirectParentRules: Bool {return _storage._directParentRules != nil}
  /// Clears the value of `directParentRules`. Subsequent reads from it will return its default value.
  mutating func clearDirectParentRules() {_uniqueStorage()._directParentRules = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  struct AttributeRule {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var type: Valdi_CSSRuleIndex.AttributeRule.TypeEnum = .equals

    var attribute: Valdi_NodeAttribute {
      get {return _attribute ?? Valdi_NodeAttribute()}
      set {_attribute = newValue}
    }
    /// Returns true if `attribute` has been explicitly set.
    var hasAttribute: Bool {return self._attribute != nil}
    /// Clears the value of `attribute`. Subsequent reads from it will return its default value.
    mutating func clearAttribute() {self._attribute = nil}

    var node: Valdi_StyleNode {
      get {return _node ?? Valdi_StyleNode()}
      set {_node = newValue}
    }
    /// Returns true if `node` has been explicitly set.
    var hasNode: Bool {return self._node != nil}
    /// Clears the value of `node`. Subsequent reads from it will return its default value.
    mutating func clearNode() {self._node = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    enum TypeEnum: SwiftProtobuf.Enum {
      typealias RawValue = Int

      /// [title="flower"]
      case equals // = 0

      /// [title~="flower"]
      case containsWord // = 1

      /// [title|="flower"]
      case startsWithWord // = 2

      /// [title^="flower"]
      case startsWithSubstring // = 3

      /// [title$="flower"]
      case endsWithSubstring // = 4

      /// [title*="flower"]
      case containsSubstring // = 5

      /// [title]
      case hasAttribute // = 6
      case UNRECOGNIZED(Int)

      init() {
        self = .equals
      }

      init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .equals
        case 1: self = .containsWord
        case 2: self = .startsWithWord
        case 3: self = .startsWithSubstring
        case 4: self = .endsWithSubstring
        case 5: self = .containsSubstring
        case 6: self = .hasAttribute
        default: self = .UNRECOGNIZED(rawValue)
        }
      }

      var rawValue: Int {
        switch self {
        case .equals: return 0
        case .containsWord: return 1
        case .startsWithWord: return 2
        case .startsWithSubstring: return 3
        case .endsWithSubstring: return 4
        case .containsSubstring: return 5
        case .hasAttribute: return 6
        case .UNRECOGNIZED(let i): return i
        }
      }

    }

    init() {}

    fileprivate var _attribute: Valdi_NodeAttribute?
    fileprivate var _node: Valdi_StyleNode?
  }

  struct NthChildRule {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var n: Int32 = 0

    var offset: Int32 = 0

    var node: Valdi_StyleNode {
      get {return _node ?? Valdi_StyleNode()}
      set {_node = newValue}
    }
    /// Returns true if `node` has been explicitly set.
    var hasNode: Bool {return self._node != nil}
    /// Clears the value of `node`. Subsequent reads from it will return its default value.
    mutating func clearNode() {self._node = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _node: Valdi_StyleNode?
  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

#if swift(>=4.2)

extension Valdi_CSSRuleIndex.AttributeRule.TypeEnum: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [Valdi_CSSRuleIndex.AttributeRule.TypeEnum] = [
    .equals,
    .containsWord,
    .startsWithWord,
    .startsWithSubstring,
    .endsWithSubstring,
    .containsSubstring,
    .hasAttribute
  ]
}

#endif  // swift(>=4.2)

#if swift(>=5.5) && canImport(_Concurrency)
extension Valdi_NodeAttribute: @unchecked Sendable {}
extension Valdi_NodeAttribute.TypeEnum: @unchecked Sendable {}
extension Valdi_DownloadableModuleArtifact: @unchecked Sendable {}
extension Valdi_DownloadableModuleArtifactSignatures: @unchecked Sendable {}
extension Valdi_DownloadableModuleAssets: @unchecked Sendable {}
extension Valdi_DownloadableModuleManifest: @unchecked Sendable {}
extension Valdi_DaemonAwakeMessage: @unchecked Sendable {}
extension Valdi_ClientAwakeMessage: @unchecked Sendable {}
extension Valdi_DaemonServiceDiscoveryPayload: @unchecked Sendable {}
extension Valdi_DaemonServiceDiscoveryPayload.OneOf_Message: @unchecked Sendable {}
extension Valdi_StyleNode: @unchecked Sendable {}
extension Valdi_StyleDeclaration: @unchecked Sendable {}
extension Valdi_NamedStyleNode: @unchecked Sendable {}
extension Valdi_CSSRuleIndex: @unchecked Sendable {}
extension Valdi_CSSRuleIndex.AttributeRule: @unchecked Sendable {}
extension Valdi_CSSRuleIndex.AttributeRule.TypeEnum: @unchecked Sendable {}
extension Valdi_CSSRuleIndex.NthChildRule: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "Valdi"

extension Valdi_NodeAttribute: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".NodeAttribute"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "type"),
    2: .same(proto: "name"),
    3: .standard(proto: "str_value"),
    4: .standard(proto: "int_value"),
    5: .standard(proto: "double_value")
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.strValue) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.intValue) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.doubleValue) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.type != .nodeAttributeTypeString {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.strValue.isEmpty {
      try visitor.visitSingularStringField(value: self.strValue, fieldNumber: 3)
    }
    if self.intValue != 0 {
      try visitor.visitSingularInt64Field(value: self.intValue, fieldNumber: 4)
    }
    if self.doubleValue != 0 {
      try visitor.visitSingularDoubleField(value: self.doubleValue, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Valdi_NodeAttribute, rhs: Valdi_NodeAttribute) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.name != rhs.name {return false}
    if lhs.strValue != rhs.strValue {return false}
    if lhs.intValue != rhs.intValue {return false}
    if lhs.doubleValue != rhs.doubleValue {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Valdi_NodeAttribute.TypeEnum: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "NODE_ATTRIBUTE_TYPE_STRING"),
    1: .same(proto: "NODE_ATTRIBUTE_TYPE_INT"),
    2: .same(proto: "NODE_ATTRIBUTE_TYPE_DOUBLE")
  ]
}

extension Valdi_DownloadableModuleArtifact: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DownloadableModuleArtifact"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "url"),
    2: .same(proto: "sha256Digest")
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.sha256Digest) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 1)
    }
    if !self.sha256Digest.isEmpty {
      try visitor.visitSingularBytesField(value: self.sha256Digest, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Valdi_DownloadableModuleArtifact, rhs: Valdi_DownloadableModuleArtifact) -> Bool {
    if lhs.url != rhs.url {return false}
    if lhs.sha256Digest != rhs.sha256Digest {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Valdi_DownloadableModuleArtifactSignatures: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DownloadableModuleArtifact"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "artifacts"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.artifacts) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.artifacts.isEmpty {
        try visitor.visitRepeatedMessageField(value: self.artifacts, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Valdi_DownloadableModuleArtifactSignatures, rhs: Valdi_DownloadableModuleArtifactSignatures) -> Bool {
    if lhs.artifacts != rhs.artifacts {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}


extension Valdi_DownloadableModuleAssets: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DownloadableModuleAssets"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "artifact"),
    3: .standard(proto: "device_density")
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._artifact) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.deviceDensity) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._artifact {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.deviceDensity != 0 {
      try visitor.visitSingularDoubleField(value: self.deviceDensity, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Valdi_DownloadableModuleAssets, rhs: Valdi_DownloadableModuleAssets) -> Bool {
    if lhs._artifact != rhs._artifact {return false}
    if lhs.deviceDensity != rhs.deviceDensity {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Valdi_DownloadableModuleManifest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DownloadableModuleManifest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "name"),
    2: .same(proto: "artifact"),
    3: .same(proto: "assets"),
    4: .same(proto: "dependencies"),
    5: .standard(proto: "has_local_assets")
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._artifact) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.assets) }()
      case 4: try { try decoder.decodeRepeatedStringField(value: &self.dependencies) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.hasLocalAssets_p) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    try { if let v = self._artifact {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.assets.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.assets, fieldNumber: 3)
    }
    if !self.dependencies.isEmpty {
      try visitor.visitRepeatedStringField(value: self.dependencies, fieldNumber: 4)
    }
    if self.hasLocalAssets_p != false {
      try visitor.visitSingularBoolField(value: self.hasLocalAssets_p, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Valdi_DownloadableModuleManifest, rhs: Valdi_DownloadableModuleManifest) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs._artifact != rhs._artifact {return false}
    if lhs.assets != rhs.assets {return false}
    if lhs.dependencies != rhs.dependencies {return false}
    if lhs.hasLocalAssets_p != rhs.hasLocalAssets_p {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Valdi_DaemonAwakeMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DaemonAwakeMessage"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    16: .standard(proto: "device_ids"),
    17: .same(proto: "usernames"),
    1: .standard(proto: "service_addresses"),
    2: .standard(proto: "service_port"),
    3: .standard(proto: "process_id")
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.serviceAddresses) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.servicePort) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.processID) }()
      case 16: try { try decoder.decodeRepeatedStringField(value: &self.deviceIds) }()
      case 17: try { try decoder.decodeRepeatedStringField(value: &self.usernames) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.serviceAddresses.isEmpty {
      try visitor.visitRepeatedStringField(value: self.serviceAddresses, fieldNumber: 1)
    }
    if self.servicePort != 0 {
      try visitor.visitSingularInt32Field(value: self.servicePort, fieldNumber: 2)
    }
    if !self.processID.isEmpty {
      try visitor.visitSingularStringField(value: self.processID, fieldNumber: 3)
    }
    if !self.deviceIds.isEmpty {
      try visitor.visitRepeatedStringField(value: self.deviceIds, fieldNumber: 16)
    }
    if !self.usernames.isEmpty {
      try visitor.visitRepeatedStringField(value: self.usernames, fieldNumber: 17)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Valdi_DaemonAwakeMessage, rhs: Valdi_DaemonAwakeMessage) -> Bool {
    if lhs.deviceIds != rhs.deviceIds {return false}
    if lhs.usernames != rhs.usernames {return false}
    if lhs.serviceAddresses != rhs.serviceAddresses {return false}
    if lhs.servicePort != rhs.servicePort {return false}
    if lhs.processID != rhs.processID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Valdi_ClientAwakeMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ClientAwakeMessage"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "device_id"),
    2: .same(proto: "username")
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.username) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 1)
    }
    if !self.username.isEmpty {
      try visitor.visitSingularStringField(value: self.username, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Valdi_ClientAwakeMessage, rhs: Valdi_ClientAwakeMessage) -> Bool {
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.username != rhs.username {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Valdi_DaemonServiceDiscoveryPayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DaemonServiceDiscoveryPayload"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "daemon_awake_message"),
    2: .standard(proto: "client_awake_message")
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Valdi_DaemonAwakeMessage?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .daemonAwakeMessage(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .daemonAwakeMessage(v)
        }
      }()
      case 2: try {
        var v: Valdi_ClientAwakeMessage?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .clientAwakeMessage(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .clientAwakeMessage(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.message {
    case .daemonAwakeMessage?: try {
      guard case .daemonAwakeMessage(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .clientAwakeMessage?: try {
      guard case .clientAwakeMessage(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Valdi_DaemonServiceDiscoveryPayload, rhs: Valdi_DaemonServiceDiscoveryPayload) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Valdi_StyleNode: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".StyleNode"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "styles"),
    2: .same(proto: "ruleIndex")
  ]

  fileprivate class _StorageClass {
    var _styles: [Valdi_StyleDeclaration] = []
    var _ruleIndex: Valdi_CSSRuleIndex?

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _styles = source._styles
      _ruleIndex = source._ruleIndex
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeRepeatedMessageField(value: &_storage._styles) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._ruleIndex) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._styles.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._styles, fieldNumber: 1)
      }
      try { if let v = _storage._ruleIndex {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Valdi_StyleNode, rhs: Valdi_StyleNode) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._styles != rhs_storage._styles {return false}
        if _storage._ruleIndex != rhs_storage._ruleIndex {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Valdi_StyleDeclaration: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".StyleDeclaration"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "attribute"),
    2: .same(proto: "priority"),
    3: .same(proto: "order"),
    4: .same(proto: "id")
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._attribute) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.priority) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.order) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.id) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._attribute {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.priority != 0 {
      try visitor.visitSingularInt32Field(value: self.priority, fieldNumber: 2)
    }
    if self.order != 0 {
      try visitor.visitSingularInt32Field(value: self.order, fieldNumber: 3)
    }
    if self.id != 0 {
      try visitor.visitSingularInt32Field(value: self.id, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Valdi_StyleDeclaration, rhs: Valdi_StyleDeclaration) -> Bool {
    if lhs._attribute != rhs._attribute {return false}
    if lhs.priority != rhs.priority {return false}
    if lhs.order != rhs.order {return false}
    if lhs.id != rhs.id {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Valdi_NamedStyleNode: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".NamedStyleNode"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "name"),
    2: .same(proto: "node")
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._node) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    try { if let v = self._node {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Valdi_NamedStyleNode, rhs: Valdi_NamedStyleNode) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs._node != rhs._node {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Valdi_CSSRuleIndex: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CSSRuleIndex"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "id_rules"),
    2: .standard(proto: "class_rules"),
    3: .standard(proto: "tag_rules"),
    4: .standard(proto: "attribute_rules"),
    5: .standard(proto: "first_child_rule"),
    6: .standard(proto: "last_child_rule"),
    7: .standard(proto: "nth_child_rules"),
    8: .standard(proto: "ancestor_rules"),
    9: .standard(proto: "direct_parent_rules")
  ]

  fileprivate class _StorageClass {
    var _idRules: [Valdi_NamedStyleNode] = []
    var _classRules: [Valdi_NamedStyleNode] = []
    var _tagRules: [Valdi_NamedStyleNode] = []
    var _attributeRules: [Valdi_CSSRuleIndex.AttributeRule] = []
    var _firstChildRule: Valdi_StyleNode?
    var _lastChildRule: Valdi_StyleNode?
    var _nthChildRules: [Valdi_CSSRuleIndex.NthChildRule] = []
    var _ancestorRules: Valdi_CSSRuleIndex?
    var _directParentRules: Valdi_CSSRuleIndex?

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _idRules = source._idRules
      _classRules = source._classRules
      _tagRules = source._tagRules
      _attributeRules = source._attributeRules
      _firstChildRule = source._firstChildRule
      _lastChildRule = source._lastChildRule
      _nthChildRules = source._nthChildRules
      _ancestorRules = source._ancestorRules
      _directParentRules = source._directParentRules
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeRepeatedMessageField(value: &_storage._idRules) }()
        case 2: try { try decoder.decodeRepeatedMessageField(value: &_storage._classRules) }()
        case 3: try { try decoder.decodeRepeatedMessageField(value: &_storage._tagRules) }()
        case 4: try { try decoder.decodeRepeatedMessageField(value: &_storage._attributeRules) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._firstChildRule) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._lastChildRule) }()
        case 7: try { try decoder.decodeRepeatedMessageField(value: &_storage._nthChildRules) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._ancestorRules) }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._directParentRules) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._idRules.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._idRules, fieldNumber: 1)
      }
      if !_storage._classRules.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._classRules, fieldNumber: 2)
      }
      if !_storage._tagRules.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._tagRules, fieldNumber: 3)
      }
      if !_storage._attributeRules.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._attributeRules, fieldNumber: 4)
      }
      try { if let v = _storage._firstChildRule {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._lastChildRule {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      if !_storage._nthChildRules.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._nthChildRules, fieldNumber: 7)
      }
      try { if let v = _storage._ancestorRules {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._directParentRules {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Valdi_CSSRuleIndex, rhs: Valdi_CSSRuleIndex) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._idRules != rhs_storage._idRules {return false}
        if _storage._classRules != rhs_storage._classRules {return false}
        if _storage._tagRules != rhs_storage._tagRules {return false}
        if _storage._attributeRules != rhs_storage._attributeRules {return false}
        if _storage._firstChildRule != rhs_storage._firstChildRule {return false}
        if _storage._lastChildRule != rhs_storage._lastChildRule {return false}
        if _storage._nthChildRules != rhs_storage._nthChildRules {return false}
        if _storage._ancestorRules != rhs_storage._ancestorRules {return false}
        if _storage._directParentRules != rhs_storage._directParentRules {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Valdi_CSSRuleIndex.AttributeRule: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Valdi_CSSRuleIndex.protoMessageName + ".AttributeRule"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "type"),
    2: .same(proto: "attribute"),
    3: .same(proto: "node")
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._attribute) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._node) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.type != .equals {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 1)
    }
    try { if let v = self._attribute {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._node {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Valdi_CSSRuleIndex.AttributeRule, rhs: Valdi_CSSRuleIndex.AttributeRule) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs._attribute != rhs._attribute {return false}
    if lhs._node != rhs._node {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Valdi_CSSRuleIndex.AttributeRule.TypeEnum: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "EQUALS"),
    1: .same(proto: "CONTAINS_WORD"),
    2: .same(proto: "STARTS_WITH_WORD"),
    3: .same(proto: "STARTS_WITH_SUBSTRING"),
    4: .same(proto: "ENDS_WITH_SUBSTRING"),
    5: .same(proto: "CONTAINS_SUBSTRING"),
    6: .same(proto: "HAS_ATTRIBUTE")
  ]
}

extension Valdi_CSSRuleIndex.NthChildRule: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Valdi_CSSRuleIndex.protoMessageName + ".NthChildRule"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "n"),
    2: .same(proto: "offset"),
    3: .same(proto: "node")
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.n) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.offset) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._node) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.n != 0 {
      try visitor.visitSingularInt32Field(value: self.n, fieldNumber: 1)
    }
    if self.offset != 0 {
      try visitor.visitSingularInt32Field(value: self.offset, fieldNumber: 2)
    }
    try { if let v = self._node {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Valdi_CSSRuleIndex.NthChildRule, rhs: Valdi_CSSRuleIndex.NthChildRule) -> Bool {
    if lhs.n != rhs.n {return false}
    if lhs.offset != rhs.offset {return false}
    if lhs._node != rhs._node {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
