#import <Foundation/Foundation.h>

/**
 * Generated from type 'FontStyle' at 'valdi_example/Drawing.d.ts' by the Valdi compiler.
 * Please do not edit this file directly.
 */
typedef NSString* _Nonnull SCValdiDrawingFontStyle NS_STRING_ENUM;
typedef NSString* _Nullable SCValdiDrawingFontStyle_Nullable NS_STRING_ENUM;

FOUNDATION_EXPORT SCValdiDrawingFontStyle SCValdiDrawingFontStyleNORMAL;
FOUNDATION_EXPORT SCValdiDrawingFontStyle SCValdiDrawingFontStyleITALIC;
