#import "valdi_core/SCValdiMarshallable.h"
#import "valdi_core/SCValdiMarshallableObject.h"
#import "valdi_core/SCValdiMarshaller.h"
#import <Foundation/Foundation.h>

@class SCValdiDrawingFontSpecs;

/**
 * Generated from 'src/Drawing.d.ts' by the Valdi compiler.
 * Please do not edit this file directly.
 */
@interface SCValdiDrawingFontSpecs : SCValdiMarshallableObject

@property (copy, nonatomic) NSString* _Nonnull font;

@property (strong, nonatomic) NSNumber* _Nullable lineHeight;

- (instancetype _Nonnull)initWithFont:(NSString* _Nonnull)font;

@end
