#import "valdi_core/SCValdiMarshallable.h"
#import "valdi_core/SCValdiMarshallableObject.h"
#import "valdi_core/SCValdiMarshaller.h"
#import <Foundation/Foundation.h>

@class SCValdiDrawingSize;

/**
 * Generated from 'src/Drawing.d.ts' by the Valdi compiler.
 * Please do not edit this file directly.
 */
@interface SCValdiDrawingSize : SCValdiMarshallableObject

@property (assign, nonatomic) double width;

@property (assign, nonatomic) double height;

- (instancetype _Nonnull)initWithWidth:(double)width height:(double)height;

@end
