#import <Foundation/Foundation.h>

/**
 * Generated from type 'FontWeight' at 'valdi_example/Drawing.d.ts' by the Valdi compiler.
 * Please do not edit this file directly.
 */
typedef NSString* _Nonnull SCValdiDrawingFontWeight NS_STRING_ENUM;
typedef NSString* _Nullable SCValdiDrawingFontWeight_Nullable NS_STRING_ENUM;

FOUNDATION_EXPORT SCValdiDrawingFontWeight SCValdiDrawingFontWeightLIGHT;
FOUNDATION_EXPORT SCValdiDrawingFontWeight SCValdiDrawingFontWeightNORMAL;
FOUNDATION_EXPORT SCValdiDrawingFontWeight SCValdiDrawingFontWeightMEDIUM;
FOUNDATION_EXPORT SCValdiDrawingFontWeight SCValdiDrawingFontWeightDEMI_BOLD;
FOUNDATION_EXPORT SCValdiDrawingFontWeight SCValdiDrawingFontWeightBOLD;
FOUNDATION_EXPORT SCValdiDrawingFontWeight SCValdiDrawingFontWeightBLACK;
