#import "valdi/ios/NativeModules/Drawing/SCValdiDrawingFont.h"
#import "valdi/ios/NativeModules/Drawing/SCValdiDrawingFontSpecs.h"
#import "valdi/ios/NativeModules/Drawing/SCValdiDrawingFontStyle.h"
#import "valdi/ios/NativeModules/Drawing/SCValdiDrawingFontWeight.h"
#import "valdi_core/SCValdiMarshallable.h"
#import "valdi_core/SCValdiMarshaller.h"
#import <Foundation/Foundation.h>

@protocol SCValdiDrawingModule;

/**
 * Generated from type 'DrawingModule' at 'valdi_example/Drawing.d.ts' by the Valdi compiler.
 * Please do not edit this file directly.
 */
@protocol SCValdiDrawingModule <NSObject, SCValdiMarshallable>

/**
 * NOTE: This method can be called from any thread.
 */
@required
- (id<SCValdiDrawingFont> _Nullable)getFontWithSpecs:(SCValdiDrawingFontSpecs* _Nonnull)specs;

/**
 * NOTE: This method can be called from any thread.
 */
@required
- (BOOL)isFontRegisteredWithFontName:(NSString* _Nonnull)fontName;

/**
 * NOTE: This method can be called from any thread.
 */
@required
- (void)registerFontWithFontName:(NSString* _Nonnull)fontName
                          weight:(SCValdiDrawingFontWeight _Nonnull)weight
                           style:(SCValdiDrawingFontStyle _Nonnull)style
                        filename:(NSString* _Nonnull)filename;

@end

/**
 * Marshall the instance into the given SCValdiMarshaller.
 */
FOUNDATION_EXPORT NSInteger SCValdiDrawingModuleMarshall(SCValdiMarshallerRef _Nonnull marshaller,
                                                         id<SCValdiDrawingModule> _Nonnull instance);