#import "valdi/ios/NativeModules/Drawing/SCValdiDrawingSize.h"
#import "valdi_core/SCValdiMarshallable.h"
#import "valdi_core/SCValdiMarshaller.h"
#import <Foundation/Foundation.h>

@protocol SCValdiDrawingFont;

/**
 * Generated from 'src/Drawing.d.ts' by the Valdi compiler.
 * Please do not edit this file directly.
 */
@protocol SCValdiDrawingFont <NSObject, SCValdiMarshallable>

/**
 * NOTE: This method can be called from any thread.
 */
@required
- (SCValdiDrawingSize* _Nonnull)measureTextWithText:(NSString* _Nonnull)text
                                           maxWidth:(NSNumber* _Nullable)maxWidth
                                          maxHeight:(NSNumber* _Nullable)maxHeight
                                           maxLines:(NSNumber* _Nullable)maxLines;

@end

/**
 * Marshall the instance into the given SCValdiMarshaller.
 */
FOUNDATION_EXPORT NSInteger SCValdiDrawingFontMarshall(SCValdiMarshallerRef _Nonnull marshaller,
                                                       id<SCValdiDrawingFont> _Nonnull instance);
