// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include <functional>

namespace snap::valdi_core {

enum class AnimationType : int {
    Linear = 0,
    EaseIn = 1,
    EaseOut = 2,
    EaseInOut = 3,
};

constexpr const char* to_string(AnimationType e) noexcept {
    constexpr const char* names[] = {
        "linear",
        "easeIn",
        "easeOut",
        "easeInOut",
    };
    return names[static_cast<int>(e)];
}

} // namespace snap::valdi_core

namespace std {

template <>
struct hash<::snap::valdi_core::AnimationType> {
    size_t operator()(::snap::valdi_core::AnimationType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

} // namespace std
