// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "valdi_core/cpp/Utils/Value.hpp"

namespace snap::valdi_core {

class Animator {
public:
    virtual ~Animator() = default;

    /** The Value is a wrapped completion callback */
    virtual void flushAnimations(const Valdi::Value & completion) = 0;

    /** Cancel an animation */
    virtual void cancel() = 0;
};

} // namespace snap::valdi_core
