// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "valdi_core/cpp/Utils/StringBox.hpp"
#include "valdi_core/cpp/Utils/Value.hpp"
#include <cstdint>
#include <memory>

namespace snap::valdi_core {

class AssetLoadObserver;
enum class AssetOutputType;

/** Represents a loadable asset like an Image */
class Asset {
public:
    virtual ~Asset() = default;

    /** Return a string that uniquely identifies this asset */
    virtual Valdi::StringBox getIdentifier() = 0;

    /**
     * Measure the width that should be used for this asset
     * given a max width and height.
     */
    virtual double measureWidth(double maxWidth, double maxHeight) = 0;

    /**
     * Measure the height that should be used for this asset
     * given a max width and height.
     */
    virtual double measureHeight(double maxWidth, double maxHeight) = 0;

    /**
     * Append a load observer, which will be notified
     * when the asset is loaded.
     */
    virtual void addLoadObserver(const /*not-null*/ std::shared_ptr<AssetLoadObserver> & observer, AssetOutputType outputType, int32_t preferredWidth, int32_t preferredHeight, const Valdi::Value & filter) = 0;

    /** Remove a previously registered load observer */
    virtual void removeLoadObserver(const /*not-null*/ std::shared_ptr<AssetLoadObserver> & observer) = 0;

    /** Update the preferred width and height of a previously registered load observer */
    virtual void updateLoadObserverPreferredSize(const /*not-null*/ std::shared_ptr<AssetLoadObserver> & observer, int32_t preferredWidth, int32_t preferredHeight) = 0;
};

} // namespace snap::valdi_core
