// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "valdi_core/cpp/Utils/StringBox.hpp"
#include "valdi_core/cpp/Utils/Value.hpp"
#include <memory>
#include <optional>

namespace snap::valdi_core {

class Asset;

class AssetLoadObserver {
public:
    virtual ~AssetLoadObserver() = default;

    virtual void onLoad(const /*not-null*/ std::shared_ptr<Asset> & asset, const Valdi::Value & loadedAsset, const std::optional<Valdi::StringBox> & error) = 0;
};

} // namespace snap::valdi_core
