// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include <functional>

namespace snap::valdi_core {

enum class AssetOutputType : int {
    Bytes = 0,
    ImageIOS = 1,
    ImageAndroid = 2,
    ImageSnapDrawing = 3,
    VideoIOS = 4,
    VideoAndroid = 5,
    Lottie = 6,
    Dummy = 7,
};

constexpr const char* to_string(AssetOutputType e) noexcept {
    constexpr const char* names[] = {
        "bytes",
        "imageIOS",
        "imageAndroid",
        "imageSnapDrawing",
        "videoIOS",
        "videoAndroid",
        "lottie",
        "dummy",
    };
    return names[static_cast<int>(e)];
}

} // namespace snap::valdi_core

namespace std {

template <>
struct hash<::snap::valdi_core::AssetOutputType> {
    size_t operator()(::snap::valdi_core::AssetOutputType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

} // namespace std
