// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include <functional>

namespace snap::valdi_core {

enum class AttributeType : int {
    String = 0,
    Double = 1,
    Int = 2,
    Boolean = 3,
    Color = 4,
    Untyped = 5,
};

constexpr const char* to_string(AttributeType e) noexcept {
    constexpr const char* names[] = {
        "string",
        "double",
        "int",
        "boolean",
        "color",
        "untyped",
    };
    return names[static_cast<int>(e)];
}

} // namespace snap::valdi_core

namespace std {

template <>
struct hash<::snap::valdi_core::AttributeType> {
    size_t operator()(::snap::valdi_core::AttributeType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

} // namespace std
