// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

namespace snap::valdi_core {

class Cancelable {
public:
    virtual ~Cancelable() = default;

    virtual void cancel() = 0;
};

} // namespace snap::valdi_core
