// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "valdi_core/AttributeType.hpp"
#include "valdi_core/cpp/Utils/StringBox.hpp"
#include <utility>

namespace snap::valdi_core {

struct CompositeAttributePart final {
    Valdi::StringBox attribute;
    AttributeType type;
    bool optional;
    bool invalidateLayoutOnChange;

    CompositeAttributePart(Valdi::StringBox attribute_,
                           AttributeType type_,
                           bool optional_,
                           bool invalidateLayoutOnChange_)
    : attribute(std::move(attribute_))
    , type(std::move(type_))
    , optional(std::move(optional_))
    , invalidateLayoutOnChange(std::move(invalidateLayoutOnChange_))
    {}
};

} // namespace snap::valdi_core
