// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "valdi_core/cpp/Utils/Bytes.hpp"
#include "valdi_core/cpp/Utils/Value.hpp"
#include <cstdint>
#include <optional>
#include <utility>

namespace snap::valdi_core {

struct HTTPResponse final {
    int32_t statusCode;
    Valdi::Value headers;
    std::optional<Valdi::BytesView> body;

    HTTPResponse(int32_t statusCode_,
                 Valdi::Value headers_,
                 std::optional<Valdi::BytesView> body_)
    : statusCode(std::move(statusCode_))
    , headers(std::move(headers_))
    , body(std::move(body_))
    {}
};

} // namespace snap::valdi_core
