// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include <string>

namespace snap::valdi_core {

struct HTTPResponse;

class HTTPRequestManagerCompletion {
public:
    virtual ~HTTPRequestManagerCompletion() = default;

    virtual void onComplete(const HTTPResponse & response) = 0;

    virtual void onFail(const std::string & error) = 0;
};

} // namespace snap::valdi_core
