// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include <memory>

namespace snap::valdi_core {

class Cancelable;
class HTTPRequestManagerCompletion;
struct HTTPRequest;

class HTTPRequestManager {
public:
    virtual ~HTTPRequestManager() = default;

    virtual /*not-null*/ std::shared_ptr<Cancelable> performRequest(const HTTPRequest & request, const /*not-null*/ std::shared_ptr<HTTPRequestManagerCompletion> & completion) = 0;
};

} // namespace snap::valdi_core
