// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "valdi_core/cpp/Utils/Bytes.hpp"
#include "valdi_core/cpp/Utils/StringBox.hpp"
#include "valdi_core/cpp/Utils/Value.hpp"
#include <cstdint>
#include <optional>
#include <utility>

namespace snap::valdi_core {

struct HTTPRequest final {
    Valdi::StringBox url;
    Valdi::StringBox method;
    Valdi::Value headers;
    std::optional<Valdi::BytesView> body;
    /** Between 0 being lowest, to 10 being maximum */
    int32_t priority;

    HTTPRequest(Valdi::StringBox url_,
                Valdi::StringBox method_,
                Valdi::Value headers_,
                std::optional<Valdi::BytesView> body_,
                int32_t priority_)
    : url(std::move(url_))
    , method(std::move(method_))
    , headers(std::move(headers_))
    , body(std::move(body_))
    , priority(std::move(priority_))
    {}
};

} // namespace snap::valdi_core
