// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include <functional>

namespace snap::valdi_core {

enum class JavaScriptEngineType : int {
    Auto = 0,
    QuickJS = 1,
    JSCore = 2,
    V8 = 3,
    Hermes = 4,
};

constexpr const char* to_string(JavaScriptEngineType e) noexcept {
    constexpr const char* names[] = {
        "Auto",
        "QuickJS",
        "JSCore",
        "V8",
        "Hermes",
    };
    return names[static_cast<int>(e)];
}

} // namespace snap::valdi_core

namespace std {

template <>
struct hash<::snap::valdi_core::JavaScriptEngineType> {
    size_t operator()(::snap::valdi_core::JavaScriptEngineType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

} // namespace std
