// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "valdi_core/cpp/Utils/Value.hpp"
#include <memory>
#include <vector>

namespace snap::valdi_core {

class ModuleFactory;

/**
 * The ModuleFactoriesProvider will be invoked when the RuntimeManager is initialized
 * to provide additional built-in Modules that will be exposed to the JS runtime environment.
 */
class ModuleFactoriesProvider {
public:
    virtual ~ModuleFactoriesProvider() = default;

    /** Create and return the module factories that will be exposed to the JS runtime environment. */
    virtual std::vector</*not-null*/ std::shared_ptr<ModuleFactory>> createModuleFactories(const Valdi::Value & runtimeManager) = 0;
};

} // namespace snap::valdi_core
