// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "valdi_core/cpp/Utils/StringBox.hpp"
#include "valdi_core/cpp/Utils/Value.hpp"

namespace snap::valdi_core {

class ModuleFactory {
public:
    virtual ~ModuleFactory() = default;

    /**
     * Return the path of the module, which represents its path
     * when imported from TypeScript.
     */
    virtual Valdi::StringBox getModulePath() = 0;

    /**
     * Returns the module exports object that should be returned to
     * TypeScript when the module is imported.
     */
    virtual Valdi::Value loadModule() = 0;
};

} // namespace snap::valdi_core
