// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include <functional>

namespace snap::valdi_core {

enum class Platform : int {
    Ios = 0,
    Android = 1,
    Skia = 2,
};

constexpr const char* to_string(Platform e) noexcept {
    constexpr const char* names[] = {
        "ios",
        "android",
        "skia",
    };
    return names[static_cast<int>(e)];
}

} // namespace snap::valdi_core

namespace std {

template <>
struct hash<::snap::valdi_core::Platform> {
    size_t operator()(::snap::valdi_core::Platform type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

} // namespace std
