// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "valdi_core/Cancelable.hpp"

namespace djinni_generated_client::valdi_core {

class NativeCancelable final : ::djinni::JniInterface<::snap::valdi_core::Cancelable, NativeCancelable> {
public:
    using CppType = std::shared_ptr<::snap::valdi_core::Cancelable>;
    using CppOptType = std::shared_ptr<::snap::valdi_core::Cancelable>;
    using JniType = jobject;

    using Boxed = NativeCancelable;

    ~NativeCancelable();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeCancelable>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeCancelable>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeCancelable();
    friend ::djinni::JniClass<NativeCancelable>;
    friend ::djinni::JniInterface<::snap::valdi_core::Cancelable, NativeCancelable>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::snap::valdi_core::Cancelable
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void cancel() override;

    private:
        friend ::djinni::JniInterface<::snap::valdi_core::Cancelable, ::djinni_generated_client::valdi_core::NativeCancelable>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/snapchat/client/valdi_core/Cancelable") };
    const jmethodID method_cancel { ::djinni::jniGetMethodID(clazz.get(), "cancel", "()V") };
};

} // namespace djinni_generated_client::valdi_core
