// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "valdi_core/CompositeAttributePart.hpp"

namespace djinni_generated_client::valdi_core {

class NativeCompositeAttributePart final {
public:
    using CppType = ::snap::valdi_core::CompositeAttributePart;
    using JniType = jobject;

    using Boxed = NativeCompositeAttributePart;

    ~NativeCompositeAttributePart();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeCompositeAttributePart();
    friend ::djinni::JniClass<NativeCompositeAttributePart>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/snapchat/client/valdi_core/CompositeAttributePart") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Lcom/snapchat/client/valdi_core/AttributeType;ZZ)V") };
    const jfieldID field_mAttribute { ::djinni::jniGetFieldID(clazz.get(), "mAttribute", "Ljava/lang/String;") };
    const jfieldID field_mType { ::djinni::jniGetFieldID(clazz.get(), "mType", "Lcom/snapchat/client/valdi_core/AttributeType;") };
    const jfieldID field_mOptional { ::djinni::jniGetFieldID(clazz.get(), "mOptional", "Z") };
    const jfieldID field_mInvalidateLayoutOnChange { ::djinni::jniGetFieldID(clazz.get(), "mInvalidateLayoutOnChange", "Z") };
};

} // namespace djinni_generated_client::valdi_core
