// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#include "valdi_core/NativeCompositeAttributePart.hpp"  // my header
#include "djinni/jni/Marshal.hpp"
#include "valdi_core/NativeAttributeType.hpp"
#include "valdi_core/bindings/InternedStringTranslator_jni.hpp"

namespace djinni_generated_client::valdi_core {

NativeCompositeAttributePart::NativeCompositeAttributePart() = default;

NativeCompositeAttributePart::~NativeCompositeAttributePart() = default;

auto NativeCompositeAttributePart::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeCompositeAttributePart>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(ValdiAndroid::InternedStringTranslator::fromCpp(jniEnv, c.attribute)),
                                                           ::djinni::get(::djinni_generated_client::valdi_core::NativeAttributeType::fromCpp(jniEnv, c.type)),
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.optional)),
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.invalidateLayoutOnChange)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeCompositeAttributePart::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 5);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeCompositeAttributePart>::get();
    return {ValdiAndroid::InternedStringTranslator::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mAttribute)),
            ::djinni_generated_client::valdi_core::NativeAttributeType::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mType)),
            ::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mOptional)),
            ::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mInvalidateLayoutOnChange))};
}

} // namespace djinni_generated_client::valdi_core
