// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#include "valdi_core/NativeHTTPRequestManager.hpp"  // my header
#include "utils/debugging/DjinniPrologue.hpp"
#include "valdi_core/NativeCancelable.hpp"
#include "valdi_core/NativeHTTPRequest.hpp"
#include "valdi_core/NativeHTTPRequestManagerCompletion.hpp"

namespace djinni_generated_client::valdi_core {

NativeHTTPRequestManager::NativeHTTPRequestManager() : ::djinni::JniInterface<::snap::valdi_core::HTTPRequestManager, NativeHTTPRequestManager>() {}

NativeHTTPRequestManager::~NativeHTTPRequestManager() = default;

NativeHTTPRequestManager::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeHTTPRequestManager::JavaProxy::~JavaProxy() = default;

/*not-null*/ std::shared_ptr<::snap::valdi_core::Cancelable> NativeHTTPRequestManager::JavaProxy::performRequest(const ::snap::valdi_core::HTTPRequest & c_request, const /*not-null*/ std::shared_ptr<::snap::valdi_core::HTTPRequestManagerCompletion> & c_completion) {
    DJINNI_FUNCTION_PROLOGUE("HTTPRequestManager.performRequest");
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated_client::valdi_core::NativeHTTPRequestManager>::get();
    auto jret = jniEnv->CallObjectMethod(Handle::get().get(), data.method_performRequest,
                                         ::djinni::get(::djinni_generated_client::valdi_core::NativeHTTPRequest::fromCpp(jniEnv, c_request)),
                                         ::djinni::get(::djinni_generated_client::valdi_core::NativeHTTPRequestManagerCompletion::fromCpp(jniEnv, c_completion)));
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni_generated_client::valdi_core::NativeCancelable::toCpp(jniEnv, jret);
}

} // namespace djinni_generated_client::valdi_core
