// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "valdi_core/HTTPRequestManagerCompletion.hpp"

namespace djinni_generated_client::valdi_core {

class NativeHTTPRequestManagerCompletion final : ::djinni::JniInterface<::snap::valdi_core::HTTPRequestManagerCompletion, NativeHTTPRequestManagerCompletion> {
public:
    using CppType = std::shared_ptr<::snap::valdi_core::HTTPRequestManagerCompletion>;
    using CppOptType = std::shared_ptr<::snap::valdi_core::HTTPRequestManagerCompletion>;
    using JniType = jobject;

    using Boxed = NativeHTTPRequestManagerCompletion;

    ~NativeHTTPRequestManagerCompletion();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeHTTPRequestManagerCompletion>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeHTTPRequestManagerCompletion>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeHTTPRequestManagerCompletion();
    friend ::djinni::JniClass<NativeHTTPRequestManagerCompletion>;
    friend ::djinni::JniInterface<::snap::valdi_core::HTTPRequestManagerCompletion, NativeHTTPRequestManagerCompletion>;

};

} // namespace djinni_generated_client::valdi_core
