// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "valdi_core/AttributeType.hpp"

namespace djinni_generated_client::valdi_core {

class NativeAttributeType final : ::djinni::JniEnum {
public:
    using CppType = ::snap::valdi_core::AttributeType;
    using JniType = jobject;

    using Boxed = NativeAttributeType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeAttributeType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeAttributeType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeAttributeType() : JniEnum("com/snapchat/client/valdi_core/AttributeType") {}
    friend ::djinni::JniClass<NativeAttributeType>;
};

} // namespace djinni_generated_client::valdi_core
