// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "valdi_core/AnimationType.hpp"

namespace djinni_generated_client::valdi_core {

class NativeAnimationType final : ::djinni::JniEnum {
public:
    using CppType = ::snap::valdi_core::AnimationType;
    using JniType = jobject;

    using Boxed = NativeAnimationType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeAnimationType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeAnimationType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeAnimationType() : JniEnum("com/snapchat/client/valdi_core/AnimationType") {}
    friend ::djinni::JniClass<NativeAnimationType>;
};

} // namespace djinni_generated_client::valdi_core
