// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "valdi_core/Asset.hpp"

namespace djinni_generated_client::valdi_core {

class NativeAsset final : ::djinni::JniInterface<::snap::valdi_core::Asset, NativeAsset> {
public:
    using CppType = std::shared_ptr<::snap::valdi_core::Asset>;
    using CppOptType = std::shared_ptr<::snap::valdi_core::Asset>;
    using JniType = jobject;

    using Boxed = NativeAsset;

    ~NativeAsset();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeAsset>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeAsset>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeAsset();
    friend ::djinni::JniClass<NativeAsset>;
    friend ::djinni::JniInterface<::snap::valdi_core::Asset, NativeAsset>;

};

} // namespace djinni_generated_client::valdi_core
