// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#include "valdi_core/NativeCancelable.hpp"  // my header
#include "utils/debugging/DjinniPrologue.hpp"

namespace djinni_generated_client::valdi_core {

NativeCancelable::NativeCancelable() : ::djinni::JniInterface<::snap::valdi_core::Cancelable, NativeCancelable>() {}

NativeCancelable::~NativeCancelable() = default;

NativeCancelable::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeCancelable::JavaProxy::~JavaProxy() = default;

void NativeCancelable::JavaProxy::cancel() {
    DJINNI_FUNCTION_PROLOGUE("Cancelable.cancel");
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated_client::valdi_core::NativeCancelable>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_cancel);
    ::djinni::jniExceptionCheck(jniEnv);
}

} // namespace djinni_generated_client::valdi_core
