// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#include "valdi_core/NativeModuleFactory.hpp"  // my header
#include "utils/debugging/DjinniPrologue.hpp"
#include "valdi_core/bindings/InternedStringTranslator_jni.hpp"
#include "valdi_core/bindings/ValueTranslator_jni.hpp"

namespace djinni_generated_client::valdi_core {

NativeModuleFactory::NativeModuleFactory() : ::djinni::JniInterface<::snap::valdi_core::ModuleFactory, NativeModuleFactory>("com/snapchat/client/valdi_core/ModuleFactory$CppProxy") {}

NativeModuleFactory::~NativeModuleFactory() = default;

NativeModuleFactory::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeModuleFactory::JavaProxy::~JavaProxy() = default;

Valdi::StringBox NativeModuleFactory::JavaProxy::getModulePath() {
    DJINNI_FUNCTION_PROLOGUE("ModuleFactory.getModulePath");
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated_client::valdi_core::NativeModuleFactory>::get();
    auto jret = jniEnv->CallObjectMethod(Handle::get().get(), data.method_getModulePath);
    ::djinni::jniExceptionCheck(jniEnv);
    return ValdiAndroid::InternedStringTranslator::toCpp(jniEnv, jret);
}
Valdi::Value NativeModuleFactory::JavaProxy::loadModule() {
    DJINNI_FUNCTION_PROLOGUE("ModuleFactory.loadModule");
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated_client::valdi_core::NativeModuleFactory>::get();
    auto jret = jniEnv->CallObjectMethod(Handle::get().get(), data.method_loadModule);
    ::djinni::jniExceptionCheck(jniEnv);
    return ValdiAndroid::ValueTranslator::toCpp(jniEnv, jret);
}

CJNIEXPORT void JNICALL Java_com_snapchat_client_valdi_1core_ModuleFactory_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("ModuleFactory.nativeDestroy");
        delete reinterpret_cast<::djinni::CppProxyHandle<::snap::valdi_core::ModuleFactory>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT ValdiAndroid::InternedStringTranslator::JniType JNICALL Java_com_snapchat_client_valdi_1core_ModuleFactory_00024CppProxy_native_1getModulePath(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("ModuleFactory.native_getModulePath");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi_core::ModuleFactory>(nativeRef);
        auto r = ref->getModulePath();
        return ::djinni::release(ValdiAndroid::InternedStringTranslator::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT ValdiAndroid::ValueTranslator::JniType JNICALL Java_com_snapchat_client_valdi_1core_ModuleFactory_00024CppProxy_native_1loadModule(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("ModuleFactory.native_loadModule");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi_core::ModuleFactory>(nativeRef);
        auto r = ref->loadModule();
        return ::djinni::release(ValdiAndroid::ValueTranslator::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated_client::valdi_core
