// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "valdi_core/JavaScriptEngineType.hpp"

namespace djinni_generated_client::valdi_core {

class NativeJavaScriptEngineType final : ::djinni::JniEnum {
public:
    using CppType = ::snap::valdi_core::JavaScriptEngineType;
    using JniType = jobject;

    using Boxed = NativeJavaScriptEngineType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeJavaScriptEngineType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeJavaScriptEngineType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeJavaScriptEngineType() : JniEnum("com/snapchat/client/valdi_core/JavaScriptEngineType") {}
    friend ::djinni::JniClass<NativeJavaScriptEngineType>;
};

} // namespace djinni_generated_client::valdi_core
