// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "valdi_core/ModuleFactoriesProvider.hpp"

namespace djinni_generated_client::valdi_core {

class NativeModuleFactoriesProvider final : ::djinni::JniInterface<::snap::valdi_core::ModuleFactoriesProvider, NativeModuleFactoriesProvider> {
public:
    using CppType = std::shared_ptr<::snap::valdi_core::ModuleFactoriesProvider>;
    using CppOptType = std::shared_ptr<::snap::valdi_core::ModuleFactoriesProvider>;
    using JniType = jobject;

    using Boxed = NativeModuleFactoriesProvider;

    ~NativeModuleFactoriesProvider();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeModuleFactoriesProvider>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeModuleFactoriesProvider>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeModuleFactoriesProvider();
    friend ::djinni::JniClass<NativeModuleFactoriesProvider>;
    friend ::djinni::JniInterface<::snap::valdi_core::ModuleFactoriesProvider, NativeModuleFactoriesProvider>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::snap::valdi_core::ModuleFactoriesProvider
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        std::vector</*not-null*/ std::shared_ptr<::snap::valdi_core::ModuleFactory>> createModuleFactories(const Valdi::Value & runtimeManager) override;

    private:
        friend ::djinni::JniInterface<::snap::valdi_core::ModuleFactoriesProvider, ::djinni_generated_client::valdi_core::NativeModuleFactoriesProvider>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/snapchat/client/valdi_core/ModuleFactoriesProvider") };
    const jmethodID method_createModuleFactories { ::djinni::jniGetMethodID(clazz.get(), "createModuleFactories", "(Ljava/lang/Object;)Ljava/util/ArrayList;") };
};

} // namespace djinni_generated_client::valdi_core
