// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#include "valdi_core/NativeAnimator.hpp"  // my header
#include "utils/debugging/DjinniPrologue.hpp"
#include "valdi_core/bindings/ValueTranslator_jni.hpp"

namespace djinni_generated_client::valdi_core {

NativeAnimator::NativeAnimator() : ::djinni::JniInterface<::snap::valdi_core::Animator, NativeAnimator>() {}

NativeAnimator::~NativeAnimator() = default;

NativeAnimator::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeAnimator::JavaProxy::~JavaProxy() = default;

void NativeAnimator::JavaProxy::flushAnimations(const Valdi::Value & c_completion) {
    DJINNI_FUNCTION_PROLOGUE("Animator.flushAnimations");
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated_client::valdi_core::NativeAnimator>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_flushAnimations,
                           ::djinni::get(ValdiAndroid::ValueTranslator::fromCpp(jniEnv, c_completion)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeAnimator::JavaProxy::cancel() {
    DJINNI_FUNCTION_PROLOGUE("Animator.cancel");
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated_client::valdi_core::NativeAnimator>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_cancel);
    ::djinni::jniExceptionCheck(jniEnv);
}

} // namespace djinni_generated_client::valdi_core
