// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "valdi_core/AssetOutputType.hpp"

namespace djinni_generated_client::valdi_core {

class NativeAssetOutputType final : ::djinni::JniEnum {
public:
    using CppType = ::snap::valdi_core::AssetOutputType;
    using JniType = jobject;

    using Boxed = NativeAssetOutputType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeAssetOutputType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeAssetOutputType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeAssetOutputType() : JniEnum("com/snapchat/client/valdi_core/AssetOutputType") {}
    friend ::djinni::JniClass<NativeAssetOutputType>;
};

} // namespace djinni_generated_client::valdi_core
