// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#include "valdi_core/bindings/UndefExceptions_jni.hpp"
#include "valdi_core/NativeHTTPRequestManagerCompletion.hpp"  // my header
#include "djinni/jni/Marshal.hpp"
#include "utils/debugging/DjinniPrologue.hpp"
#include "valdi_core/NativeHTTPResponse.hpp"

namespace djinni_generated_client::valdi_core {

NativeHTTPRequestManagerCompletion::NativeHTTPRequestManagerCompletion() : ::djinni::JniInterface<::snap::valdi_core::HTTPRequestManagerCompletion, NativeHTTPRequestManagerCompletion>("com/snapchat/client/valdi_core/HTTPRequestManagerCompletion$CppProxy") {}

NativeHTTPRequestManagerCompletion::~NativeHTTPRequestManagerCompletion() = default;


CJNIEXPORT void JNICALL Java_com_snapchat_client_valdi_1core_HTTPRequestManagerCompletion_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("HTTPRequestManagerCompletion.nativeDestroy");
        delete reinterpret_cast<::djinni::CppProxyHandle<::snap::valdi_core::HTTPRequestManagerCompletion>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_snapchat_client_valdi_1core_HTTPRequestManagerCompletion_00024CppProxy_native_1onComplete(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_response)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("HTTPRequestManagerCompletion.native_onComplete");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi_core::HTTPRequestManagerCompletion>(nativeRef);
        ref->onComplete(::djinni_generated_client::valdi_core::NativeHTTPResponse::toCpp(jniEnv, j_response));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_snapchat_client_valdi_1core_HTTPRequestManagerCompletion_00024CppProxy_native_1onFail(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_error)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("HTTPRequestManagerCompletion.native_onFail");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi_core::HTTPRequestManagerCompletion>(nativeRef);
        ref->onFail(::djinni::String::toCpp(jniEnv, j_error));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

} // namespace djinni_generated_client::valdi_core
