// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#include "valdi_core/NativeModuleFactoriesProvider.hpp"  // my header
#include "djinni/jni/Marshal.hpp"
#include "utils/debugging/DjinniPrologue.hpp"
#include "valdi_core/NativeModuleFactory.hpp"
#include "valdi_core/bindings/ValueTranslator_jni.hpp"

namespace djinni_generated_client::valdi_core {

NativeModuleFactoriesProvider::NativeModuleFactoriesProvider() : ::djinni::JniInterface<::snap::valdi_core::ModuleFactoriesProvider, NativeModuleFactoriesProvider>("com/snapchat/client/valdi_core/ModuleFactoriesProvider$CppProxy") {}

NativeModuleFactoriesProvider::~NativeModuleFactoriesProvider() = default;

NativeModuleFactoriesProvider::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeModuleFactoriesProvider::JavaProxy::~JavaProxy() = default;

std::vector</*not-null*/ std::shared_ptr<::snap::valdi_core::ModuleFactory>> NativeModuleFactoriesProvider::JavaProxy::createModuleFactories(const Valdi::Value & c_runtimeManager) {
    DJINNI_FUNCTION_PROLOGUE("ModuleFactoriesProvider.createModuleFactories");
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated_client::valdi_core::NativeModuleFactoriesProvider>::get();
    auto jret = jniEnv->CallObjectMethod(Handle::get().get(), data.method_createModuleFactories,
                                         ::djinni::get(ValdiAndroid::ValueTranslator::fromCpp(jniEnv, c_runtimeManager)));
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni::List<::djinni_generated_client::valdi_core::NativeModuleFactory>::toCpp(jniEnv, jret);
}

CJNIEXPORT void JNICALL Java_com_snapchat_client_valdi_1core_ModuleFactoriesProvider_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("ModuleFactoriesProvider.nativeDestroy");
        delete reinterpret_cast<::djinni::CppProxyHandle<::snap::valdi_core::ModuleFactoriesProvider>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_snapchat_client_valdi_1core_ModuleFactoriesProvider_00024CppProxy_native_1createModuleFactories(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, ValdiAndroid::ValueTranslator::JniType j_runtimeManager)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("ModuleFactoriesProvider.native_createModuleFactories");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi_core::ModuleFactoriesProvider>(nativeRef);
        auto r = ref->createModuleFactories(ValdiAndroid::ValueTranslator::toCpp(jniEnv, j_runtimeManager));
        return ::djinni::release(::djinni::List<::djinni_generated_client::valdi_core::NativeModuleFactory>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated_client::valdi_core
