// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#include "valdi_core/NativeHTTPRequest.hpp"  // my header
#include "djinni/jni/Marshal.hpp"
#include "valdi_core/bindings/BytesTranslator_jni.hpp"
#include "valdi_core/bindings/InternedStringTranslator_jni.hpp"
#include "valdi_core/bindings/ValueTranslator_jni.hpp"

namespace djinni_generated_client::valdi_core {

NativeHTTPRequest::NativeHTTPRequest() = default;

NativeHTTPRequest::~NativeHTTPRequest() = default;

auto NativeHTTPRequest::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeHTTPRequest>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(ValdiAndroid::InternedStringTranslator::fromCpp(jniEnv, c.url)),
                                                           ::djinni::get(ValdiAndroid::InternedStringTranslator::fromCpp(jniEnv, c.method)),
                                                           ::djinni::get(ValdiAndroid::ValueTranslator::fromCpp(jniEnv, c.headers)),
                                                           ::djinni::get(::djinni::Optional<std::optional, ValdiAndroid::BytesTranslator>::fromCpp(jniEnv, c.body)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.priority)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeHTTPRequest::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 6);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeHTTPRequest>::get();
    return {ValdiAndroid::InternedStringTranslator::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mUrl)),
            ValdiAndroid::InternedStringTranslator::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mMethod)),
            ValdiAndroid::ValueTranslator::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mHeaders)),
            ::djinni::Optional<std::optional, ValdiAndroid::BytesTranslator>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mBody)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mPriority))};
}

} // namespace djinni_generated_client::valdi_core
