// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#include "valdi_core/NativeAsset.hpp"  // my header
#include "djinni/jni/Marshal.hpp"
#include "utils/debugging/DjinniPrologue.hpp"
#include "valdi_core/NativeAssetLoadObserver.hpp"
#include "valdi_core/NativeAssetOutputType.hpp"
#include "valdi_core/bindings/InternedStringTranslator_jni.hpp"
#include "valdi_core/bindings/ValueTranslator_jni.hpp"

namespace djinni_generated_client::valdi_core {

NativeAsset::NativeAsset() : ::djinni::JniInterface<::snap::valdi_core::Asset, NativeAsset>("com/snapchat/client/valdi_core/Asset$CppProxy") {}

NativeAsset::~NativeAsset() = default;


CJNIEXPORT void JNICALL Java_com_snapchat_client_valdi_1core_Asset_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("Asset.nativeDestroy");
        delete reinterpret_cast<::djinni::CppProxyHandle<::snap::valdi_core::Asset>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT ValdiAndroid::InternedStringTranslator::JniType JNICALL Java_com_snapchat_client_valdi_1core_Asset_00024CppProxy_native_1getIdentifier(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("Asset.native_getIdentifier");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi_core::Asset>(nativeRef);
        auto r = ref->getIdentifier();
        return ::djinni::release(ValdiAndroid::InternedStringTranslator::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jdouble JNICALL Java_com_snapchat_client_valdi_1core_Asset_00024CppProxy_native_1measureWidth(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jdouble j_maxWidth, jdouble j_maxHeight)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("Asset.native_measureWidth");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi_core::Asset>(nativeRef);
        auto r = ref->measureWidth(::djinni::F64::toCpp(jniEnv, j_maxWidth),
                                   ::djinni::F64::toCpp(jniEnv, j_maxHeight));
        return ::djinni::release(::djinni::F64::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jdouble JNICALL Java_com_snapchat_client_valdi_1core_Asset_00024CppProxy_native_1measureHeight(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jdouble j_maxWidth, jdouble j_maxHeight)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("Asset.native_measureHeight");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi_core::Asset>(nativeRef);
        auto r = ref->measureHeight(::djinni::F64::toCpp(jniEnv, j_maxWidth),
                                    ::djinni::F64::toCpp(jniEnv, j_maxHeight));
        return ::djinni::release(::djinni::F64::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_snapchat_client_valdi_1core_Asset_00024CppProxy_native_1addLoadObserver(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_observer, jobject j_outputType, jint j_preferredWidth, jint j_preferredHeight, ValdiAndroid::ValueTranslator::JniType j_filter)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("Asset.native_addLoadObserver");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi_core::Asset>(nativeRef);
        ref->addLoadObserver(::djinni_generated_client::valdi_core::NativeAssetLoadObserver::toCpp(jniEnv, j_observer),
                             ::djinni_generated_client::valdi_core::NativeAssetOutputType::toCpp(jniEnv, j_outputType),
                             ::djinni::I32::toCpp(jniEnv, j_preferredWidth),
                             ::djinni::I32::toCpp(jniEnv, j_preferredHeight),
                             ValdiAndroid::ValueTranslator::toCpp(jniEnv, j_filter));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_snapchat_client_valdi_1core_Asset_00024CppProxy_native_1removeLoadObserver(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_observer)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("Asset.native_removeLoadObserver");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi_core::Asset>(nativeRef);
        ref->removeLoadObserver(::djinni_generated_client::valdi_core::NativeAssetLoadObserver::toCpp(jniEnv, j_observer));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_snapchat_client_valdi_1core_Asset_00024CppProxy_native_1updateLoadObserverPreferredSize(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_observer, jint j_preferredWidth, jint j_preferredHeight)
{
    try {
        DJINNI_FUNCTION_PROLOGUE("Asset.native_updateLoadObserverPreferredSize");
        const auto& ref = ::djinni::objectFromHandleAddress<::snap::valdi_core::Asset>(nativeRef);
        ref->updateLoadObserverPreferredSize(::djinni_generated_client::valdi_core::NativeAssetLoadObserver::toCpp(jniEnv, j_observer),
                                             ::djinni::I32::toCpp(jniEnv, j_preferredWidth),
                                             ::djinni::I32::toCpp(jniEnv, j_preferredHeight));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

} // namespace djinni_generated_client::valdi_core
