// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "valdi_core/AssetLoadObserver.hpp"

namespace djinni_generated_client::valdi_core {

class NativeAssetLoadObserver final : ::djinni::JniInterface<::snap::valdi_core::AssetLoadObserver, NativeAssetLoadObserver> {
public:
    using CppType = std::shared_ptr<::snap::valdi_core::AssetLoadObserver>;
    using CppOptType = std::shared_ptr<::snap::valdi_core::AssetLoadObserver>;
    using JniType = jobject;

    using Boxed = NativeAssetLoadObserver;

    ~NativeAssetLoadObserver();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeAssetLoadObserver>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeAssetLoadObserver>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeAssetLoadObserver();
    friend ::djinni::JniClass<NativeAssetLoadObserver>;
    friend ::djinni::JniInterface<::snap::valdi_core::AssetLoadObserver, NativeAssetLoadObserver>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::snap::valdi_core::AssetLoadObserver
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void onLoad(const /*not-null*/ std::shared_ptr<::snap::valdi_core::Asset> & asset, const Valdi::Value & loadedAsset, const std::optional<Valdi::StringBox> & error) override;

    private:
        friend ::djinni::JniInterface<::snap::valdi_core::AssetLoadObserver, ::djinni_generated_client::valdi_core::NativeAssetLoadObserver>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/snapchat/client/valdi_core/AssetLoadObserver") };
    const jmethodID method_onLoad { ::djinni::jniGetMethodID(clazz.get(), "onLoad", "(Lcom/snapchat/client/valdi_core/Asset;Ljava/lang/Object;Ljava/lang/String;)V") };
};

} // namespace djinni_generated_client::valdi_core
