// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "valdi_core/Animator.hpp"

namespace djinni_generated_client::valdi_core {

class NativeAnimator final : ::djinni::JniInterface<::snap::valdi_core::Animator, NativeAnimator> {
public:
    using CppType = std::shared_ptr<::snap::valdi_core::Animator>;
    using CppOptType = std::shared_ptr<::snap::valdi_core::Animator>;
    using JniType = jobject;

    using Boxed = NativeAnimator;

    ~NativeAnimator();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeAnimator>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeAnimator>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeAnimator();
    friend ::djinni::JniClass<NativeAnimator>;
    friend ::djinni::JniInterface<::snap::valdi_core::Animator, NativeAnimator>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::snap::valdi_core::Animator
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void flushAnimations(const Valdi::Value & completion) override;
        void cancel() override;

    private:
        friend ::djinni::JniInterface<::snap::valdi_core::Animator, ::djinni_generated_client::valdi_core::NativeAnimator>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/snapchat/client/valdi_core/Animator") };
    const jmethodID method_flushAnimations { ::djinni::jniGetMethodID(clazz.get(), "flushAnimations", "(Ljava/lang/Object;)V") };
    const jmethodID method_cancel { ::djinni::jniGetMethodID(clazz.get(), "cancel", "()V") };
};

} // namespace djinni_generated_client::valdi_core
