// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "valdi_core/HTTPResponse.hpp"

namespace djinni_generated_client::valdi_core {

class NativeHTTPResponse final {
public:
    using CppType = ::snap::valdi_core::HTTPResponse;
    using JniType = jobject;

    using Boxed = NativeHTTPResponse;

    ~NativeHTTPResponse();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeHTTPResponse();
    friend ::djinni::JniClass<NativeHTTPResponse>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/snapchat/client/valdi_core/HTTPResponse") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(ILjava/lang/Object;[B)V") };
    const jfieldID field_mStatusCode { ::djinni::jniGetFieldID(clazz.get(), "mStatusCode", "I") };
    const jfieldID field_mHeaders { ::djinni::jniGetFieldID(clazz.get(), "mHeaders", "Ljava/lang/Object;") };
    const jfieldID field_mBody { ::djinni::jniGetFieldID(clazz.get(), "mBody", "[B") };
};

} // namespace djinni_generated_client::valdi_core
