// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "valdi_core/ModuleFactory.hpp"

namespace djinni_generated_client::valdi_core {

class NativeModuleFactory final : ::djinni::JniInterface<::snap::valdi_core::ModuleFactory, NativeModuleFactory> {
public:
    using CppType = std::shared_ptr<::snap::valdi_core::ModuleFactory>;
    using CppOptType = std::shared_ptr<::snap::valdi_core::ModuleFactory>;
    using JniType = jobject;

    using Boxed = NativeModuleFactory;

    ~NativeModuleFactory();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeModuleFactory>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeModuleFactory>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeModuleFactory();
    friend ::djinni::JniClass<NativeModuleFactory>;
    friend ::djinni::JniInterface<::snap::valdi_core::ModuleFactory, NativeModuleFactory>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::snap::valdi_core::ModuleFactory
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        Valdi::StringBox getModulePath() override;
        Valdi::Value loadModule() override;

    private:
        friend ::djinni::JniInterface<::snap::valdi_core::ModuleFactory, ::djinni_generated_client::valdi_core::NativeModuleFactory>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/snapchat/client/valdi_core/ModuleFactory") };
    const jmethodID method_getModulePath { ::djinni::jniGetMethodID(clazz.get(), "getModulePath", "()Ljava/lang/String;") };
    const jmethodID method_loadModule { ::djinni::jniGetMethodID(clazz.get(), "loadModule", "()Ljava/lang/Object;") };
};

} // namespace djinni_generated_client::valdi_core
