// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#include "valdi_core/NativeAssetLoadObserver.hpp"  // my header
#include "djinni/jni/Marshal.hpp"
#include "utils/debugging/DjinniPrologue.hpp"
#include "valdi_core/NativeAsset.hpp"
#include "valdi_core/bindings/InternedStringTranslator_jni.hpp"
#include "valdi_core/bindings/ValueTranslator_jni.hpp"

namespace djinni_generated_client::valdi_core {

NativeAssetLoadObserver::NativeAssetLoadObserver() : ::djinni::JniInterface<::snap::valdi_core::AssetLoadObserver, NativeAssetLoadObserver>() {}

NativeAssetLoadObserver::~NativeAssetLoadObserver() = default;

NativeAssetLoadObserver::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeAssetLoadObserver::JavaProxy::~JavaProxy() = default;

void NativeAssetLoadObserver::JavaProxy::onLoad(const /*not-null*/ std::shared_ptr<::snap::valdi_core::Asset> & c_asset, const Valdi::Value & c_loadedAsset, const std::optional<Valdi::StringBox> & c_error) {
    DJINNI_FUNCTION_PROLOGUE("AssetLoadObserver.onLoad");
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated_client::valdi_core::NativeAssetLoadObserver>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onLoad,
                           ::djinni::get(::djinni_generated_client::valdi_core::NativeAsset::fromCpp(jniEnv, c_asset)),
                           ::djinni::get(ValdiAndroid::ValueTranslator::fromCpp(jniEnv, c_loadedAsset)),
                           ::djinni::get(::djinni::Optional<std::optional, ValdiAndroid::InternedStringTranslator>::fromCpp(jniEnv, c_error)));
    ::djinni::jniExceptionCheck(jniEnv);
}

} // namespace djinni_generated_client::valdi_core
