// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "valdi_core/Platform.hpp"

namespace djinni_generated_client::valdi_core {

class NativePlatform final : ::djinni::JniEnum {
public:
    using CppType = ::snap::valdi_core::Platform;
    using JniType = jobject;

    using Boxed = NativePlatform;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativePlatform>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativePlatform>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativePlatform() : JniEnum("com/snapchat/client/valdi_core/Platform") {}
    friend ::djinni::JniClass<NativePlatform>;
};

} // namespace djinni_generated_client::valdi_core
