// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "valdi_core/HTTPRequestManager.hpp"

namespace djinni_generated_client::valdi_core {

class NativeHTTPRequestManager final : ::djinni::JniInterface<::snap::valdi_core::HTTPRequestManager, NativeHTTPRequestManager> {
public:
    using CppType = std::shared_ptr<::snap::valdi_core::HTTPRequestManager>;
    using CppOptType = std::shared_ptr<::snap::valdi_core::HTTPRequestManager>;
    using JniType = jobject;

    using Boxed = NativeHTTPRequestManager;

    ~NativeHTTPRequestManager();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeHTTPRequestManager>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeHTTPRequestManager>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeHTTPRequestManager();
    friend ::djinni::JniClass<NativeHTTPRequestManager>;
    friend ::djinni::JniInterface<::snap::valdi_core::HTTPRequestManager, NativeHTTPRequestManager>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::snap::valdi_core::HTTPRequestManager
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        /*not-null*/ std::shared_ptr<::snap::valdi_core::Cancelable> performRequest(const ::snap::valdi_core::HTTPRequest & request, const /*not-null*/ std::shared_ptr<::snap::valdi_core::HTTPRequestManagerCompletion> & completion) override;

    private:
        friend ::djinni::JniInterface<::snap::valdi_core::HTTPRequestManager, ::djinni_generated_client::valdi_core::NativeHTTPRequestManager>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/snapchat/client/valdi_core/HTTPRequestManager") };
    const jmethodID method_performRequest { ::djinni::jniGetMethodID(clazz.get(), "performRequest", "(Lcom/snapchat/client/valdi_core/HTTPRequest;Lcom/snapchat/client/valdi_core/HTTPRequestManagerCompletion;)Lcom/snapchat/client/valdi_core/Cancelable;") };
};

} // namespace djinni_generated_client::valdi_core
