// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#include "valdi_core/NativeHTTPResponse.hpp"  // my header
#include "djinni/jni/Marshal.hpp"
#include "valdi_core/bindings/BytesTranslator_jni.hpp"
#include "valdi_core/bindings/ValueTranslator_jni.hpp"

namespace djinni_generated_client::valdi_core {

NativeHTTPResponse::NativeHTTPResponse() = default;

NativeHTTPResponse::~NativeHTTPResponse() = default;

auto NativeHTTPResponse::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeHTTPResponse>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.statusCode)),
                                                           ::djinni::get(ValdiAndroid::ValueTranslator::fromCpp(jniEnv, c.headers)),
                                                           ::djinni::get(::djinni::Optional<std::optional, ValdiAndroid::BytesTranslator>::fromCpp(jniEnv, c.body)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeHTTPResponse::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 4);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeHTTPResponse>::get();
    return {::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mStatusCode)),
            ValdiAndroid::ValueTranslator::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mHeaders)),
            ::djinni::Optional<std::optional, ValdiAndroid::BytesTranslator>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mBody))};
}

} // namespace djinni_generated_client::valdi_core
