// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "valdi_core/HTTPRequest.hpp"

namespace djinni_generated_client::valdi_core {

class NativeHTTPRequest final {
public:
    using CppType = ::snap::valdi_core::HTTPRequest;
    using JniType = jobject;

    using Boxed = NativeHTTPRequest;

    ~NativeHTTPRequest();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeHTTPRequest();
    friend ::djinni::JniClass<NativeHTTPRequest>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/snapchat/client/valdi_core/HTTPRequest") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;[BI)V") };
    const jfieldID field_mUrl { ::djinni::jniGetFieldID(clazz.get(), "mUrl", "Ljava/lang/String;") };
    const jfieldID field_mMethod { ::djinni::jniGetFieldID(clazz.get(), "mMethod", "Ljava/lang/String;") };
    const jfieldID field_mHeaders { ::djinni::jniGetFieldID(clazz.get(), "mHeaders", "Ljava/lang/Object;") };
    const jfieldID field_mBody { ::djinni::jniGetFieldID(clazz.get(), "mBody", "[B") };
    const jfieldID field_mPriority { ::djinni::jniGetFieldID(clazz.get(), "mPriority", "I") };
};

} // namespace djinni_generated_client::valdi_core
