// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

#ifdef __cplusplus
#import "valdi/SCNValdiKeychain+Private.h"
#import "valdi/SCNValdiKeychain.h"
#import "djinni/objc/DJIMarshal+Private.h"
#import "djinni/objc/DJIObjcWrapperCache+Private.h"
#import "valdi_core/bindings/BytesTranslator_objc.hpp"
#import "valdi_core/bindings/InternedStringTranslator_objc.hpp"
#import "valdi_core/bindings/ResultTranslator_objc.hpp"
#include "utils/debugging/DjinniPrologue.hpp"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated_client::valdi {

class Keychain::ObjcProxy final
: public ::snap::valdi::Keychain
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated_client::valdi::Keychain;
public:
    using ObjcProxyBase::ObjcProxyBase;
    Valdi::PlatformResult store(const Valdi::StringBox & c_key, const Valdi::BytesView & c_value) override
    {
        DJINNI_FUNCTION_PROLOGUE("Keychain.store");
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() store:(ValdiIOS::InternedStringTranslator::fromCpp(c_key))
                                                                            value:(ValdiIOS::BytesTranslator::fromCpp(c_value))];
            return ValdiIOS::ResultTranslator::toCpp(objcpp_result_);
        }
    }
    Valdi::BytesView get(const Valdi::StringBox & c_key) override
    {
        DJINNI_FUNCTION_PROLOGUE("Keychain.get");
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() get:(ValdiIOS::InternedStringTranslator::fromCpp(c_key))];
            return ValdiIOS::BytesTranslator::toCpp(objcpp_result_);
        }
    }
    bool erase(const Valdi::StringBox & c_key) override
    {
        DJINNI_FUNCTION_PROLOGUE("Keychain.erase");
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() erase:(ValdiIOS::InternedStringTranslator::fromCpp(c_key))];
            return ::djinni::Bool::toCpp(objcpp_result_);
        }
    }
};

} // namespace djinni_generated_client::valdi

namespace djinni_generated_client::valdi {

auto Keychain::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto Keychain::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

} // namespace djinni_generated_client::valdi
#endif // __cplusplus
