// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

#import <Foundation/Foundation.h>


@interface SCNValdiJSRuntimeNativeObjectsManager : NSObject

- (nonnull NSObject *)getReachableObjectsDescription;

@end
