// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

#ifdef __cplusplus
#include "valdi/Keychain.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol SCNValdiKeychain;

namespace djinni_generated_client::valdi {

class Keychain
{
public:
    using CppType = std::shared_ptr<::snap::valdi::Keychain>;
    using CppOptType = std::shared_ptr<::snap::valdi::Keychain>;
    using ObjcType = id<SCNValdiKeychain>;

    using Boxed = Keychain;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated_client::valdi

#endif // __cplusplus
