// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

#import "valdi_core/SCValdiResult.h"
#import <Foundation/Foundation.h>


@protocol SCNValdiKeychain <NSObject>

/** Store the given string blob into the keychain */
- (nonnull SCValdiResult *)store:(nonnull NSString *)key
                              value:(nonnull NSData *)value;

/**
 * Retrieve the stored blob for the given key.
 * Returns empty data if the value was not found.
 */
- (nonnull NSData *)get:(nonnull NSString *)key;

/** Erase the stored blob for the given key. */
- (BOOL)erase:(nonnull NSString *)key;

@end
