// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

#ifdef __cplusplus
#import "valdi/SCNValdiJSRuntimeNativeObjectsManager+Private.h"
#import "valdi/SCNValdiJSRuntimeNativeObjectsManager.h"
#import "djinni/objc/DJICppWrapperCache+Private.h"
#import "djinni/objc/DJIError.h"
#import "valdi_core/bindings/ValueTranslator_objc.hpp"
#include "utils/debugging/DjinniPrologue.hpp"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SCNValdiJSRuntimeNativeObjectsManager ()

- (id)initWithCpp:(const std::shared_ptr<::snap::valdi::JSRuntimeNativeObjectsManager>&)cppRef;

@end

@implementation SCNValdiJSRuntimeNativeObjectsManager {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::snap::valdi::JSRuntimeNativeObjectsManager>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::snap::valdi::JSRuntimeNativeObjectsManager>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nonnull NSObject *)getReachableObjectsDescription {
    try {
        DJINNI_FUNCTION_PROLOGUE("JSRuntimeNativeObjectsManager.getReachableObjectsDescription");
        auto objcpp_result_ = _cppRefHandle.get()->getReachableObjectsDescription();
        return ValdiIOS::ValueTranslator::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated_client::valdi {

auto JSRuntimeNativeObjectsManager::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto JSRuntimeNativeObjectsManager::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SCNValdiJSRuntimeNativeObjectsManager>(cpp);
}

} // namespace djinni_generated_client::valdi

@end
#endif // __cplusplus
