// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

#import <Foundation/Foundation.h>


@protocol SCNValdiRuntimeMessageHandler <NSObject>

- (void)onUncaughtJsError:(int32_t)errorCode
               moduleName:(nonnull NSString *)moduleName
             errorMessage:(nonnull NSString *)errorMessage
               stackTrace:(nonnull NSString *)stackTrace;

- (void)onJsCrash:(nonnull NSString *)moduleName
     errorMessage:(nonnull NSString *)errorMessage
       stackTrace:(nonnull NSString *)stackTrace
            isANR:(BOOL)isANR;

- (void)onDebugMessage:(int32_t)level
               message:(nonnull NSString *)message;

@end
