// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

#import <Foundation/Foundation.h>
@class SCNValdiJSRuntime;
@class SCNValdiJSRuntimeNativeObjectsManager;


@interface SCNValdiJSRuntime : NSObject

/**
 * Push the module unmarshalled using the schema in the given marshaller handle
 * into the marshaller.
 */
- (int32_t)pushModuleToMarshaller:(nullable SCNValdiJSRuntimeNativeObjectsManager *)nativeObjectsManager
                             path:(nonnull NSString *)path
                 marshallerHandle:(int64_t)marshallerHandle;

- (void)addModuleUnloadObserver:(nonnull NSString *)path
                       observer:(nonnull NSObject *)observer;

- (void)preloadModule:(nonnull NSString *)path
             maxDepth:(int32_t)maxDepth;

- (nullable SCNValdiJSRuntimeNativeObjectsManager *)createNativeObjectsManager;

- (void)destroyNativeObjectsManager:(nullable SCNValdiJSRuntimeNativeObjectsManager *)nativeObjectsManager;

- (nullable SCNValdiJSRuntime *)createWorker;

- (void)runOnJsThread:(nonnull NSObject *)runnable;

@end
