// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi.djinni

#ifdef __cplusplus
#import "valdi/SCNValdiRuntimeMessageHandler+Private.h"
#import "valdi/SCNValdiRuntimeMessageHandler.h"
#import "djinni/objc/DJICppWrapperCache+Private.h"
#import "djinni/objc/DJIError.h"
#import "djinni/objc/DJIMarshal+Private.h"
#import "djinni/objc/DJIObjcWrapperCache+Private.h"
#import "valdi_core/bindings/InternedStringTranslator_objc.hpp"
#include "utils/debugging/DjinniPrologue.hpp"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SCNValdiRuntimeMessageHandlerCppProxy : NSObject<SCNValdiRuntimeMessageHandler>

- (id)initWithCpp:(const std::shared_ptr<::snap::valdi::RuntimeMessageHandler>&)cppRef;

@end

@implementation SCNValdiRuntimeMessageHandlerCppProxy {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::snap::valdi::RuntimeMessageHandler>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::snap::valdi::RuntimeMessageHandler>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)onUncaughtJsError:(int32_t)errorCode
               moduleName:(nonnull NSString *)moduleName
             errorMessage:(nonnull NSString *)errorMessage
               stackTrace:(nonnull NSString *)stackTrace {
    try {
        DJINNI_FUNCTION_PROLOGUE("RuntimeMessageHandler.onUncaughtJsError");
        _cppRefHandle.get()->onUncaughtJsError(::djinni::I32::toCpp(errorCode),
                                               ValdiIOS::InternedStringTranslator::toCpp(moduleName),
                                               ::djinni::String::toCpp(errorMessage),
                                               ::djinni::String::toCpp(stackTrace));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)onJsCrash:(nonnull NSString *)moduleName
     errorMessage:(nonnull NSString *)errorMessage
       stackTrace:(nonnull NSString *)stackTrace
            isANR:(BOOL)isANR {
    try {
        DJINNI_FUNCTION_PROLOGUE("RuntimeMessageHandler.onJsCrash");
        _cppRefHandle.get()->onJsCrash(ValdiIOS::InternedStringTranslator::toCpp(moduleName),
                                       ::djinni::String::toCpp(errorMessage),
                                       ::djinni::String::toCpp(stackTrace),
                                       ::djinni::Bool::toCpp(isANR));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)onDebugMessage:(int32_t)level
               message:(nonnull NSString *)message {
    try {
        DJINNI_FUNCTION_PROLOGUE("RuntimeMessageHandler.onDebugMessage");
        _cppRefHandle.get()->onDebugMessage(::djinni::I32::toCpp(level),
                                            ::djinni::String::toCpp(message));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated_client::valdi {

class RuntimeMessageHandler::ObjcProxy final
: public ::snap::valdi::RuntimeMessageHandler
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated_client::valdi::RuntimeMessageHandler;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void onUncaughtJsError(int32_t c_errorCode, const Valdi::StringBox & c_moduleName, const std::string & c_errorMessage, const std::string & c_stackTrace) override
    {
        DJINNI_FUNCTION_PROLOGUE("RuntimeMessageHandler.onUncaughtJsError");
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onUncaughtJsError:(::djinni::I32::fromCpp(c_errorCode))
                                                             moduleName:(ValdiIOS::InternedStringTranslator::fromCpp(c_moduleName))
                                                           errorMessage:(::djinni::String::fromCpp(c_errorMessage))
                                                             stackTrace:(::djinni::String::fromCpp(c_stackTrace))];
        }
    }
    void onJsCrash(const Valdi::StringBox & c_moduleName, const std::string & c_errorMessage, const std::string & c_stackTrace, bool c_isANR) override
    {
        DJINNI_FUNCTION_PROLOGUE("RuntimeMessageHandler.onJsCrash");
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onJsCrash:(ValdiIOS::InternedStringTranslator::fromCpp(c_moduleName))
                                                   errorMessage:(::djinni::String::fromCpp(c_errorMessage))
                                                     stackTrace:(::djinni::String::fromCpp(c_stackTrace))
                                                          isANR:(::djinni::Bool::fromCpp(c_isANR))];
        }
    }
    void onDebugMessage(int32_t c_level, const std::string & c_message) override
    {
        DJINNI_FUNCTION_PROLOGUE("RuntimeMessageHandler.onDebugMessage");
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onDebugMessage:(::djinni::I32::fromCpp(c_level))
                                                             message:(::djinni::String::fromCpp(c_message))];
        }
    }
};

} // namespace djinni_generated_client::valdi

namespace djinni_generated_client::valdi {

auto RuntimeMessageHandler::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    if ([(id)objc isKindOfClass:[SCNValdiRuntimeMessageHandlerCppProxy class]]) {
        return ((SCNValdiRuntimeMessageHandlerCppProxy*)objc)->_cppRefHandle.get();
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto RuntimeMessageHandler::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    if (auto cppPtr = dynamic_cast<ObjcProxy*>(cpp.get())) {
        return cppPtr->djinni_private_get_proxied_objc_object();
    }
    return ::djinni::get_cpp_proxy<SCNValdiRuntimeMessageHandlerCppProxy>(cpp);
}

} // namespace djinni_generated_client::valdi

@end
#endif // __cplusplus
