//
//  FileHeaderCommentGenerator.swift
//  Compiler
//
//  Created by Simon Corsin on 7/21/18.
//  Copyright © 2018 Snap Inc. All rights reserved.
//

import Foundation

struct FileHeaderCommentGenerator {

    static func generateMultilineComment(comment: String) -> String {
        let commentLines = comment
            .split(separator: "\n", maxSplits: Int.max, omittingEmptySubsequences: false)
            .map { "* \($0)" }
            .joined(separator: "\n")

        return """
        /**
        \(commentLines)
        */
        """
    }

    private static func generateHeaderMessage(sourceFilename: GeneratedSourceFilename) -> String {
        return """
        Generated from type '\(sourceFilename.symbolName)' at '\(sourceFilename.filename)' by the Valdi compiler.
        Please do not edit this file directly.
        """
    }

    static func generateFactoryHeaderMessage(className: String, sourceFilename: GeneratedSourceFilename) -> String {
        let commentMessage = """
        Generated factory for '\(className)' at '\(sourceFilename.filename)' by the Valdi compiler.
        Needed for native dependency injection.
        Please do not edit this file directly.
        """

        return generateMultilineComment(comment: commentMessage)
    }

    static func generateComment(sourceFilename: GeneratedSourceFilename, additionalComments: String? = nil) -> String {
        var commentMessage = generateHeaderMessage(sourceFilename: sourceFilename)

        if let additionalComments = additionalComments, !additionalComments.isEmpty {
            commentMessage = "\(additionalComments)\n\n\(commentMessage)"
        }

        return generateMultilineComment(comment: commentMessage)
    }

}
